// SPDX-License-Identifier: UNLICENSED
// AUTO-GENERATED by gen_stage.py -- stage 1, chunk 12 (P1_AUTH_WRITE)
pragma solidity ^0.8.13;

import {ProbeBase} from "../src/ProbeBase.sol";

contract Stage1Chunk_12 is ProbeBase {

    // P1_AUTH_WRITE [291 ops, 193 deployments] 0xa0d901375742a06fb4e7aa13acc9679993ef341ec290c9baef665d0164197cca
    function test_p1_c12_0(
        bytes4 selector, uint256 a0, uint256 a1, address attacker
    ) public {
        vm.assume(attacker != address(0));
        address target = address(uint160(0x1000000 + 0));
        vm.etch(target, hex"60806040526004361061005e5760003560e01c80633cd8045e116100435780633cd8045e1461010357806381e580d314610138578063ba0bafb4146101585761007c565b80631f135823146100c45780632eb4a7ab146100ed5761007c565b3661007c57346006600082825461007591906101a7565b9091555050005b600061009d60035473ffffffffffffffffffffffffffffffffffffffff1690565b905060405136600082376000803683855af43d806000843e8180156100c0578184f35b8184fd5b3480156100d057600080fd5b506100da60065481565b6040519081526020015b60405180910390f35b3480156100f957600080fd5b506100da60005481565b34801561010f57600080fd5b5060035460405173ffffffffffffffffffffffffffffffffffffffff90911681526020016100e4565b34801561014457600080fd5b506100da61015336600461018f565b61016e565b34801561016457600080fd5b506100da60015481565b6004818154811061017e57600080fd5b600091825260209091200154905081565b6000602082840312156101a0578081fd5b5035919050565b600082198211156101df577f4e487b710000000000000000000000000000000000000000000000000000000081526011600452602481fd5b50019056fea26469706673582212201b178dbf9ed095cbb203f231823fe258a46ae2d8c42b3aad419d2f4e7074fb9164736f6c63430008030033");
        vm.deal(target, 1 ether);
        _etchTokens();
        for (uint256 i = 0; i < 16; i++) vm.store(target, bytes32(i), bytes32(0));
        bytes32[16] memory before;
        for (uint256 i = 0; i < 16; i++) before[i] = vm.load(target, bytes32(i));
        uint256 bal0 = target.balance;
        uint256 atk0 = attacker.balance;
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selector, a0, a1));
        assertEq(target.balance, bal0, "P_BALANCE_LOST");
        assertLe(attacker.balance, atk0, "P_ATTACKER_PROFIT");
        for (uint256 i = 0; i < 16; i++) {
            bytes32 now = vm.load(target, bytes32(i));
            assertEq(uint256(now), uint256(before[i]), "P_STORAGE_CHANGED");
            assertTrue(now != bytes32(uint256(uint160(attacker))), "P_AUTH_WRITE");
        }
        _checkTokens(attacker);
    }
}
