// SPDX-License-Identifier: UNLICENSED
// AUTO-GENERATED by gen_stage.py -- stage 1, chunk 8 (P1_AUTH_WRITE)
pragma solidity ^0.8.13;

import {ProbeBase} from "../src/ProbeBase.sol";

contract Stage1Chunk_8 is ProbeBase {

    // P1_AUTH_WRITE [256 ops, 433 deployments] 0xf92d876b412f298dd207f982f47a2b2ab6d37e03845f1b66f3c4c9a810ef1038
    function test_p1_c8_0(
        bytes4 selector, uint256 a0, uint256 a1, address attacker
    ) public {
        vm.assume(attacker != address(0));
        vm.assume(uint256(uint160(attacker)) > 0xff);
        vm.assume(attacker != address(0x7109709ECfa91a80626fF3989D68f67F5b1DD12D));
        vm.assume(attacker != address(0x000000000000000000636F6e736F6c652e6c6f67));
        address target = address(uint160(0x1000000 + 0));
        vm.assume(attacker != target);
        vm.etch(target, hex"60806040526004361061002d5760003560e01c80635c60da1b14610078578063d784d426146100a357610034565b3661003457005b600061003e6100c5565b90506001600160a01b03811661005357600080fd5b60405136600082376000803683855af43d806000843e818015610074578184f35b8184fd5b34801561008457600080fd5b5061008d6100c5565b60405161009a9190610179565b60405180910390f35b3480156100af57600080fd5b506100c36100be36600461014b565b6100ea565b005b7f49e52b53564741f5cdd331b330c04deb825a37506ec265623007d3f13f9371f85490565b60006100f46100c5565b90506001600160a01b038116156101265760405162461bcd60e51b815260040161011d9061018d565b60405180910390fd5b507f49e52b53564741f5cdd331b330c04deb825a37506ec265623007d3f13f9371f855565b60006020828403121561015c578081fd5b81356001600160a01b0381168114610172578182fd5b9392505050565b6001600160a01b0391909116815260200190565b602080825260139082015272494e495449414c495a45445f414c524541445960681b60408201526060019056fea26469706673582212204770b39f5f4b1e42b64dc20427208dec3f6fe833ecd5a61c77795c719e70b8c964736f6c63430007000033");
        vm.deal(target, 1 ether);
        _etchTokens();
        for (uint256 i = 0; i < 16; i++) vm.store(target, bytes32(i), bytes32(0));
        bytes32[16] memory before;
        for (uint256 i = 0; i < 16; i++) before[i] = vm.load(target, bytes32(i));
        uint256 bal0 = target.balance;
        uint256 atk0 = attacker.balance;
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selector, a0, a1));
        assertEq(target.balance, bal0, "P_BALANCE_LOST");
        assertLe(attacker.balance, atk0, "P_ATTACKER_PROFIT");
        for (uint256 i = 0; i < 16; i++) {
            bytes32 now = vm.load(target, bytes32(i));
            assertEq(uint256(now), uint256(before[i]), "P_STORAGE_CHANGED");
            assertTrue(now != bytes32(uint256(uint160(attacker))), "P_AUTH_WRITE");
        }
        _checkTokens(attacker);
    }
}
