// SPDX-License-Identifier: UNLICENSED
// AUTO-GENERATED by gen_stage.py -- stage 1, chunk 36 (P2_BALANCE)
pragma solidity ^0.8.13;

import {ProbeBase} from "../src/ProbeBase.sol";

contract Stage1Chunk_36 is ProbeBase {

    // P2_BALANCE [561 ops, 37 deployments] 0x5883d381eced509f5b449de069110bb31f5234c879660f7ce3a6fdd5a16a74a9
    function test_p2_c36_0(
        bytes4 selector, uint256 a0, uint256 a1, address attacker
    ) public {
        vm.assume(attacker != address(0));
        vm.assume(uint256(uint160(attacker)) > 0xff);
        vm.assume(attacker != address(0x7109709ECfa91a80626fF3989D68f67F5b1DD12D));
        vm.assume(attacker != address(0x000000000000000000636F6e736F6c652e6c6f67));
        address target = address(uint160(0x1000000 + 0));
        vm.assume(attacker != target);
        vm.etch(target, hex"6080604052600436106100495760003560e01c8062f55d9d146100cb57806313af4035146100ed578063150b7a021461010d5780635bb478081461016e578063ca5eb5e11461018e575b6001546001600160a01b031632146100a75760405162461bcd60e51b815260206004820152601560248201527f43616e206e6f742063616c6c2066616c6c6261636b0000000000000000000000604482015260640160405180910390fd5b600080543682833781823684845af490503d82833e8080156100c7573d83f35b8283fd5b3480156100d757600080fd5b506100eb6100e636600461027c565b6101ae565b005b3480156100f957600080fd5b506100eb61010836600461027c565b6101d1565b34801561011957600080fd5b5061013961012836600461029f565b630a85bd0160e11b95945050505050565b6040517fffffffff00000000000000000000000000000000000000000000000000000000909116815260200160405180910390f35b34801561017a57600080fd5b506100eb61018936600461027c565b61020a565b34801561019a57600080fd5b506100eb6101a936600461027c565b610243565b6002546001600160a01b031633146101c557600080fd5b806001600160a01b0316ff5b6002546001600160a01b031633146101e857600080fd5b600180546001600160a01b0319166001600160a01b0392909216919091179055565b6002546001600160a01b0316331461022157600080fd5b600280546001600160a01b0319166001600160a01b0392909216919091179055565b6002546001600160a01b0316331461025a57600080fd5b600080546001600160a01b0319166001600160a01b0392909216919091179055565b60006020828403121561028d578081fd5b813561029881610339565b9392505050565b6000806000806000608086880312156102b6578081fd5b85356102c181610339565b945060208601356102d181610339565b935060408601359250606086013567ffffffffffffffff808211156102f4578283fd5b818801915088601f830112610307578283fd5b813581811115610315578384fd5b896020828501011115610326578384fd5b9699959850939650602001949392505050565b6001600160a01b038116811461034e57600080fd5b5056fea26469706673582212204614d468d59050bedf37d23a44703388c98c70f5fd4bd8a24c47064c1e52f73564736f6c63430008040033");
        vm.deal(target, 1 ether);
        _etchTokens();
        for (uint256 i = 0; i < 16; i++) vm.store(target, bytes32(i), bytes32(0));
        bytes32[16] memory before;
        for (uint256 i = 0; i < 16; i++) before[i] = vm.load(target, bytes32(i));
        uint256 bal0 = target.balance;
        uint256 atk0 = attacker.balance;
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selector, a0, a1));
        assertEq(target.balance, bal0, "P_BALANCE_LOST");
        assertLe(attacker.balance, atk0, "P_ATTACKER_PROFIT");
        for (uint256 i = 0; i < 16; i++) {
            bytes32 now = vm.load(target, bytes32(i));
            assertEq(uint256(now), uint256(before[i]), "P_STORAGE_CHANGED");
            assertTrue(now != bytes32(uint256(uint160(attacker))), "P_AUTH_WRITE");
        }
        _checkTokens(attacker);
    }

    // P2_BALANCE [52 ops, 35 deployments] 0x7bf71f786c4d36aecf77e6b12fda8c5018bf98d31253bd0d2864bf1b60868b87
    function test_p2_c36_1(
        bytes4 selector, uint256 a0, uint256 a1, address attacker
    ) public {
        vm.assume(attacker != address(0));
        vm.assume(uint256(uint160(attacker)) > 0xff);
        vm.assume(attacker != address(0x7109709ECfa91a80626fF3989D68f67F5b1DD12D));
        vm.assume(attacker != address(0x000000000000000000636F6e736F6c652e6c6f67));
        address target = address(uint160(0x1000000 + 1));
        vm.assume(attacker != target);
        vm.etch(target, hex"3d3d3d3d363d3d37603d6035363936603d013d73cd80c916b1194beb48abf007d0b79a7238436d565af43d3d93803e603357fd5bf3b16c1342e617a5b6e4b631eb114483fdb289c0a4432f962d8209781da23fb37b6b59ee15de7d9841ec0a7a26456b8451aefc4b00393ce1beff5eb3e902");
        vm.deal(target, 1 ether);
        _etchTokens();
        for (uint256 i = 0; i < 16; i++) vm.store(target, bytes32(i), bytes32(0));
        bytes32[16] memory before;
        for (uint256 i = 0; i < 16; i++) before[i] = vm.load(target, bytes32(i));
        uint256 bal0 = target.balance;
        uint256 atk0 = attacker.balance;
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selector, a0, a1));
        assertEq(target.balance, bal0, "P_BALANCE_LOST");
        assertLe(attacker.balance, atk0, "P_ATTACKER_PROFIT");
        for (uint256 i = 0; i < 16; i++) {
            bytes32 now = vm.load(target, bytes32(i));
            assertEq(uint256(now), uint256(before[i]), "P_STORAGE_CHANGED");
            assertTrue(now != bytes32(uint256(uint160(attacker))), "P_AUTH_WRITE");
        }
        _checkTokens(attacker);
    }
}
