// SPDX-License-Identifier: UNLICENSED
// AUTO-GENERATED by gen_stage.py -- stage 1, chunk 18 (P1_AUTH_WRITE)
pragma solidity ^0.8.13;

import {Test} from "forge-std/Test.sol";

contract Stage1Chunk_18 is Test {

    // P1_AUTH_WRITE [49 ops, 94 deployments] 0x3fbde051a9d39cfcb37dd6218d71046822495909f2ec186b85cee31df48c4317
    function test_p1_c18_0(
        bytes4 selector, uint256 a0, uint256 a1, address attacker
    ) public {
        vm.assume(attacker != address(0));
        address target = address(uint160(0x1000000 + 0));
        vm.etch(target, hex"3d3d3d3d363d3d37603d6035363936603d013d7308ce97807a81896e85841d74fb7e7b065ab3ef055af43d3d93803e603357fd5bf3b16c1342e617a5b6e4b631eb114483fdb289c0a45b6ac51d9b1cede0068a1b26533cace807f883ee7093431941e810bec79575bad211d5d83d1e552a01");
        vm.deal(target, 1 ether);
        for (uint256 i = 0; i < 8; i++) vm.store(target, bytes32(i), bytes32(0));
        uint256 bal0 = target.balance;
        uint256 atk0 = attacker.balance;
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selector, a0, a1));
        assertEq(target.balance, bal0, "P_BALANCE_LOST");
        assertEq(attacker.balance, atk0, "P_ATTACKER_PROFIT");
        for (uint256 i = 0; i < 8; i++) {
            assertTrue(vm.load(target, bytes32(i)) != bytes32(uint256(uint160(attacker))), "P_AUTH_WRITE");
        }
    }
}
