// SPDX-License-Identifier: UNLICENSED
// AUTO-GENERATED by gen_stage.py -- stage 1, chunk 0 (CONTROLS)
pragma solidity ^0.8.13;

import {ProbeBase} from "../src/ProbeBase.sol";

contract Stage1Chunk_0 is ProbeBase {

    // CONTROL_MUST_FAIL VulnerableControl
    function test_control_vulnerable(
        bytes4 selector, uint256 a0, uint256 a1, address attacker
    ) public {
        vm.assume(attacker != address(0));
        address target = address(uint160(0x1000000 + 0));
        vm.etch(target, hex"608060405234801561000f575f80fd5b506004361061004a575f3560e01c806313af40351461004e57806341c0e1b51461006a5780638da5cb5b14610074578063f07745be14610092575b5f80fd5b61006860048036038101906100639190610194565b6100b0565b005b6100726100f2565b005b61007c61010b565b60405161008991906101ce565b60405180910390f35b61009a61012e565b6040516100a791906101ff565b60405180910390f35b805f806101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555050565b3373ffffffffffffffffffffffffffffffffffffffff16ff5b5f8054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b5f6001905090565b5f80fd5b5f73ffffffffffffffffffffffffffffffffffffffff82169050919050565b5f6101638261013a565b9050919050565b61017381610159565b811461017d575f80fd5b50565b5f8135905061018e8161016a565b92915050565b5f602082840312156101a9576101a8610136565b5b5f6101b684828501610180565b91505092915050565b6101c881610159565b82525050565b5f6020820190506101e15f8301846101bf565b92915050565b5f819050919050565b6101f9816101e7565b82525050565b5f6020820190506102125f8301846101f0565b9291505056fea2646970667358221220269bf5183d96056df2f09d14e08852ceaae5eb063bff40e4d12018189f65ba3b64736f6c63430008180033");
        vm.deal(target, 1 ether);
        _etchTokens();
        for (uint256 i = 0; i < 16; i++) vm.store(target, bytes32(i), bytes32(0));
        bytes32[16] memory before;
        for (uint256 i = 0; i < 16; i++) before[i] = vm.load(target, bytes32(i));
        uint256 bal0 = target.balance;
        uint256 atk0 = attacker.balance;
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selector, a0, a1));
        assertEq(target.balance, bal0, "P_BALANCE_LOST");
        assertLe(attacker.balance, atk0, "P_ATTACKER_PROFIT");
        for (uint256 i = 0; i < 16; i++) {
            bytes32 now = vm.load(target, bytes32(i));
            assertEq(uint256(now), uint256(before[i]), "P_STORAGE_CHANGED");
            assertTrue(now != bytes32(uint256(uint160(attacker))), "P_AUTH_WRITE");
        }
        _checkTokens(attacker);
    }

    // CONTROL_MUST_PASS SafeControl
    function test_control_safe(
        bytes4 selector, uint256 a0, uint256 a1, address attacker
    ) public {
        vm.assume(attacker != address(0));
        address target = address(uint160(0x1000000 + 0));
        vm.etch(target, hex"608060405234801561000f575f80fd5b506004361061003f575f3560e01c806313af4035146100435780638da5cb5b1461005f578063f07745be1461007d575b5f80fd5b61005d600480360381019061005891906101f3565b61009b565b005b61006761016a565b604051610074919061022d565b60405180910390f35b61008561018d565b604051610092919061025e565b60405180910390f35b5f8054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff1614610128576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040161011f906102d1565b60405180910390fd5b805f806101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555050565b5f8054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b5f6001905090565b5f80fd5b5f73ffffffffffffffffffffffffffffffffffffffff82169050919050565b5f6101c282610199565b9050919050565b6101d2816101b8565b81146101dc575f80fd5b50565b5f813590506101ed816101c9565b92915050565b5f6020828403121561020857610207610195565b5b5f610215848285016101df565b91505092915050565b610227816101b8565b82525050565b5f6020820190506102405f83018461021e565b92915050565b5f819050919050565b61025881610246565b82525050565b5f6020820190506102715f83018461024f565b92915050565b5f82825260208201905092915050565b7f61757468000000000000000000000000000000000000000000000000000000005f82015250565b5f6102bb600483610277565b91506102c682610287565b602082019050919050565b5f6020820190508181035f8301526102e8816102af565b905091905056fea264697066735822122012c4ed83debbed7a71152d73437a67d86fe14aa82139be8c37e9f5fb575f2f8964736f6c63430008180033");
        vm.deal(target, 1 ether);
        _etchTokens();
        for (uint256 i = 0; i < 16; i++) vm.store(target, bytes32(i), bytes32(0));
        bytes32[16] memory before;
        for (uint256 i = 0; i < 16; i++) before[i] = vm.load(target, bytes32(i));
        uint256 bal0 = target.balance;
        uint256 atk0 = attacker.balance;
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selector, a0, a1));
        assertEq(target.balance, bal0, "P_BALANCE_LOST");
        assertLe(attacker.balance, atk0, "P_ATTACKER_PROFIT");
        for (uint256 i = 0; i < 16; i++) {
            bytes32 now = vm.load(target, bytes32(i));
            assertEq(uint256(now), uint256(before[i]), "P_STORAGE_CHANGED");
            assertTrue(now != bytes32(uint256(uint160(attacker))), "P_AUTH_WRITE");
        }
        _checkTokens(attacker);
    }
}
