// SPDX-License-Identifier: UNLICENSED
// AUTO-GENERATED by gen_track_a.py -- stage tracka_a7small, chunk 3 (a7_unchecked)
pragma solidity ^0.8.13;

import {ProbeBaseA} from "../src/ProbeBaseA.sol";

contract Stagetracka_a7smallChunk_3 is ProbeBaseA {

    function _probeSingle(
        bytes memory code, uint256 idx, bytes4 selector,
        uint256 a0, uint256 a1, address attacker, bool zeroed
    ) internal {
        address target = address(uint160(0x1700000 + idx));
        _assumeAttacker(attacker, target);
        vm.etch(target, code);
        vm.deal(target, 1 ether);
        if (zeroed) { _seedZeroed(target); } else { _seedSymbolic(target); }
        _snapshotTarget(target);
        _snapshotTokens();
        _markBalances(target, attacker);
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selector, a0, a1));
        _checkTarget(target, attacker, zeroed);
    }
    // a7_unchecked [26 ops, 1 deploys] 0xbf0c6e73839704acd2f2988f2b342b2d4f13eed788a8b640c45914be30a61dee
    function _code_0() internal pure returns (bytes memory) { return hex"61014435365f604037606060403660405f73111111125421ca6dc452d289314280a0f8842a655af150604051101561003657600380fd5b00"; }

    function test_a7_c3_0_z(
        bytes4 selector, uint256 a0, uint256 a1, address attacker
    ) public {
        _probeSingle(_code_0(), 0, selector, a0, a1, attacker, true);
    }

    function test_a7_c3_0_s(
        bytes4 selector, uint256 a0, uint256 a1, address attacker
    ) public {
        _probeSingle(_code_0(), 0, selector, a0, a1, attacker, false);
    }

}

