// SPDX-License-Identifier: UNLICENSED
// AUTO-GENERATED by gen_track_a.py -- stage tracka_a7small, chunk 2 (a7_unchecked)
pragma solidity ^0.8.13;

import {ProbeBaseA} from "../src/ProbeBaseA.sol";

contract Stagetracka_a7smallChunk_2 is ProbeBaseA {

    function _probeSingle(
        bytes memory code, uint256 idx, bytes4 selector,
        uint256 a0, uint256 a1, address attacker, bool zeroed
    ) internal {
        address target = address(uint160(0x1700000 + idx));
        _assumeAttacker(attacker, target);
        vm.etch(target, code);
        vm.deal(target, 1 ether);
        if (zeroed) { _seedZeroed(target); } else { _seedSymbolic(target); }
        _snapshotTarget(target);
        _snapshotTokens();
        _markBalances(target, attacker);
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selector, a0, a1));
        _checkTarget(target, attacker, zeroed);
    }
    // a7_unchecked [27 ops, 2 deploys] 0xdb96ded93727f9d9877cc39b215ba6e2f753313cb09082aac2132131f5f88556
    function _code_0() internal pure returns (bytes memory) { return hex"7fc2a407530000000000000000000000000000000000000000000000000000000034526034602060103760203460443473111111125421ca6dc452d289314280a0f8842a655afa345119343511605157005b5934fd"; }

    function test_a7_c2_0_z(
        bytes4 selector, uint256 a0, uint256 a1, address attacker
    ) public {
        _probeSingle(_code_0(), 0, selector, a0, a1, attacker, true);
    }

    function test_a7_c2_0_s(
        bytes4 selector, uint256 a0, uint256 a1, address attacker
    ) public {
        _probeSingle(_code_0(), 0, selector, a0, a1, attacker, false);
    }

    // a7_unchecked [25 ops, 1 deploys] 0xdaa551bdb6ba8f9c79bb9c7a4f78470c74b630ee6f1622d6dfb41118edb1736c
    function _code_1() internal pure returns (bytes memory) { return hex"7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5f350363a9059cbb5f52336020526040525f5f6044601c5f73dac17f958d2ee523a2206206994597c13d831ec75af15f5260205ff3"; }

    function test_a7_c2_1_z(
        bytes4 selector, uint256 a0, uint256 a1, address attacker
    ) public {
        _probeSingle(_code_1(), 1, selector, a0, a1, attacker, true);
    }

    function test_a7_c2_1_s(
        bytes4 selector, uint256 a0, uint256 a1, address attacker
    ) public {
        _probeSingle(_code_1(), 1, selector, a0, a1, attacker, false);
    }

}

