// SPDX-License-Identifier: UNLICENSED
// AUTO-GENERATED by gen_track_a.py -- stage tracka_a7small, chunk 1 (a7_unchecked)
pragma solidity ^0.8.13;

import {ProbeBaseA} from "../src/ProbeBaseA.sol";

contract Stagetracka_a7smallChunk_1 is ProbeBaseA {

    function _probeSingle(
        bytes memory code, uint256 idx, bytes4 selector,
        uint256 a0, uint256 a1, address attacker, bool zeroed
    ) internal {
        address target = address(uint160(0x1700000 + idx));
        _assumeAttacker(attacker, target);
        vm.etch(target, code);
        vm.deal(target, 1 ether);
        if (zeroed) { _seedZeroed(target); } else { _seedSymbolic(target); }
        _snapshotTarget(target);
        _snapshotTokens();
        _markBalances(target, attacker);
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selector, a0, a1));
        _checkTarget(target, attacker, zeroed);
    }
    // a7_unchecked [26 ops, 3 deploys] 0x8cd5a574bdc50bd5534d139d3c04ceb0ba942c000c54f25b43800ddec9e58d67
    function _code_0() internal pure returns (bytes memory) { return hex"7f6004600c60003960046000f3600035ff00000000000000000000000000000000600052602060006000f05b60003560005260008060208180856006f1505a6080106200002b57"; }

    function test_a7_c1_0_z(
        bytes4 selector, uint256 a0, uint256 a1, address attacker
    ) public {
        _probeSingle(_code_0(), 0, selector, a0, a1, attacker, true);
    }

    function test_a7_c1_0_s(
        bytes4 selector, uint256 a0, uint256 a1, address attacker
    ) public {
        _probeSingle(_code_0(), 0, selector, a0, a1, attacker, false);
    }

    // a7_unchecked [25 ops, 2 deploys] 0xed52d10638055876d13f77a0ec244ed13f37d33faec35559d8530ed958305567
    function _code_1() internal pure returns (bytes memory) { return hex"5f357fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff0163a9059cbb5f52336020526040525f5f6044601c5f73dac17f958d2ee523a2206206994597c13d831ec75af15f5260205ff3"; }

    function test_a7_c1_1_z(
        bytes4 selector, uint256 a0, uint256 a1, address attacker
    ) public {
        _probeSingle(_code_1(), 1, selector, a0, a1, attacker, true);
    }

    function test_a7_c1_1_s(
        bytes4 selector, uint256 a0, uint256 a1, address attacker
    ) public {
        _probeSingle(_code_1(), 1, selector, a0, a1, attacker, false);
    }

}

