// SPDX-License-Identifier: UNLICENSED
// AUTO-GENERATED by gen_stage.py -- stage 2, chunk 9 (P4_TWO_PHASE)
pragma solidity ^0.8.13;

import {ProbeBase} from "../src/ProbeBase.sol";

contract Stage2Chunk_9 is ProbeBase {

    // P4_TWO_PHASE [93 ops, 4 deployments] 0x09bbaa47cc2cd2909493541a304356d83502e4a9971fcd756b68dc71c028b675
    function test_p4_c9_0(
        bytes4 selA, uint256 prime, bytes4 selB, uint256 a, uint256 b, address attacker
    ) public {
        vm.assume(attacker != address(0));
        vm.assume(uint256(uint160(attacker)) > 0xff);
        vm.assume(attacker != address(0x7109709ECfa91a80626fF3989D68f67F5b1DD12D));
        vm.assume(attacker != address(0x000000000000000000636F6e736F6c652e6c6f67));
        address target = address(uint160(0x2000000 + 0));
        vm.assume(attacker != target);
        vm.etch(target, hex"0089504e470d0a1a0a0000000d4948445200000020000000200806000000737a7af4000000017352474200aece1ce90000005a494441545885edd0b10a00200845d1faff8fb6a5c1c84c4368b9670a5ea9d91a00009ff5c45d516ff45967e9dad10124d47ecfaef5ef0388f9bbb8eef7c86fc07a7dce0a36701a626de065a564b6b2feec65c543bc6500009806079e1afcd108330f0000000049454e44ae426082");
        vm.deal(target, 1 ether);
        _etchTokens();
        for (uint256 i = 0; i < 16; i++) vm.store(target, bytes32(i), bytes32(0));
        bytes32[16] memory before;
        for (uint256 i = 0; i < 16; i++) before[i] = vm.load(target, bytes32(i));
        uint256 bal0 = target.balance;
        uint256 atk0 = attacker.balance;
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selA, prime));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selB, a, b));
        assertEq(target.balance, bal0, "P_BALANCE_LOST");
        assertLe(attacker.balance, atk0, "P_ATTACKER_PROFIT");
        for (uint256 i = 0; i < 16; i++) {
            bytes32 now = vm.load(target, bytes32(i));
            assertEq(uint256(now), uint256(before[i]), "P_STORAGE_CHANGED");
            assertTrue(now != bytes32(uint256(uint160(attacker))), "P_AUTH_WRITE");
        }
        _checkTokens(attacker);
    }

    // P4_TWO_PHASE [225 ops, 3 deployments] 0x106ecd9cd5e42f383e77d43f7797fdfa2dbccdd67bbad9c986635684a5b5f5d8
    function test_p4_c9_1(
        bytes4 selA, uint256 prime, bytes4 selB, uint256 a, uint256 b, address attacker
    ) public {
        vm.assume(attacker != address(0));
        vm.assume(uint256(uint160(attacker)) > 0xff);
        vm.assume(attacker != address(0x7109709ECfa91a80626fF3989D68f67F5b1DD12D));
        vm.assume(attacker != address(0x000000000000000000636F6e736F6c652e6c6f67));
        address target = address(uint160(0x2000000 + 1));
        vm.assume(attacker != target);
        vm.etch(target, hex"00000300010a01e66b31678d6c16e9ebf358268a790b763c13375000000000000000000000000000e4005cf5402600000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee000000000000000000000000eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee00000000000000000000000000000000000000000000000000000000000000000000000000000000000000006982508145454ce325ddbe47a25d4ec3d231193300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000");
        vm.deal(target, 1 ether);
        _etchTokens();
        for (uint256 i = 0; i < 16; i++) vm.store(target, bytes32(i), bytes32(0));
        bytes32[16] memory before;
        for (uint256 i = 0; i < 16; i++) before[i] = vm.load(target, bytes32(i));
        uint256 bal0 = target.balance;
        uint256 atk0 = attacker.balance;
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selA, prime));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selB, a, b));
        assertEq(target.balance, bal0, "P_BALANCE_LOST");
        assertLe(attacker.balance, atk0, "P_ATTACKER_PROFIT");
        for (uint256 i = 0; i < 16; i++) {
            bytes32 now = vm.load(target, bytes32(i));
            assertEq(uint256(now), uint256(before[i]), "P_STORAGE_CHANGED");
            assertTrue(now != bytes32(uint256(uint160(attacker))), "P_AUTH_WRITE");
        }
        _checkTokens(attacker);
    }
}
