// SPDX-License-Identifier: UNLICENSED
// AUTO-GENERATED by gen_stage.py -- stage 2, chunk 11 (P4_TWO_PHASE)
pragma solidity ^0.8.13;

import {Test} from "forge-std/Test.sol";

contract Stage2Chunk_11 is Test {

    // P4_TWO_PHASE [100 ops, 4 deployments] 0x79e2fa99794a7763982cdf10a613f9c537b557d5cc0362a6472a30bbe2009d0b
    function test_p4_c11_0(
        bytes4 selA, uint256 prime, bytes4 selB, uint256 a, uint256 b, address attacker
    ) public {
        vm.assume(attacker != address(0));
        address target = address(uint160(0x2000000 + 0));
        vm.etch(target, hex"0089504e470d0a1a0a0000000d4948445200000020000000200806000000737a7af4000000017352474200aece1ce90000008a494441545885edd24b0e83300c04d01994eeb91057e9ae172b47e140654f24778564c8c754ea8e79cb3872267100111191bb63b4e1f3328c53b65a6d5d120134eb7c3ec2fea977f0a919ccdcda9c8bba67ef2d3abb1fa0762b9287107e8f99810c2f5c187ac57549dc9fd9876839bcd03f02b4ec216a017f0dd11c41d1389aa9fb1357e72f222202005f978e3364996a30d50000000049454e44ae426082");
        vm.deal(target, 1 ether);
        for (uint256 i = 0; i < 8; i++) vm.store(target, bytes32(i), bytes32(0));
        uint256 bal0 = target.balance;
        uint256 atk0 = attacker.balance;
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selA, prime));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selB, a, b));
        assertEq(target.balance, bal0, "P_BALANCE_LOST");
        assertEq(attacker.balance, atk0, "P_ATTACKER_PROFIT");
        for (uint256 i = 0; i < 8; i++) {
            assertTrue(vm.load(target, bytes32(i)) != bytes32(uint256(uint160(attacker))), "P_AUTH_WRITE");
        }
    }

    // P4_TWO_PHASE [269 ops, 4 deployments] 0xb6aa9c41d9ab516ee44e94fb5f27e3a51706cffb76659497a2f5d2077bcdf52f
    function test_p4_c11_1(
        bytes4 selA, uint256 prime, bytes4 selB, uint256 a, uint256 b, address attacker
    ) public {
        vm.assume(attacker != address(0));
        address target = address(uint160(0x2000000 + 1));
        vm.etch(target, hex"36151561000857005b60206100148138610109565b600082828239805191508054600480838437600160e01b83510463c4627c5d81146100575763776d1a0181146100a657631e77933e81146100c0578384fd6100d5565b84331461006960018286331417610131565b3683863761007f60026001548751148317610131565b506100a1600385866060516100968b6040516100e1565b8b518a515af1610131565b6100d5565b6100b282863314610131565b8582853783516001556100d5565b6100cc82863314610131565b85828537835184555b50505050505000610149565b60008282019050600182821183831417101561010257600060005260206000fd5b5b92915050565b60008282039050600182821083831417101561012a57600060005260206000fd5b5b92915050565b6001811015610144578160005260206000fd5b5b5050565b0000000000000000000000000ea6b5edc8905c85514b3676703f1bfe6ec260ad0000000000000000000000003e947a271a37ae7b59921c57be0a3246ee0d887c");
        vm.deal(target, 1 ether);
        for (uint256 i = 0; i < 8; i++) vm.store(target, bytes32(i), bytes32(0));
        uint256 bal0 = target.balance;
        uint256 atk0 = attacker.balance;
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selA, prime));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selB, a, b));
        assertEq(target.balance, bal0, "P_BALANCE_LOST");
        assertEq(attacker.balance, atk0, "P_ATTACKER_PROFIT");
        for (uint256 i = 0; i < 8; i++) {
            assertTrue(vm.load(target, bytes32(i)) != bytes32(uint256(uint160(attacker))), "P_AUTH_WRITE");
        }
    }
}
