// SPDX-License-Identifier: UNLICENSED
// AUTO-GENERATED by gen_stage.py -- stage 2, chunk 15 (P4_TWO_PHASE)
pragma solidity ^0.8.13;

import {ProbeBase} from "../src/ProbeBase.sol";

contract Stage2Chunk_15 is ProbeBase {

    // P4_TWO_PHASE [107 ops, 4 deployments] 0xbf1ce3a599950d8a40a152415b9cf39ececf818e674c89918abaa8e42070da0b
    function test_p4_c15_0(
        bytes4 selA, uint256 prime, bytes4 selB, uint256 a, uint256 b, address attacker
    ) public {
        vm.assume(attacker != address(0));
        address target = address(uint160(0x2000000 + 0));
        vm.etch(target, hex"0089504e470d0a1a0a0000000d4948445200000020000000200806000000737a7af4000000017352474200aece1ce900000060494441545885edd2bb0d80300c45515b620c26635cd6a0cd1e4e6b07115ba441e29ef6e5f3ac44040080bfd3ea4233b3db6655cdb2e502e1f0e696efc39d0f5956644b1bfa294f171cb52c931608ae97d944f90f88c4e718279c6500007c5a07788023fe40d5ff650000000049454e44ae426082");
        vm.deal(target, 1 ether);
        _etchTokens();
        for (uint256 i = 0; i < 16; i++) vm.store(target, bytes32(i), bytes32(0));
        bytes32[16] memory before;
        for (uint256 i = 0; i < 16; i++) before[i] = vm.load(target, bytes32(i));
        uint256 bal0 = target.balance;
        uint256 atk0 = attacker.balance;
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selA, prime));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selB, a, b));
        assertEq(target.balance, bal0, "P_BALANCE_LOST");
        assertLe(attacker.balance, atk0, "P_ATTACKER_PROFIT");
        for (uint256 i = 0; i < 16; i++) {
            bytes32 now = vm.load(target, bytes32(i));
            assertEq(uint256(now), uint256(before[i]), "P_STORAGE_CHANGED");
            assertTrue(now != bytes32(uint256(uint160(attacker))), "P_AUTH_WRITE");
        }
        _checkTokens(attacker);
    }

    // P4_TWO_PHASE [225 ops, 3 deployments] 0x106ecd9cd5e42f383e77d43f7797fdfa2dbccdd67bbad9c986635684a5b5f5d8
    function test_p4_c15_1(
        bytes4 selA, uint256 prime, bytes4 selB, uint256 a, uint256 b, address attacker
    ) public {
        vm.assume(attacker != address(0));
        address target = address(uint160(0x2000000 + 1));
        vm.etch(target, hex"00000300010a01e66b31678d6c16e9ebf358268a790b763c13375000000000000000000000000000e4005cf5402600000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee000000000000000000000000eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee00000000000000000000000000000000000000000000000000000000000000000000000000000000000000006982508145454ce325ddbe47a25d4ec3d231193300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000");
        vm.deal(target, 1 ether);
        _etchTokens();
        for (uint256 i = 0; i < 16; i++) vm.store(target, bytes32(i), bytes32(0));
        bytes32[16] memory before;
        for (uint256 i = 0; i < 16; i++) before[i] = vm.load(target, bytes32(i));
        uint256 bal0 = target.balance;
        uint256 atk0 = attacker.balance;
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selA, prime));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selB, a, b));
        assertEq(target.balance, bal0, "P_BALANCE_LOST");
        assertLe(attacker.balance, atk0, "P_ATTACKER_PROFIT");
        for (uint256 i = 0; i < 16; i++) {
            bytes32 now = vm.load(target, bytes32(i));
            assertEq(uint256(now), uint256(before[i]), "P_STORAGE_CHANGED");
            assertTrue(now != bytes32(uint256(uint160(attacker))), "P_AUTH_WRITE");
        }
        _checkTokens(attacker);
    }
}
