// SPDX-License-Identifier: UNLICENSED
// AUTO-GENERATED by gen_stage.py -- stage 3, chunk 6 (P7_PROFIT)
pragma solidity ^0.8.13;

import {ProbeBase} from "../src/ProbeBase.sol";

contract Stage3Chunk_6 is ProbeBase {

    // P7_PROFIT [246 ops, 36,214 deployments] 0x6683cfc30ed7dd6605aa84788407ff6ef5b76062a60a6dd0c8d1dfac5f801dc5
    function test_p7_c6_0(
        bytes4 s1, uint256 x1, bytes4 s2, uint256 x2, bytes4 s3, uint256 x3, address attacker
    ) public {
        vm.assume(attacker != address(0));
        address target = address(uint160(0x3000000 + 0));
        vm.etch(target, hex"6060604052361561003d576000357c01000000000000000000000000000000000000000000000000000000009004806301681a62146100765761003d565b34610002576100745b610071600160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff16610093565b5b565b005b34610002576100916004808035906020019091905050610093565b005b6000819050600060009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff1614801561024a57508073ffffffffffffffffffffffffffffffffffffffff1663a9059cbb600060009054906101000a900473ffffffffffffffffffffffffffffffffffffffff168373ffffffffffffffffffffffffffffffffffffffff166370a0823130600060405160200152604051827c0100000000000000000000000000000000000000000000000000000000028152600401808273ffffffffffffffffffffffffffffffffffffffff168152602001915050602060405180830381600087803b156100025760325a03f1156100025750505060405180519060200150600060405160200152604051837c0100000000000000000000000000000000000000000000000000000000028152600401808373ffffffffffffffffffffffffffffffffffffffff16815260200182815260200192505050602060405180830381600087803b156100025760325a03f11561000257505050604051805190602001505b151561025557610002565b5b505056");
        vm.deal(target, 1 ether);
        _etchTokens();
        for (uint256 i = 0; i < 16; i++) vm.store(target, bytes32(i), bytes32(0));
        bytes32[16] memory before;
        for (uint256 i = 0; i < 16; i++) before[i] = vm.load(target, bytes32(i));
        uint256 bal0 = target.balance;
        uint256 atk0 = attacker.balance;
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(s1, x1));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(s2, x2));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(s3, x3));
        assertEq(target.balance, bal0, "P_BALANCE_LOST");
        assertLe(attacker.balance, atk0, "P_ATTACKER_PROFIT");
        for (uint256 i = 0; i < 16; i++) {
            bytes32 now = vm.load(target, bytes32(i));
            assertEq(uint256(now), uint256(before[i]), "P_STORAGE_CHANGED");
            assertTrue(now != bytes32(uint256(uint160(attacker))), "P_AUTH_WRITE");
        }
        _checkTokens(attacker);
    }

    // P7_PROFIT [334 ops, 31,285 deployments] 0xb295f581dc18129473ef66c2cefea4da335452a4704bafda2777e09802f528fa
    function test_p7_c6_1(
        bytes4 s1, uint256 x1, bytes4 s2, uint256 x2, bytes4 s3, uint256 x3, address attacker
    ) public {
        vm.assume(attacker != address(0));
        address target = address(uint160(0x3000000 + 1));
        vm.etch(target, hex"60606040523615610060576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff16806341c0e1b5146101545780636b9f96ea14610166578063a4592aa214610178578063b574714f146101ca575b6101525b600034111561014f5734600160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff167fe1fffcc4923d04b559f4d29a8bfc6cda04eb5b0d3c460751c2402c5c5cc9109c60405180905060405180910390a3600260009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16619c403073ffffffffffffffffffffffffffffffffffffffff1631604051809050600060405180830381858888f19350505050151561014e5760006000fd5b5b5b565b005b341561015c57fe5b61016461021c565b005b341561016e57fe5b6101766102b0565b005b341561018057fe5b610188610330565b604051808273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b34156101d257fe5b6101da610356565b604051808273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b600060009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff1614156102ad57600060009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16ff5b5b565b600160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff166108fc3073ffffffffffffffffffffffffffffffffffffffff16319081150290604051809050600060405180830381858888f19350505050151561032d5760006000fd5b5b565b600160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b600260009054906101000a900473ffffffffffffffffffffffffffffffffffffffff16815600a165627a7a723058202952c883ea9c764298347861973db5d0cadeb6be095782fff88d921cf8abebf80029");
        vm.deal(target, 1 ether);
        _etchTokens();
        for (uint256 i = 0; i < 16; i++) vm.store(target, bytes32(i), bytes32(0));
        bytes32[16] memory before;
        for (uint256 i = 0; i < 16; i++) before[i] = vm.load(target, bytes32(i));
        uint256 bal0 = target.balance;
        uint256 atk0 = attacker.balance;
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(s1, x1));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(s2, x2));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(s3, x3));
        assertEq(target.balance, bal0, "P_BALANCE_LOST");
        assertLe(attacker.balance, atk0, "P_ATTACKER_PROFIT");
        for (uint256 i = 0; i < 16; i++) {
            bytes32 now = vm.load(target, bytes32(i));
            assertEq(uint256(now), uint256(before[i]), "P_STORAGE_CHANGED");
            assertTrue(now != bytes32(uint256(uint160(attacker))), "P_AUTH_WRITE");
        }
        _checkTokens(attacker);
    }
}
