// SPDX-License-Identifier: UNLICENSED
// AUTO-GENERATED by gen_stage.py -- stage 3, chunk 16 (P7_PROFIT)
pragma solidity ^0.8.13;

import {ProbeBase} from "../src/ProbeBase.sol";

contract Stage3Chunk_16 is ProbeBase {

    // P7_PROFIT [102 ops, 16,410 deployments] 0x0908d3b05c8d1eb49c03b9427601d12d87c64afe51c71bf257dbbbd3186349d9
    function test_p7_c16_0(
        bytes4 s1, uint256 x1, bytes4 s2, uint256 x2, bytes4 s3, uint256 x3, address attacker
    ) public {
        vm.assume(attacker != address(0));
        vm.assume(uint256(uint160(attacker)) > 0xff);
        vm.assume(attacker != address(0x7109709ECfa91a80626fF3989D68f67F5b1DD12D));
        vm.assume(attacker != address(0x000000000000000000636F6e736F6c652e6c6f67));
        address target = address(uint160(0x3000000 + 0));
        vm.assume(attacker != target);
        vm.etch(target, hex"60606040526000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff16806384b366dc146100485780638da5cb5b1461005d57600080fd5b341561005357600080fd5b61005b6100b2565b005b341561006857600080fd5b6100706100ec565b604051808273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b6000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16ff5b6000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff16815600a165627a7a723058205a4c10330cb883cb9f747ea58909d1c199816042a04ee2ad4817dfd2801e73ef0029");
        vm.deal(target, 1 ether);
        _etchTokens();
        for (uint256 i = 0; i < 16; i++) vm.store(target, bytes32(i), bytes32(0));
        bytes32[16] memory before;
        for (uint256 i = 0; i < 16; i++) before[i] = vm.load(target, bytes32(i));
        uint256 bal0 = target.balance;
        uint256 atk0 = attacker.balance;
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(s1, x1));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(s2, x2));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(s3, x3));
        assertEq(target.balance, bal0, "P_BALANCE_LOST");
        assertLe(attacker.balance, atk0, "P_ATTACKER_PROFIT");
        for (uint256 i = 0; i < 16; i++) {
            bytes32 now = vm.load(target, bytes32(i));
            assertEq(uint256(now), uint256(before[i]), "P_STORAGE_CHANGED");
            assertTrue(now != bytes32(uint256(uint160(attacker))), "P_AUTH_WRITE");
        }
        _checkTokens(attacker);
    }

    // P7_PROFIT [360 ops, 14,931 deployments] 0xde4c9d1a6fb8f3413ac6280a96e70d8d5509a1356742ce84e2978a35c594d053
    function test_p7_c16_1(
        bytes4 s1, uint256 x1, bytes4 s2, uint256 x2, bytes4 s3, uint256 x3, address attacker
    ) public {
        vm.assume(attacker != address(0));
        vm.assume(uint256(uint160(attacker)) > 0xff);
        vm.assume(attacker != address(0x7109709ECfa91a80626fF3989D68f67F5b1DD12D));
        vm.assume(attacker != address(0x000000000000000000636F6e736F6c652e6c6f67));
        address target = address(uint160(0x3000000 + 1));
        vm.assume(attacker != target);
        vm.etch(target, hex"6060604052361561004a576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff168063c0ee0b8a14610053578063f3fef3a3146100d5575b6100515b5b565b005b341561005b57fe5b6100d3600480803573ffffffffffffffffffffffffffffffffffffffff1690602001909190803590602001909190803590602001908201803590602001908080601f0160208091040260200160405190810160405280939291908181526020018383808284378201915050505050509190505061012c565b005b34156100dd57fe5b610112600480803573ffffffffffffffffffffffffffffffffffffffff16906020019091908035906020019091905050610132565b604051808215151515815260200191505060405180910390f35b5b505050565b60006000600060009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1663f2da1a80856000604051602001526040518263ffffffff167c0100000000000000000000000000000000000000000000000000000000028152600401808273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001915050602060405180830381600087803b15156101f857fe5b60325a03f1151561020557fe5b5050506040518051905073ffffffffffffffffffffffffffffffffffffffff16600036600060405160200152604051808383808284378201915050925050506020604051808303818560325a03f4151561025b57fe5b50506040518051905090507f48089fabc73f15b8c6a24d3fdea4a569a4b27661efa87ac952a9f13b0ed881a781604051808215151515815260200191505060405180910390a18091505b50929150505600a165627a7a723058203644ccc5b14e690665067724fe38dce434f92f8a195e459b5a3c4e2873bb9de00029");
        vm.deal(target, 1 ether);
        _etchTokens();
        for (uint256 i = 0; i < 16; i++) vm.store(target, bytes32(i), bytes32(0));
        bytes32[16] memory before;
        for (uint256 i = 0; i < 16; i++) before[i] = vm.load(target, bytes32(i));
        uint256 bal0 = target.balance;
        uint256 atk0 = attacker.balance;
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(s1, x1));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(s2, x2));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(s3, x3));
        assertEq(target.balance, bal0, "P_BALANCE_LOST");
        assertLe(attacker.balance, atk0, "P_ATTACKER_PROFIT");
        for (uint256 i = 0; i < 16; i++) {
            bytes32 now = vm.load(target, bytes32(i));
            assertEq(uint256(now), uint256(before[i]), "P_STORAGE_CHANGED");
            assertTrue(now != bytes32(uint256(uint160(attacker))), "P_AUTH_WRITE");
        }
        _checkTokens(attacker);
    }
}
