// SPDX-License-Identifier: UNLICENSED
// AUTO-GENERATED by gen_stage.py -- stage 3, chunk 11 (P7_PROFIT)
pragma solidity ^0.8.13;

import {ProbeBase} from "../src/ProbeBase.sol";

contract Stage3Chunk_11 is ProbeBase {

    // P7_PROFIT [399 ops, 20,686 deployments] 0x40fe4aa0dae90a0ae92202c2245b6ba88bf754a61a4af2ac03f5f301d558644e
    function test_p7_c11_0(
        bytes4 s1, uint256 x1, bytes4 s2, uint256 x2, bytes4 s3, uint256 x3, address attacker
    ) public {
        vm.assume(attacker != address(0));
        vm.assume(uint256(uint160(attacker)) > 0xff);
        vm.assume(attacker != address(0x7109709ECfa91a80626fF3989D68f67F5b1DD12D));
        vm.assume(attacker != address(0x000000000000000000636F6e736F6c652e6c6f67));
        address target = address(uint160(0x3000000 + 0));
        vm.assume(attacker != target);
        vm.etch(target, hex"60806040526004361061002d5760003560e01c8063893d20e81461011c578063cf6cbb3d1461017357610117565b36610117576000803690501461004257600080fd5b6000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff166108fc349081150290604051600060405180830381858888f193505050501580156100a9573d6000803e3d6000fd5b507f6643d795ec4836e9ebd83ebe59402e7510c7fef7c2d84e7eee10ec77898e1d4a3334604051808373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020018281526020019250505060405180910390a1005b600080fd5b34801561012857600080fd5b506101316101ce565b604051808273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b34801561017f57600080fd5b506101cc6004803603604081101561019657600080fd5b81019080803573ffffffffffffffffffffffffffffffffffffffff169060200190929190803590602001909291905050506101f7565b005b60008060009054906101000a900473ffffffffffffffffffffffffffffffffffffffff16905090565b6000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff161461025057600080fd5b60008290508073ffffffffffffffffffffffffffffffffffffffff1663a9059cbb6000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff16846040518363ffffffff1660e01b8152600401808373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200182815260200192505050600060405180830381600087803b1580156102fd57600080fd5b505af1158015610311573d6000803e3d6000fd5b5050505060003d6000811461032d576020811461033757600080fd5b6000199150610343565b60206000803e60005191505b508061034e57600080fd5b5050505056fea264697066735822122063fe8f2fa2dbda25d02e48cffe12a007baade89f2491b12f9c259644aa435b3464736f6c63430006080033");
        vm.deal(target, 1 ether);
        _etchTokens();
        for (uint256 i = 0; i < 16; i++) vm.store(target, bytes32(i), bytes32(0));
        bytes32[16] memory before;
        for (uint256 i = 0; i < 16; i++) before[i] = vm.load(target, bytes32(i));
        uint256 bal0 = target.balance;
        uint256 atk0 = attacker.balance;
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(s1, x1));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(s2, x2));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(s3, x3));
        assertEq(target.balance, bal0, "P_BALANCE_LOST");
        assertLe(attacker.balance, atk0, "P_ATTACKER_PROFIT");
        for (uint256 i = 0; i < 16; i++) {
            bytes32 now = vm.load(target, bytes32(i));
            assertEq(uint256(now), uint256(before[i]), "P_STORAGE_CHANGED");
            assertTrue(now != bytes32(uint256(uint160(attacker))), "P_AUTH_WRITE");
        }
        _checkTokens(attacker);
    }

    // P7_PROFIT [507 ops, 20,594 deployments] 0x9aa1be13f3d79ada93191d9aba0e19ea9310bc77049ef8aeba839ec8c2c4716c
    function test_p7_c11_1(
        bytes4 s1, uint256 x1, bytes4 s2, uint256 x2, bytes4 s3, uint256 x3, address attacker
    ) public {
        vm.assume(attacker != address(0));
        vm.assume(uint256(uint160(attacker)) > 0xff);
        vm.assume(attacker != address(0x7109709ECfa91a80626fF3989D68f67F5b1DD12D));
        vm.assume(attacker != address(0x000000000000000000636F6e736F6c652e6c6f67));
        address target = address(uint160(0x3000000 + 1));
        vm.assume(attacker != target);
        vm.etch(target, hex"60806040526004361061004b5763ffffffff7c01000000000000000000000000000000000000000000000000000000006000350416633f579f42811461004d578063d2ec4a92146100b6575b005b34801561005957600080fd5b50604080516020600460443581810135601f810184900484028501840190955284845261004b948235600160a060020a03169460248035953695946064949201919081908401838280828437509497506100e79650505050505050565b3480156100c257600080fd5b506100cb6102d9565b60408051600160a060020a039092168252519081900360200190f35b6000809054906101000a9004600160a060020a0316600160a060020a031663c34c08e56040518163ffffffff167c0100000000000000000000000000000000000000000000000000000000028152600401602060405180830381600087803b15801561015257600080fd5b505af1158015610166573d6000803e3d6000fd5b505050506040513d602081101561017c57600080fd5b5051600160a060020a0316331461019257600080fd5b82600160a060020a0316828260405180828051906020019080838360005b838110156101c85781810151838201526020016101b0565b50505050905090810190601f1680156101f55780820380516001836020036101000a031916815260200191505b5091505060006040518083038185875af192505050156102cf577f39f46e1dedea184144e3feaf4e595d78345d9a9d8b43da87912efbe4df3c8a318383836040518084600160a060020a0316600160a060020a0316815260200183815260200180602001828103825283818151815260200191508051906020019080838360005b8381101561028e578181015183820152602001610276565b50505050905090810190601f1680156102bb5780820380516001836020036101000a031916815260200191505b5094505050505060405180910390a16102d4565b600080fd5b505050565b600054600160a060020a0316815600a165627a7a72305820e15ee5e2160fdc89ce720dc909c6dc0f003d58418735db64a66e99fd3338afa30029");
        vm.deal(target, 1 ether);
        _etchTokens();
        for (uint256 i = 0; i < 16; i++) vm.store(target, bytes32(i), bytes32(0));
        bytes32[16] memory before;
        for (uint256 i = 0; i < 16; i++) before[i] = vm.load(target, bytes32(i));
        uint256 bal0 = target.balance;
        uint256 atk0 = attacker.balance;
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(s1, x1));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(s2, x2));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(s3, x3));
        assertEq(target.balance, bal0, "P_BALANCE_LOST");
        assertLe(attacker.balance, atk0, "P_ATTACKER_PROFIT");
        for (uint256 i = 0; i < 16; i++) {
            bytes32 now = vm.load(target, bytes32(i));
            assertEq(uint256(now), uint256(before[i]), "P_STORAGE_CHANGED");
            assertTrue(now != bytes32(uint256(uint160(attacker))), "P_AUTH_WRITE");
        }
        _checkTokens(attacker);
    }
}
