// SPDX-License-Identifier: UNLICENSED
// AUTO-GENERATED by gen_stage.py -- stage 3, chunk 19 (P7_PROFIT)
pragma solidity ^0.8.13;

import {Test} from "forge-std/Test.sol";

contract Stage3Chunk_19 is Test {

    // P7_PROFIT [265 ops, 10,767 deployments] 0xc279544d07d9631b1e37d835cadfe7098d60e508cf8f18a89ddb8b176d56874d
    function test_p7_c19_0(
        bytes4 s1, uint256 x1, bytes4 s2, uint256 x2, bytes4 s3, uint256 x3, address attacker
    ) public {
        vm.assume(attacker != address(0));
        address target = address(uint160(0x3000000 + 0));
        vm.etch(target, hex"6060604052600436106100615763ffffffff7c01000000000000000000000000000000000000000000000000000000006000350416635a6b26ba811461008c5780638da5cb5b146100bb578063ca7d1ccb146100f7578063de242ff41461010f575b60005474010000000000000000000000000000000000000000900460ff16151561008a57600080fd5b005b341561009757600080fd5b61008a73ffffffffffffffffffffffffffffffffffffffff60043516602435610136565b34156100c657600080fd5b6100ce6101a0565b60405173ffffffffffffffffffffffffffffffffffffffff909116815260200160405180910390f35b341561010257600080fd5b61008a60043515156101bc565b341561011a57600080fd5b610122610249565b604051901515815260200160405180910390f35b6000543373ffffffffffffffffffffffffffffffffffffffff90811691161461015e57600080fd5b73ffffffffffffffffffffffffffffffffffffffff821681156108fc0282604051600060405180830381858888f19350505050151561019c57600080fd5b5050565b60005473ffffffffffffffffffffffffffffffffffffffff1681565b6000543373ffffffffffffffffffffffffffffffffffffffff9081169116146101e457600080fd5b60005474010000000000000000000000000000000000000000900460ff16151581151514610246576000805474ff0000000000000000000000000000000000000000191674010000000000000000000000000000000000000000831515021790555b50565b60005474010000000000000000000000000000000000000000900460ff16815600a165627a7a72305820e6bcaab642c13c39fb30fb0986dccbec8fdbf8e54b2228e7fa91400c25e6d29f0029");
        vm.deal(target, 1 ether);
        for (uint256 i = 0; i < 8; i++) vm.store(target, bytes32(i), bytes32(0));
        uint256 bal0 = target.balance;
        uint256 atk0 = attacker.balance;
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(s1, x1));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(s2, x2));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(s3, x3));
        assertEq(target.balance, bal0, "P_TARGET_LOSS");
        assertLe(attacker.balance, atk0, "P_ATTACKER_PROFIT");
        for (uint256 i = 0; i < 8; i++) {
            assertTrue(vm.load(target, bytes32(i)) != bytes32(uint256(uint160(attacker))), "P_AUTH_WRITE");
        }
    }

    // P7_PROFIT [421 ops, 10,100 deployments] 0x4ca475653d166f48143248bc39a0f62b785011c8b4b6daf1021e8dc77afcabcd
    function test_p7_c19_1(
        bytes4 s1, uint256 x1, bytes4 s2, uint256 x2, bytes4 s3, uint256 x3, address attacker
    ) public {
        vm.assume(attacker != address(0));
        address target = address(uint160(0x3000000 + 1));
        vm.etch(target, hex"60806040526004361061004c576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff1680632e1a7d4d146100ec578063928d81c114610119575b6000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1663d0e30db0346040518263ffffffff167c01000000000000000000000000000000000000000000000000000000000281526004016000604051808303818588803b1580156100d157600080fd5b505af11580156100e5573d6000803e3d6000fd5b5050505050005b3480156100f857600080fd5b5061011760048036038101908080359060200190929190505050610166565b005b34801561012557600080fd5b50610164600480360381019080803573ffffffffffffffffffffffffffffffffffffffff16906020019092919080359060200190929190505050610207565b005b6000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1663d0e30db0826040518263ffffffff167c01000000000000000000000000000000000000000000000000000000000281526004016000604051808303818588803b1580156101eb57600080fd5b505af11580156101ff573d6000803e3d6000fd5b505050505050565b8173ffffffffffffffffffffffffffffffffffffffff1663a9059cbb6000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1663d367c5406040518163ffffffff167c0100000000000000000000000000000000000000000000000000000000028152600401602060405180830381600087803b1580156102a857600080fd5b505af11580156102bc573d6000803e3d6000fd5b505050506040513d60208110156102d257600080fd5b8101908080519060200190929190505050836040518363ffffffff167c0100000000000000000000000000000000000000000000000000000000028152600401808373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200182815260200192505050600060405180830381600087803b15801561036957600080fd5b505af115801561037d573d6000803e3d6000fd5b5050505050505600a165627a7a72305820bf56b9a12c43fd69f0ed36bf9123feeb9ea4620f56601719204a8f4a755686f90029");
        vm.deal(target, 1 ether);
        for (uint256 i = 0; i < 8; i++) vm.store(target, bytes32(i), bytes32(0));
        uint256 bal0 = target.balance;
        uint256 atk0 = attacker.balance;
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(s1, x1));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(s2, x2));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(s3, x3));
        assertEq(target.balance, bal0, "P_TARGET_LOSS");
        assertLe(attacker.balance, atk0, "P_ATTACKER_PROFIT");
        for (uint256 i = 0; i < 8; i++) {
            assertTrue(vm.load(target, bytes32(i)) != bytes32(uint256(uint160(attacker))), "P_AUTH_WRITE");
        }
    }
}
