// SPDX-License-Identifier: UNLICENSED
// AUTO-GENERATED by gen_stage.py -- stage 3, chunk 22 (P7_PROFIT)
pragma solidity ^0.8.13;

import {ProbeBase} from "../src/ProbeBase.sol";

contract Stage3Chunk_22 is ProbeBase {

    // P7_PROFIT [531 ops, 8,850 deployments] 0x7163ba9b235b928bb6b4aaa3df40597fe4c95c66757f8444517e301d83ba637b
    function test_p7_c22_0(
        bytes4 s1, uint256 x1, bytes4 s2, uint256 x2, bytes4 s3, uint256 x3, address attacker
    ) public {
        vm.assume(attacker != address(0));
        address target = address(uint160(0x3000000 + 0));
        vm.etch(target, hex"6080604052600436106100565763ffffffff7c0100000000000000000000000000000000000000000000000000000000600035041663578e9dc58114610127578063ce7be2d614610158578063dde9c2971461017e575b60008054604051600a34600981028290049491900492600160a060020a0316916108fc85150291859190818181858888f1935050505015801561009d573d6000803e3d6000fd5b50600154604051600160a060020a039091169082156108fc029083906000818181858888f193505050501580156100d8573d6000803e3d6000fd5b5060005460408051338152600160a060020a0390921660208301523482820152517fed0d2b85ecda74217b5111c81438d31a43b8b4e2c061bfd34d5a1b2d3aab988f9181900360600190a15050005b34801561013357600080fd5b5061013c610193565b60408051600160a060020a039092168252519081900360200190f35b34801561016457600080fd5b5061017c600160a060020a03600435166024356101a2565b005b34801561018a57600080fd5b5061013c610340565b600054600160a060020a031681565b60008054604080517fa9059cbb000000000000000000000000000000000000000000000000000000008152600160a060020a039283166004820152600a6009860281900460248301819052925192949086049387169263a9059cbb926044808201936020939283900390910190829087803b15801561022057600080fd5b505af1158015610234573d6000803e3d6000fd5b505050506040513d602081101561024a57600080fd5b5050600154604080517fa9059cbb000000000000000000000000000000000000000000000000000000008152600160a060020a0392831660048201526024810184905290519186169163a9059cbb916044808201926020929091908290030181600087803b1580156102bb57600080fd5b505af11580156102cf573d6000803e3d6000fd5b505050506040513d60208110156102e557600080fd5b505060005460408051338152600160a060020a0392831660208201529186168282015260608201859052517fa4a78035a9350286d6a0665d9bd4e141f41f3513d3fcdbcef369cef00bf0fb919181900360800190a150505050565b600154600160a060020a0316815600a165627a7a7230582058f28ca17a7bf4592858243137425e5857cc106bf1739267c7f195a0ad1aa4a90029");
        vm.deal(target, 1 ether);
        _etchTokens();
        for (uint256 i = 0; i < 16; i++) vm.store(target, bytes32(i), bytes32(0));
        bytes32[16] memory before;
        for (uint256 i = 0; i < 16; i++) before[i] = vm.load(target, bytes32(i));
        uint256 bal0 = target.balance;
        uint256 atk0 = attacker.balance;
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(s1, x1));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(s2, x2));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(s3, x3));
        assertEq(target.balance, bal0, "P_BALANCE_LOST");
        assertLe(attacker.balance, atk0, "P_ATTACKER_PROFIT");
        for (uint256 i = 0; i < 16; i++) {
            bytes32 now = vm.load(target, bytes32(i));
            assertEq(uint256(now), uint256(before[i]), "P_STORAGE_CHANGED");
            assertTrue(now != bytes32(uint256(uint160(attacker))), "P_AUTH_WRITE");
        }
        _checkTokens(attacker);
    }

    // P7_PROFIT [253 ops, 7,531 deployments] 0x05f2cadb6486616d3ed61a6243af2589c12c30bab95a6f1c720b6bb8b08b90f6
    function test_p7_c22_1(
        bytes4 s1, uint256 x1, bytes4 s2, uint256 x2, bytes4 s3, uint256 x3, address attacker
    ) public {
        vm.assume(attacker != address(0));
        address target = address(uint160(0x3000000 + 1));
        vm.etch(target, hex"6060604052361561003f576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff16806301681a6214610078575b34610000576100765b610073600160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff166100ab565b5b565b005b34610000576100a9600480803573ffffffffffffffffffffffffffffffffffffffff169060200190919050506100ab565b005b6000819050600060009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff1614801561029457508073ffffffffffffffffffffffffffffffffffffffff1663a9059cbb600060009054906101000a900473ffffffffffffffffffffffffffffffffffffffff168373ffffffffffffffffffffffffffffffffffffffff166370a08231306000604051602001526040518263ffffffff167c0100000000000000000000000000000000000000000000000000000000028152600401808273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001915050602060405180830381600087803b156100005760325a03f11561000057505050604051805190506000604051602001526040518363ffffffff167c0100000000000000000000000000000000000000000000000000000000028152600401808373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200182815260200192505050602060405180830381600087803b156100005760325a03f11561000057505050604051805190505b151561029f57610000565b5b50505600a165627a7a72305820751ac97e8cd77b38cc4f02a35daf5fa8b23534d41a9bad70a8c4f0eefaa8eaaf0029");
        vm.deal(target, 1 ether);
        _etchTokens();
        for (uint256 i = 0; i < 16; i++) vm.store(target, bytes32(i), bytes32(0));
        bytes32[16] memory before;
        for (uint256 i = 0; i < 16; i++) before[i] = vm.load(target, bytes32(i));
        uint256 bal0 = target.balance;
        uint256 atk0 = attacker.balance;
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(s1, x1));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(s2, x2));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(s3, x3));
        assertEq(target.balance, bal0, "P_BALANCE_LOST");
        assertLe(attacker.balance, atk0, "P_ATTACKER_PROFIT");
        for (uint256 i = 0; i < 16; i++) {
            bytes32 now = vm.load(target, bytes32(i));
            assertEq(uint256(now), uint256(before[i]), "P_STORAGE_CHANGED");
            assertTrue(now != bytes32(uint256(uint160(attacker))), "P_AUTH_WRITE");
        }
        _checkTokens(attacker);
    }
}
