// SPDX-License-Identifier: UNLICENSED
// AUTO-GENERATED by gen_stage.py -- stage 3, chunk 9 (P7_PROFIT)
pragma solidity ^0.8.13;

import {Test} from "forge-std/Test.sol";

contract Stage3Chunk_9 is Test {

    // P7_PROFIT [290 ops, 22,375 deployments] 0x7c764d7b20b3a2cef2528776af549b65e45fb645c8bb26e3aa932bac7b24b02c
    function test_p7_c9_0(
        bytes4 s1, uint256 x1, bytes4 s2, uint256 x2, bytes4 s3, uint256 x3, address attacker
    ) public {
        vm.assume(attacker != address(0));
        address target = address(uint160(0x3000000 + 0));
        vm.etch(target, hex"606060405260043610610057576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff1680630f24f5c814610059578063521eb2731461009b578063ce3f865f146100f0575b005b341561006457600080fd5b610099600480803573ffffffffffffffffffffffffffffffffffffffff16906020019091908035906020019091905050610113565b005b34156100a657600080fd5b6100ae6101ff565b604051808273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b34156100fb57600080fd5b6101116004808035906020019091905050610224565b005b8173ffffffffffffffffffffffffffffffffffffffff1663a9059cbb6000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff16836000604051602001526040518363ffffffff167c0100000000000000000000000000000000000000000000000000000000028152600401808373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200182815260200192505050602060405180830381600087803b15156101df57600080fd5b6102c65a03f115156101f057600080fd5b50505060405180519050505050565b6000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b6000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff166108fc829081150290604051600060405180830381858888f19350505050151561028557600080fd5b505600a165627a7a72305820c3f3930d598c2dc8755f7b85ba18ed066331a3fed63157ad8887f5adabcafbce0029");
        vm.deal(target, 1 ether);
        for (uint256 i = 0; i < 8; i++) vm.store(target, bytes32(i), bytes32(0));
        uint256 bal0 = target.balance;
        uint256 atk0 = attacker.balance;
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(s1, x1));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(s2, x2));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(s3, x3));
        assertEq(target.balance, bal0, "P_TARGET_LOSS");
        assertLe(attacker.balance, atk0, "P_ATTACKER_PROFIT");
        for (uint256 i = 0; i < 8; i++) {
            assertTrue(vm.load(target, bytes32(i)) != bytes32(uint256(uint160(attacker))), "P_AUTH_WRITE");
        }
    }

    // P7_PROFIT [406 ops, 21,275 deployments] 0xfc102dffed8f5f30850a6fa59f7f4b8c94719c5e531bba1b7bac9df1869f6ccd
    function test_p7_c9_1(
        bytes4 s1, uint256 x1, bytes4 s2, uint256 x2, bytes4 s3, uint256 x3, address attacker
    ) public {
        vm.assume(attacker != address(0));
        address target = address(uint160(0x3000000 + 1));
        vm.etch(target, hex"608060405260043610610062576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff168063092a5cce146100cd57806354fd4d50146100e45780638da5cb5b1461010f578063b61d27f614610166575b600160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff166108fc349081150290604051600060405180830381858888f193505050501580156100ca573d6000803e3d6000fd5b50005b3480156100d957600080fd5b506100e26101df565b005b3480156100f057600080fd5b506100f9610278565b6040518082815260200191505060405180910390f35b34801561011b57600080fd5b5061012461027e565b604051808273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b34801561017257600080fd5b506101c9600480360381019080803573ffffffffffffffffffffffffffffffffffffffff169060200190929190803590602001909291908035906020019082018035906020019190919293919293905050506102a4565b6040518082815260200191505060405180910390f35b600160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff1614151561023b57610276565b600160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16ff5b565b60005481565b600160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b6000600160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff1614151561030257600080fd5b8473ffffffffffffffffffffffffffffffffffffffff168484846040518083838082843782019150509250505060006040518083038185875af192505050151561034b57600080fd5b600090509493505050505600a165627a7a72305820bf2b8f19a5800f4dc60201ea19dc69607dd04b7f94b73bbc7db87cd0d20369ec0029");
        vm.deal(target, 1 ether);
        for (uint256 i = 0; i < 8; i++) vm.store(target, bytes32(i), bytes32(0));
        uint256 bal0 = target.balance;
        uint256 atk0 = attacker.balance;
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(s1, x1));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(s2, x2));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(s3, x3));
        assertEq(target.balance, bal0, "P_TARGET_LOSS");
        assertLe(attacker.balance, atk0, "P_ATTACKER_PROFIT");
        for (uint256 i = 0; i < 8; i++) {
            assertTrue(vm.load(target, bytes32(i)) != bytes32(uint256(uint160(attacker))), "P_AUTH_WRITE");
        }
    }
}
