// SPDX-License-Identifier: UNLICENSED
// AUTO-GENERATED by gen_stage.py -- stage tracka_batch1, chunk 0 (CONTROLS-BATCH1)
pragma solidity ^0.8.13;

import {ProbeBase} from "../src/ProbeBase.sol";

contract Stagetracka_batch1Chunk_0 is ProbeBase {

    // MUST_FAIL a1_init VulnerableInit
    function test_a1_vulnerable(
        bytes4 selector, uint256 a0, uint256 a1, address attacker
    ) public {
        vm.assume(attacker != address(0));
        vm.assume(uint256(uint160(attacker)) > 0xff);
        vm.assume(attacker != address(0x7109709ECfa91a80626fF3989D68f67F5b1DD12D));
        vm.assume(attacker != address(0x000000000000000000636F6e736F6c652e6c6f67));
        address target = address(uint160(0x1000000 + 0));
        vm.assume(attacker != target);
        vm.etch(target, hex"608060405234801561000f575f80fd5b5060043610610034575f3560e01c80638da5cb5b14610038578063c4d66de814610056575b5f80fd5b610040610072565b60405161004d9190610116565b60405180910390f35b610070600480360381019061006b919061015d565b610095565b005b5f8054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b805f806101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555050565b5f73ffffffffffffffffffffffffffffffffffffffff82169050919050565b5f610100826100d7565b9050919050565b610110816100f6565b82525050565b5f6020820190506101295f830184610107565b92915050565b5f80fd5b61013c816100f6565b8114610146575f80fd5b50565b5f8135905061015781610133565b92915050565b5f602082840312156101725761017161012f565b5b5f61017f84828501610149565b9150509291505056fea26469706673582212208fe5b6ff82990cf1220b295d5d6489721797cc8598a0c3b3e7611a40f5036f5164736f6c63430008180033");
        vm.deal(target, 1 ether);
        _etchTokens();
        for (uint256 i = 0; i < 16; i++) vm.store(target, bytes32(i), bytes32(0));
        bytes32[16] memory before;
        for (uint256 i = 0; i < 16; i++) before[i] = vm.load(target, bytes32(i));
        uint256 bal0 = target.balance;
        uint256 atk0 = attacker.balance;
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selector, a0, a1));
        assertEq(target.balance, bal0, "P_BALANCE_LOST");
        assertLe(attacker.balance, atk0, "P_ATTACKER_PROFIT");
        for (uint256 i = 0; i < 16; i++) {
            bytes32 now = vm.load(target, bytes32(i));
            assertEq(uint256(now), uint256(before[i]), "P_STORAGE_CHANGED");
            assertTrue(now != bytes32(uint256(uint160(attacker))), "P_AUTH_WRITE");
        }
        _checkTokens(attacker);
    }

    // MUST_PASS a1_init SafeInit
    function test_a1_safe(
        bytes4 selector, uint256 a0, uint256 a1, address attacker
    ) public {
        vm.assume(attacker != address(0));
        vm.assume(uint256(uint160(attacker)) > 0xff);
        vm.assume(attacker != address(0x7109709ECfa91a80626fF3989D68f67F5b1DD12D));
        vm.assume(attacker != address(0x000000000000000000636F6e736F6c652e6c6f67));
        address target = address(uint160(0x1000000 + 0));
        vm.assume(attacker != target);
        vm.etch(target, hex"608060405234801561000f575f80fd5b5060043610610034575f3560e01c80638da5cb5b14610038578063c4d66de814610056575b5f80fd5b610040610072565b60405161004d9190610184565b60405180910390f35b610070600480360381019061006b91906101cb565b610095565b005b5f8054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b5f73ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff1614610103576040517f08c379a00000000000000000000000000000000000000000000000000000000081526004016100fa90610250565b60405180910390fd5b805f806101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555050565b5f73ffffffffffffffffffffffffffffffffffffffff82169050919050565b5f61016e82610145565b9050919050565b61017e81610164565b82525050565b5f6020820190506101975f830184610175565b92915050565b5f80fd5b6101aa81610164565b81146101b4575f80fd5b50565b5f813590506101c5816101a1565b92915050565b5f602082840312156101e0576101df61019d565b5b5f6101ed848285016101b7565b91505092915050565b5f82825260208201905092915050565b7f61757468000000000000000000000000000000000000000000000000000000005f82015250565b5f61023a6004836101f6565b915061024582610206565b602082019050919050565b5f6020820190508181035f8301526102678161022e565b905091905056fea2646970667358221220574ab5293bc52c1730b62bce5d58cd26a2a4af5b909885284f7f49abcde750ec64736f6c63430008180033");
        vm.deal(target, 1 ether);
        _etchTokens();
        for (uint256 i = 0; i < 16; i++) vm.store(target, bytes32(i), bytes32(0));
        bytes32[16] memory before;
        for (uint256 i = 0; i < 16; i++) before[i] = vm.load(target, bytes32(i));
        uint256 bal0 = target.balance;
        uint256 atk0 = attacker.balance;
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selector, a0, a1));
        assertEq(target.balance, bal0, "P_BALANCE_LOST");
        assertLe(attacker.balance, atk0, "P_ATTACKER_PROFIT");
        for (uint256 i = 0; i < 16; i++) {
            bytes32 now = vm.load(target, bytes32(i));
            assertEq(uint256(now), uint256(before[i]), "P_STORAGE_CHANGED");
            assertTrue(now != bytes32(uint256(uint160(attacker))), "P_AUTH_WRITE");
        }
        _checkTokens(attacker);
    }

    // MUST_FAIL a2_upgrade VulnerableUpgrade
    function test_a2_vulnerable(
        bytes4 selector, uint256 a0, uint256 a1, address attacker
    ) public {
        vm.assume(attacker != address(0));
        vm.assume(uint256(uint160(attacker)) > 0xff);
        vm.assume(attacker != address(0x7109709ECfa91a80626fF3989D68f67F5b1DD12D));
        vm.assume(attacker != address(0x000000000000000000636F6e736F6c652e6c6f67));
        address target = address(uint160(0x1000000 + 0));
        vm.assume(attacker != target);
        vm.etch(target, hex"608060405234801561000f575f80fd5b5060043610610034575f3560e01c80633659cfe6146100385780635c60da1b14610054575b5f80fd5b610052600480360381019061004d9190610135565b610072565b005b61005c6100b4565b604051610069919061016f565b60405180910390f35b805f806101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555050565b5f8054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b5f80fd5b5f73ffffffffffffffffffffffffffffffffffffffff82169050919050565b5f610104826100db565b9050919050565b610114816100fa565b811461011e575f80fd5b50565b5f8135905061012f8161010b565b92915050565b5f6020828403121561014a576101496100d7565b5b5f61015784828501610121565b91505092915050565b610169816100fa565b82525050565b5f6020820190506101825f830184610160565b9291505056fea2646970667358221220ad68f517f8c797f440b07c50e1bb6a4fac58ffd37d514fa326cf780410e1623f64736f6c63430008180033");
        vm.deal(target, 1 ether);
        _etchTokens();
        for (uint256 i = 0; i < 16; i++) vm.store(target, bytes32(i), bytes32(0));
        bytes32[16] memory before;
        for (uint256 i = 0; i < 16; i++) before[i] = vm.load(target, bytes32(i));
        uint256 bal0 = target.balance;
        uint256 atk0 = attacker.balance;
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selector, a0, a1));
        assertEq(target.balance, bal0, "P_BALANCE_LOST");
        assertLe(attacker.balance, atk0, "P_ATTACKER_PROFIT");
        for (uint256 i = 0; i < 16; i++) {
            bytes32 now = vm.load(target, bytes32(i));
            assertEq(uint256(now), uint256(before[i]), "P_STORAGE_CHANGED");
            assertTrue(now != bytes32(uint256(uint160(attacker))), "P_AUTH_WRITE");
        }
        _checkTokens(attacker);
    }

    // MUST_PASS a2_upgrade SafeUpgrade
    function test_a2_safe(
        bytes4 selector, uint256 a0, uint256 a1, address attacker
    ) public {
        vm.assume(attacker != address(0));
        vm.assume(uint256(uint160(attacker)) > 0xff);
        vm.assume(attacker != address(0x7109709ECfa91a80626fF3989D68f67F5b1DD12D));
        vm.assume(attacker != address(0x000000000000000000636F6e736F6c652e6c6f67));
        address target = address(uint160(0x1000000 + 0));
        vm.assume(attacker != target);
        vm.etch(target, hex"608060405234801561000f575f80fd5b5060043610610034575f3560e01c80633659cfe6146100385780635c60da1b14610054575b5f80fd5b610052600480360381019061004d91906101a3565b610072565b005b61005c610122565b60405161006991906101dd565b60405180910390f35b5f73ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff16146100e0576040517f08c379a00000000000000000000000000000000000000000000000000000000081526004016100d790610250565b60405180910390fd5b805f806101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555050565b5f8054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b5f80fd5b5f73ffffffffffffffffffffffffffffffffffffffff82169050919050565b5f61017282610149565b9050919050565b61018281610168565b811461018c575f80fd5b50565b5f8135905061019d81610179565b92915050565b5f602082840312156101b8576101b7610145565b5b5f6101c58482850161018f565b91505092915050565b6101d781610168565b82525050565b5f6020820190506101f05f8301846101ce565b92915050565b5f82825260208201905092915050565b7f61757468000000000000000000000000000000000000000000000000000000005f82015250565b5f61023a6004836101f6565b915061024582610206565b602082019050919050565b5f6020820190508181035f8301526102678161022e565b905091905056fea2646970667358221220fbf240c7ac3a43b2f7735ade73b5068c79a0e49c9d8c0be016458c035cc7d04e64736f6c63430008180033");
        vm.deal(target, 1 ether);
        _etchTokens();
        for (uint256 i = 0; i < 16; i++) vm.store(target, bytes32(i), bytes32(0));
        bytes32[16] memory before;
        for (uint256 i = 0; i < 16; i++) before[i] = vm.load(target, bytes32(i));
        uint256 bal0 = target.balance;
        uint256 atk0 = attacker.balance;
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selector, a0, a1));
        assertEq(target.balance, bal0, "P_BALANCE_LOST");
        assertLe(attacker.balance, atk0, "P_ATTACKER_PROFIT");
        for (uint256 i = 0; i < 16; i++) {
            bytes32 now = vm.load(target, bytes32(i));
            assertEq(uint256(now), uint256(before[i]), "P_STORAGE_CHANGED");
            assertTrue(now != bytes32(uint256(uint160(attacker))), "P_AUTH_WRITE");
        }
        _checkTokens(attacker);
    }

    // MUST_FAIL a6_fee VulnerableFee
    function test_a6_vulnerable(
        bytes4 selector, uint256 a0, uint256 a1, address attacker
    ) public {
        vm.assume(attacker != address(0));
        vm.assume(uint256(uint160(attacker)) > 0xff);
        vm.assume(attacker != address(0x7109709ECfa91a80626fF3989D68f67F5b1DD12D));
        vm.assume(attacker != address(0x000000000000000000636F6e736F6c652e6c6f67));
        address target = address(uint160(0x1000000 + 0));
        vm.assume(attacker != target);
        vm.etch(target, hex"608060405234801561000f575f80fd5b5060043610610034575f3560e01c806319f8dcf114610038578063fff6cae914610056575b5f80fd5b610040610060565b60405161004d9190610097565b60405180910390f35b61005e610065565b005b5f5481565b60015f8082825461007691906100dd565b92505081905550565b5f819050919050565b6100918161007f565b82525050565b5f6020820190506100aa5f830184610088565b92915050565b7f4e487b71000000000000000000000000000000000000000000000000000000005f52601160045260245ffd5b5f6100e78261007f565b91506100f28361007f565b925082820190508082111561010a576101096100b0565b5b9291505056fea26469706673582212205dfd68aa34dc3a8213136cffd5b0ea16463f99ef31da7aef69ddef2f505a7e7664736f6c63430008180033");
        vm.deal(target, 1 ether);
        _etchTokens();
        for (uint256 i = 0; i < 16; i++) vm.store(target, bytes32(i), bytes32(0));
        bytes32[16] memory before;
        for (uint256 i = 0; i < 16; i++) before[i] = vm.load(target, bytes32(i));
        uint256 bal0 = target.balance;
        uint256 atk0 = attacker.balance;
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selector, a0, a1));
        assertEq(target.balance, bal0, "P_BALANCE_LOST");
        assertLe(attacker.balance, atk0, "P_ATTACKER_PROFIT");
        for (uint256 i = 0; i < 16; i++) {
            bytes32 now = vm.load(target, bytes32(i));
            assertEq(uint256(now), uint256(before[i]), "P_STORAGE_CHANGED");
            assertTrue(now != bytes32(uint256(uint160(attacker))), "P_AUTH_WRITE");
        }
        _checkTokens(attacker);
    }

    // MUST_PASS a6_fee SafeFee
    function test_a6_safe(
        bytes4 selector, uint256 a0, uint256 a1, address attacker
    ) public {
        vm.assume(attacker != address(0));
        vm.assume(uint256(uint160(attacker)) > 0xff);
        vm.assume(attacker != address(0x7109709ECfa91a80626fF3989D68f67F5b1DD12D));
        vm.assume(attacker != address(0x000000000000000000636F6e736F6c652e6c6f67));
        address target = address(uint160(0x1000000 + 0));
        vm.assume(attacker != target);
        vm.etch(target, hex"608060405234801561000f575f80fd5b5060043610610034575f3560e01c806319f8dcf114610038578063fff6cae914610056575b5f80fd5b610040610060565b60405161004d9190610105565b60405180910390f35b61005e610065565b005b5f5481565b5f73ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff16146100d3576040517f08c379a00000000000000000000000000000000000000000000000000000000081526004016100ca90610178565b60405180910390fd5b60015f808282546100e491906101c3565b92505081905550565b5f819050919050565b6100ff816100ed565b82525050565b5f6020820190506101185f8301846100f6565b92915050565b5f82825260208201905092915050565b7f61757468000000000000000000000000000000000000000000000000000000005f82015250565b5f61016260048361011e565b915061016d8261012e565b602082019050919050565b5f6020820190508181035f83015261018f81610156565b9050919050565b7f4e487b71000000000000000000000000000000000000000000000000000000005f52601160045260245ffd5b5f6101cd826100ed565b91506101d8836100ed565b92508282019050808211156101f0576101ef610196565b5b9291505056fea2646970667358221220b69c894bb492bded0a01c4814c440e6501a6a39e98ad0d34d048e6175cb5759f64736f6c63430008180033");
        vm.deal(target, 1 ether);
        _etchTokens();
        for (uint256 i = 0; i < 16; i++) vm.store(target, bytes32(i), bytes32(0));
        bytes32[16] memory before;
        for (uint256 i = 0; i < 16; i++) before[i] = vm.load(target, bytes32(i));
        uint256 bal0 = target.balance;
        uint256 atk0 = attacker.balance;
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selector, a0, a1));
        assertEq(target.balance, bal0, "P_BALANCE_LOST");
        assertLe(attacker.balance, atk0, "P_ATTACKER_PROFIT");
        for (uint256 i = 0; i < 16; i++) {
            bytes32 now = vm.load(target, bytes32(i));
            assertEq(uint256(now), uint256(before[i]), "P_STORAGE_CHANGED");
            assertTrue(now != bytes32(uint256(uint160(attacker))), "P_AUTH_WRITE");
        }
        _checkTokens(attacker);
    }

    // MUST_FAIL a7_unchecked VulnerableUnchecked
    function test_a7_vulnerable(
        bytes4 selector, uint256 a0, uint256 a1, address attacker
    ) public {
        vm.assume(attacker != address(0));
        vm.assume(uint256(uint160(attacker)) > 0xff);
        vm.assume(attacker != address(0x7109709ECfa91a80626fF3989D68f67F5b1DD12D));
        vm.assume(attacker != address(0x000000000000000000636F6e736F6c652e6c6f67));
        address target = address(uint160(0x1000000 + 0));
        vm.assume(attacker != target);
        vm.etch(target, hex"608060405234801561000f575f80fd5b5060043610610034575f3560e01c806312aecce714610038578063c290d69114610056575b5f80fd5b610040610072565b60405161004d9190610101565b60405180910390f35b610070600480360381019061006b9190610148565b610077565b005b5f5481565b5f3373ffffffffffffffffffffffffffffffffffffffff168260405161009c906101a0565b5f6040518083038185875af1925050503d805f81146100d6576040519150601f19603f3d011682016040523d82523d5f602084013e6100db565b606091505b50509050815f819055505050565b5f819050919050565b6100fb816100e9565b82525050565b5f6020820190506101145f8301846100f2565b92915050565b5f80fd5b610127816100e9565b8114610131575f80fd5b50565b5f813590506101428161011e565b92915050565b5f6020828403121561015d5761015c61011a565b5b5f61016a84828501610134565b91505092915050565b5f81905092915050565b50565b5f61018b5f83610173565b91506101968261017d565b5f82019050919050565b5f6101aa82610180565b915081905091905056fea2646970667358221220b171381c6c31c831677900ae7e43cb27468fcfcd95dd8ccf55a461aa0003689d64736f6c63430008180033");
        vm.deal(target, 1 ether);
        _etchTokens();
        for (uint256 i = 0; i < 16; i++) vm.store(target, bytes32(i), bytes32(0));
        bytes32[16] memory before;
        for (uint256 i = 0; i < 16; i++) before[i] = vm.load(target, bytes32(i));
        uint256 bal0 = target.balance;
        uint256 atk0 = attacker.balance;
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selector, a0, a1));
        assertEq(target.balance, bal0, "P_BALANCE_LOST");
        assertLe(attacker.balance, atk0, "P_ATTACKER_PROFIT");
        for (uint256 i = 0; i < 16; i++) {
            bytes32 now = vm.load(target, bytes32(i));
            assertEq(uint256(now), uint256(before[i]), "P_STORAGE_CHANGED");
            assertTrue(now != bytes32(uint256(uint160(attacker))), "P_AUTH_WRITE");
        }
        _checkTokens(attacker);
    }

    // MUST_PASS a7_unchecked SafeUnchecked
    function test_a7_safe(
        bytes4 selector, uint256 a0, uint256 a1, address attacker
    ) public {
        vm.assume(attacker != address(0));
        vm.assume(uint256(uint160(attacker)) > 0xff);
        vm.assume(attacker != address(0x7109709ECfa91a80626fF3989D68f67F5b1DD12D));
        vm.assume(attacker != address(0x000000000000000000636F6e736F6c652e6c6f67));
        address target = address(uint160(0x1000000 + 0));
        vm.assume(attacker != target);
        vm.etch(target, hex"608060405234801561000f575f80fd5b5060043610610034575f3560e01c806312aecce714610038578063c290d69114610056575b5f80fd5b610040610072565b60405161004d9190610106565b60405180910390f35b610070600480360381019061006b919061014d565b610077565b005b5f5481565b5f73ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff16146100e5576040517f08c379a00000000000000000000000000000000000000000000000000000000081526004016100dc906101d2565b60405180910390fd5b805f8190555050565b5f819050919050565b610100816100ee565b82525050565b5f6020820190506101195f8301846100f7565b92915050565b5f80fd5b61012c816100ee565b8114610136575f80fd5b50565b5f8135905061014781610123565b92915050565b5f602082840312156101625761016161011f565b5b5f61016f84828501610139565b91505092915050565b5f82825260208201905092915050565b7f61757468000000000000000000000000000000000000000000000000000000005f82015250565b5f6101bc600483610178565b91506101c782610188565b602082019050919050565b5f6020820190508181035f8301526101e9816101b0565b905091905056fea264697066735822122052c7aabcc8be486d63df27e5eb01f3309ea1a3023f59347272927ed5efb37e8e64736f6c63430008180033");
        vm.deal(target, 1 ether);
        _etchTokens();
        for (uint256 i = 0; i < 16; i++) vm.store(target, bytes32(i), bytes32(0));
        bytes32[16] memory before;
        for (uint256 i = 0; i < 16; i++) before[i] = vm.load(target, bytes32(i));
        uint256 bal0 = target.balance;
        uint256 atk0 = attacker.balance;
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selector, a0, a1));
        assertEq(target.balance, bal0, "P_BALANCE_LOST");
        assertLe(attacker.balance, atk0, "P_ATTACKER_PROFIT");
        for (uint256 i = 0; i < 16; i++) {
            bytes32 now = vm.load(target, bytes32(i));
            assertEq(uint256(now), uint256(before[i]), "P_STORAGE_CHANGED");
            assertTrue(now != bytes32(uint256(uint160(attacker))), "P_AUTH_WRITE");
        }
        _checkTokens(attacker);
    }
}
