#!/usr/bin/env python3
"""Track A generator (v3) — ProbeBaseA probes with selector hints + model choice.

Emits, per class, the CI matrix layout:

    harness/stages/stage<stage>/Stage<stage>Chunk_<n>.sol
    harness/stages/stage<stage>/chunk_<n>.tests
    harness/stages/stage<stage>/manifest.json

Chunk 0 is ALWAYS the class's two controls (MUST_FAIL / MUST_PASS) and needs no
bytecode DB. Target chunks embed runtime bytecode from the CI/HF-built DuckDB
(`bytecodes`) or a compact `tracka_bytecodes.parquet`.

Two levers over v2:
  * `--selector-hint` (default on): constrain the symbolic `bytes4 selector` to
    the target's real dispatcher entries (`disp_sel` from the scanner). This
    removes the 2^32 selector branching that made every safe proof cost ~1 h.
  * `--models zeroed|symbolic|both` (default `zeroed`): the symbolic-storage
    model OOMs on 16 GB runners, so mass sweeps use `zeroed`; use `both` on a
    big-memory HF job when you want the extra soundness.

Classes (sweepable set; A3/A4/A8 are Track B): a1 a2 a6 a7 (SINGLE),
a9 (PULL), a5 (VALUE).
"""
import argparse
import json
import os
import string
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
CTRL = os.path.join(ROOT, "harness", "controls")
OUTROOT = os.path.join(ROOT, "harness", "stages")

CLASSES = {
    "a1": ("a1_init", "SINGLE", ("VulnerableInit", "SafeInit")),
    "a2": ("a2_upgrade", "SINGLE", ("VulnerableUpgrade", "SafeUpgrade")),
    "a6": ("a6_fee", "SINGLE", ("VulnerableFee", "SafeFee")),
    "a7": ("a7_unchecked", "SINGLE", ("VulnerableUnchecked", "SafeUnchecked")),
    "a9": ("a9_unauth_pull", "PULL", ("VulnerablePull", "SafePull")),
    "a5": ("a5_multicall", "VALUE", ("VulnerableValue", "SafeValue")),
}
ORDER = ["a1", "a2", "a5", "a6", "a7", "a9"]
BASE = {"a1": 0x1000000, "a2": 0x1100000, "a6": 0x1600000, "a7": 0x1700000,
        "a9": 0x1900000, "a5": 0x1500000}
SEL_CAP = 128

T = string.Template

HDR = T("""// SPDX-License-Identifier: UNLICENSED
// AUTO-GENERATED by gen_track_a.py -- stage $stage, chunk $chunk ($cls)
pragma solidity ^0.8.13;

import {ProbeBaseA} from "../src/ProbeBaseA.sol";

contract Stage${stage}Chunk_$chunk is ProbeBaseA {
$body
""")

SINGLE_BODY = T("""
    function _probeSingle(
        bytes memory code, uint256 idx, bytes4 selector,
        uint256 a0, uint256 a1, address attacker, bool zeroed
    ) internal {
        address target = address(uint160(0x${base} + idx));
        _assumeAttacker(attacker, target);
        vm.etch(target, code);
        vm.deal(target, 1 ether);
        if (zeroed) { _seedZeroed(target); } else { _seedSymbolic(target); }
        _snapshotTarget(target);
        _snapshotTokens();
        _markBalances(target, attacker);
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selector, a0, a1));
        _checkTarget(target, attacker, zeroed);
    }
$probes}
""")

PULL_BODY = T("""
    address internal constant VICTIM = 0x0000000000000000000000000000000000002222;

    function _probePull(
        bytes memory code, uint256 idx, bytes4 selector, uint256 amt, address attacker
    ) internal {
        address target = address(uint160(0x${base} + idx));
        _assumeAttackerVictim(attacker, target, VICTIM);
        vm.etch(target, code);
        vm.deal(target, 1 ether);
        _seedVictim(VICTIM, target, 1_000 ether, 1_000 ether);
        _snapshotTokens();
        vm.assume(amt <= 1_000 ether);
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selector, VICTIM, amt));
        _checkVictim(VICTIM);
    }
$probes}
""")

VALUE_BODY = T("""
    function _probeValue(
        bytes memory code, uint256 idx, bytes4 selector,
        uint256 a0, uint256 a1, address attacker
    ) internal {
        address target = address(uint160(0x${base} + idx));
        _assumeAttacker(attacker, target);
        vm.etch(target, code);
        vm.deal(target, 2 ether);
        _seedZeroed(target);
        vm.assume(a0 > 0);
        vm.assume(a0 <= 1 ether);
        vm.deal(attacker, a0);
        _markBalances(target, attacker);
        vm.prank(attacker);
        target.call{value: a0}(abi.encodeWithSelector(selector, a0, a1));
        _checkValue(target, attacker);
    }
$probes}
""")

CODE = T("""    function _code_$i() internal pure returns (bytes memory) { return hex"$code"; }""")

SEL = T("""    function _sels_${chunk}_${i}(bytes4 selector) internal pure returns (bool) {
        return $conds;
    }""")

SINGLE_TEST = T("""    function test_${cls}_c${chunk}_${i}$suffix(
        bytes4 selector, uint256 a0, uint256 a1, address attacker
    ) public {
$guard        _probeSingle(_code_$i(), $i, selector, a0, a1, attacker, $zeroed);
    }""")

PULL_TEST = T("""    function test_${cls}_c${chunk}_${i}(
        bytes4 selector, uint256 amt, address attacker
    ) public {
$guard        _probePull(_code_$i(), $i, selector, amt, attacker);
    }""")

VALUE_TEST = T("""    function test_${cls}_c${chunk}_${i}(
        bytes4 selector, uint256 a0, uint256 a1, address attacker
    ) public {
$guard        _probeValue(_code_$i(), $i, selector, a0, a1, attacker);
    }""")

BODIES = {"SINGLE": SINGLE_BODY, "PULL": PULL_BODY, "VALUE": VALUE_BODY}


def control_code(name):
    with open(os.path.join(CTRL, name + ".hex")) as fh:
        c = fh.read().strip()
    return c[2:] if c.startswith("0x") else c


def parse_sels(disp):
    """`disp_sel` is a space-separated list of 8-hex selectors from the scanner."""
    if not disp:
        return []
    toks = str(disp).replace(",", " ").split()
    out = [t for t in toks if len(t) == 8]
    return out[:SEL_CAP]


def sel_helpers(chunk, i, sels, enabled):
    """(helper_src, guard_src) for the per-target selector constraint."""
    if not (enabled and sels):
        return "", ""
    conds = " || ".join(f'selector == hex"{s}"' for s in sels)
    return SEL.substitute(chunk=chunk, i=i, conds=conds) + "\n", \
        f"        vm.assume(_sels_{chunk}_{i}(selector));\n"


def emit_probes(cls, chunk, items, base, models, selector_hint):
    """items: list of dicts {i, code, label, sels}. Returns (body, tests)."""
    template = CLASSES[cls][1]
    probes, tests = [], []
    for it in items:
        i = it["i"]
        block = "    // " + it["label"] + "\n"
        helper, guard = sel_helpers(chunk, i, it.get("sels", []), selector_hint) \
            if template == "SINGLE" else ("", "")
        block += CODE.substitute(i=i, code=it["code"]) + "\n\n"
        if helper:
            block += helper + "\n"
        if template == "SINGLE":
            for m in models:
                zeroed = "true" if m == "zeroed" else "false"
                suffix = "_z" if m == "zeroed" else "_s"
                block += SINGLE_TEST.substitute(cls=cls, chunk=chunk, i=i, suffix=suffix,
                                                guard=guard, zeroed=zeroed) + "\n\n"
                tests.append(f"test_{cls}_c{chunk}_{i}{suffix}")
        elif template == "PULL":
            block += PULL_TEST.substitute(cls=cls, chunk=chunk, i=i, guard=guard) + "\n\n"
            tests.append(f"test_{cls}_c{chunk}_{i}")
        else:
            block += VALUE_TEST.substitute(cls=cls, chunk=chunk, i=i, guard=guard) + "\n\n"
            tests.append(f"test_{cls}_c{chunk}_{i}")
        probes.append(block)
    body = BODIES[template].substitute(base=f"{base:x}", probes="".join(probes))
    return body, tests


def chunk_targets(items):
    out, small, mid = [], [], []
    for it in items:
        ops = it["n_ops"]
        if ops > 1500:
            if small:
                out.append(small); small = []
            if mid:
                out.append(mid); mid = []
            out.append([it])
        elif ops > 600:
            mid.append(it)
            if len(mid) == 2:
                out.append(mid); mid = []
        else:
            small.append(it)
            if len(small) == 2:
                out.append(small); small = []
    if mid:
        out.append(mid)
    if small:
        out.append(small)
    return out


def load_targets(args, scanner):
    """Preferred source is the full-match parquet (`<scanner>.parquet`); the JSON
    is the deployment-ranked sample."""
    if args.targets_parquet:
        import duckdb
        con = duckdb.connect(":memory:")
        rows = con.execute(
            "SELECT bytecode_hash, n_ops, code_size_eff, deploys, disp_sel "
            "FROM read_parquet(?) ORDER BY deploys DESC", [args.targets_parquet]
        ).fetchall()
        con.close()
        items = [{"hash": h, "n_ops": int(o), "code_size_eff": int(s),
                  "deploys": int(d), "disp_sel": ds} for h, o, s, d, ds in rows]
    else:
        path = args.targets or os.path.join(ROOT, "data", "stages", scanner + "_targets.json")
        man = json.load(open(path))
        items = [{"hash": t["hash"], "n_ops": t.get("n_ops", 0),
                  "code_size_eff": t.get("code_size_eff", 0),
                  "deploys": t.get("deploys", 0),
                  "disp_sel": t.get("disp_sel", "")} for t in man.get("targets", [])]
    if args.limit and args.limit > 0:
        items = items[: args.limit]
    return items


def bytecode_source(args):
    if not args.controls_only and not (args.db or args.bytecodes_parquet):
        raise SystemExit("target generation needs --db or --bytecodes-parquet")
    import duckdb
    con = duckdb.connect(":memory:")
    con.execute("SET threads=4")
    if args.db:
        con.execute(f"ATTACH '{args.db}' AS eth (READ_ONLY)")
        view = "eth.bytecodes"
    else:
        view = f"read_parquet('{args.bytecodes_parquet}')"
    con.execute(f"CREATE VIEW bytecodes_v AS SELECT bytecode_hash, bytecode FROM {view}")

    def fetch(h):
        row = con.execute("SELECT bytecode FROM bytecodes_v WHERE bytecode_hash = ?", [h]).fetchone()
        if row is None:
            return None
        code = row[0]
        if isinstance(code, (bytes, bytearray)):
            code = bytes(code).hex()
        else:
            code = str(code).strip()
            if code.startswith("\\x"):
                code = code[2:]
            if code.startswith("0x"):
                code = code[2:]
        return code

    return fetch


def write_stage(stage, chunks, outroot=None):
    outdir = os.path.join(outroot or OUTROOT, "stage" + stage)
    os.makedirs(outdir, exist_ok=True)
    for f in os.listdir(outdir):
        if f.startswith("Stage") or f.startswith("chunk_") or f == "manifest.json":
            os.remove(os.path.join(outdir, f))
    manifest = {"stage": stage, "chunks": []}
    for ci, body, tests, cls, targets in chunks:
        src = HDR.substitute(stage=stage, chunk=ci, cls=cls, body=body)
        with open(os.path.join(outdir, f"Stage{stage}Chunk_{ci}.sol"), "w") as fh:
            fh.write(src)
        with open(os.path.join(outdir, f"chunk_{ci}.tests"), "w") as fh:
            fh.write("\n".join(tests) + "\n")
        manifest["chunks"].append({"chunk": ci, "class": cls, "tests": tests, "targets": targets})
        print(f"  wrote Stage{stage}Chunk_{ci}.sol ({len(targets)} targets, {len(tests)} tests)",
              flush=True)
    with open(os.path.join(outdir, "manifest.json"), "w") as fh:
        json.dump(manifest, fh, indent=1)
    print(f"[{stage}] {len(chunks)} chunks", flush=True)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--class", dest="cls", required=True, choices=ORDER)
    ap.add_argument("--controls-only", action="store_true")
    ap.add_argument("--targets", default=None)
    ap.add_argument("--targets-parquet", default=None)
    ap.add_argument("--db", default=None)
    ap.add_argument("--bytecodes-parquet", default=None)
    ap.add_argument("--limit", type=int, default=0)
    ap.add_argument("--stage", default=None)
    ap.add_argument("--out", default=None)
    ap.add_argument("--models", default="zeroed",
                    help="zeroed | symbolic | both (SINGLE classes)")
    ap.add_argument("--no-selector-hint", dest="selector_hint",
                    action="store_false", help="leave bytes4 selector fully symbolic")
    args = ap.parse_args()

    models = {"zeroed": ["zeroed"], "symbolic": ["symbolic"],
              "both": ["zeroed", "symbolic"]}[args.models]
    cls = args.cls
    scanner, template, (vuln, safe) = CLASSES[cls]
    stage = args.stage or f"tracka_{cls}"
    base = BASE[cls]

    chunks = []
    items = []
    for i, (kind, cname) in enumerate((("MUST_FAIL", vuln), ("MUST_PASS", safe))):
        items.append({"i": i, "code": control_code(cname),
                      "label": f"{kind} {cname}", "sels": []})
    body, tests = emit_probes(cls, 0, items, base, models, False)
    chunks.append((0, body, tests, "CONTROLS", []))

    if not args.controls_only:
        targets = load_targets(args, scanner)
        if not targets:
            raise SystemExit(f"no targets for {scanner}")
        fetch = bytecode_source(args)
        missing = 0
        for gi, group in enumerate(chunk_targets(targets), start=1):
            probe_items, meta = [], []
            for i, t in enumerate(group):
                code = fetch(t["hash"])
                if not code:
                    missing += 1
                    continue
                probe_items.append({"i": i, "code": code, "sels": parse_sels(t.get("disp_sel")),
                                    "label": f"{scanner} [{t['n_ops']} ops, {t['deploys']:,} deploys] {t['hash']}"})
                meta.append({"hash": t["hash"], "n_ops": t["n_ops"],
                             "deploys": t["deploys"], "idx": i})
            if not probe_items:
                continue
            body, tests = emit_probes(cls, gi, probe_items, base, models, args.selector_hint)
            chunks.append((gi, body, tests, scanner, meta))
        print(f"[{stage}] targets={len(targets)} chunks={len(chunks)-1} "
              f"missing={missing} models={args.models} sel_hint={args.selector_hint}", flush=True)

    write_stage(stage, chunks, args.out)


if __name__ == "__main__":
    main()
