#!/usr/bin/env python3
"""Track A generator (v2) — ProbeBaseA probes for the sweepable classes.

Emits, per class, the CI matrix layout:

    harness/stages/tracka_<class>/Stage<stage>Chunk_<n>.sol
    harness/stages/tracka_<class>/chunk_<n>.tests
    harness/stages/tracka_<class>/manifest.json

Chunk 0 is ALWAYS the class's two v2 controls (MUST_FAIL / MUST_PASS) and needs
no bytecode DB — this is the `mode: sanity` gate. Target chunks embed the real
runtime bytecode fetched from the CI-built DuckDB (`bytecodes` table) or a
`bytecodes_sel.parquet`; therefore target generation runs in CI, never locally.

Classes (Track A sweepable set; A3/A4/A8 are Track B):
  a1  a1_init        SINGLE  (zeroed + symbolic models)
  a2  a2_upgrade     SINGLE  (zeroed + symbolic models)
  a6  a6_fee         SINGLE  (zeroed + symbolic models)
  a7  a7_unchecked   SINGLE  (zeroed + symbolic models)
  a9  a9_unauth_pull PULL    (ConsentToken victim + fixed-slot observation)
  a5  a5_multicall   VALUE   (msg.value conservation)

Design invariants (no FP / no FN) live in `src/ProbeBaseA.sol` and `CA/kontrol`:
  * attacker assumptions centralised (`vm.assume`, never `bound`);
  * `P_AUTH_WRITE` only under the zeroed model; `P_STORAGE_CHANGED` in both;
  * keccak-free token observation via ConsentToken fixed slots.
"""
import argparse
import json
import os
import string
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
CTRL = os.path.join(ROOT, "harness", "controls")
OUTROOT = os.path.join(ROOT, "harness", "stages")

# class -> scanner id, template, (MUST_FAIL control, MUST_PASS control)
CLASSES = {
    "a1": ("a1_init", "SINGLE", ("VulnerableInit", "SafeInit")),
    "a2": ("a2_upgrade", "SINGLE", ("VulnerableUpgrade", "SafeUpgrade")),
    "a6": ("a6_fee", "SINGLE", ("VulnerableFee", "SafeFee")),
    "a7": ("a7_unchecked", "SINGLE", ("VulnerableUnchecked", "SafeUnchecked")),
    "a9": ("a9_unauth_pull", "PULL", ("VulnerablePull", "SafePull")),
    "a5": ("a5_multicall", "VALUE", ("VulnerableValue", "SafeValue")),
}
ORDER = ["a1", "a2", "a5", "a6", "a7", "a9"]

T = string.Template

HDR = T("""// SPDX-License-Identifier: UNLICENSED
// AUTO-GENERATED by gen_track_a.py -- stage $stage, chunk $chunk ($cls)
pragma solidity ^0.8.13;

import {ProbeBaseA} from "../src/ProbeBaseA.sol";

contract Stage${stage}Chunk_$chunk is ProbeBaseA {
$body
""")

SINGLE_BODY = T("""
    function _probeSingle(
        bytes memory code, uint256 idx, bytes4 selector,
        uint256 a0, uint256 a1, address attacker, bool zeroed
    ) internal {
        address target = address(uint160(0x${base} + idx));
        _assumeAttacker(attacker, target);
        vm.etch(target, code);
        vm.deal(target, 1 ether);
        if (zeroed) { _seedZeroed(target); } else { _seedSymbolic(target); }
        _snapshotTarget(target);
        _snapshotTokens();
        _markBalances(target, attacker);
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selector, a0, a1));
        _checkTarget(target, attacker, zeroed);
    }
$probes}
""")

SINGLE_PROBE = T("""
    function _code_$i() internal pure returns (bytes memory) { return hex"$code"; }

    // $label
    function test_${cls}_c${chunk}_${i}_z(
        bytes4 selector, uint256 a0, uint256 a1, address attacker
    ) public {
        _probeSingle(_code_$i(), $i, selector, a0, a1, attacker, true);
    }

    function test_${cls}_c${chunk}_${i}_s(
        bytes4 selector, uint256 a0, uint256 a1, address attacker
    ) public {
        _probeSingle(_code_$i(), $i, selector, a0, a1, attacker, false);
    }
""")

PULL_BODY = T("""
    address internal constant VICTIM = 0x0000000000000000000000000000000000002222;

    function _probePull(
        bytes memory code, uint256 idx, bytes4 selector, uint256 amt, address attacker
    ) internal {
        address target = address(uint160(0x${base} + idx));
        _assumeAttackerVictim(attacker, target, VICTIM);
        vm.etch(target, code);
        vm.deal(target, 1 ether);
        _seedVictim(VICTIM, target, 1_000 ether, 1_000 ether);
        _snapshotTokens();
        vm.assume(amt <= 1_000 ether);
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selector, VICTIM, amt));
        _checkVictim(VICTIM);
    }
$probes}
""")

PULL_PROBE = T("""
    function _code_$i() internal pure returns (bytes memory) { return hex"$code"; }

    // $label
    function test_${cls}_c${chunk}_${i}(
        bytes4 selector, uint256 amt, address attacker
    ) public {
        _probePull(_code_$i(), $i, selector, amt, attacker);
    }
""")

VALUE_BODY = T("""
    function _probeValue(
        bytes memory code, uint256 idx, bytes4 selector,
        uint256 a0, uint256 a1, address attacker
    ) internal {
        address target = address(uint160(0x${base} + idx));
        _assumeAttacker(attacker, target);
        vm.etch(target, code);
        vm.deal(target, 2 ether);
        _seedZeroed(target);
        vm.assume(a0 > 0);
        vm.assume(a0 <= 1 ether);
        vm.deal(attacker, a0);
        _markBalances(target, attacker);
        vm.prank(attacker);
        target.call{value: a0}(abi.encodeWithSelector(selector, a0, a1));
        _checkValue(target, attacker);
    }
$probes}
""")

VALUE_PROBE = T("""
    function _code_$i() internal pure returns (bytes memory) { return hex"$code"; }

    // $label
    function test_${cls}_c${chunk}_${i}(
        bytes4 selector, uint256 a0, uint256 a1, address attacker
    ) public {
        _probeValue(_code_$i(), $i, selector, a0, a1, attacker);
    }
""")

TEMPLATES = {
    "SINGLE": (SINGLE_BODY, SINGLE_PROBE),
    "PULL": (PULL_BODY, PULL_PROBE),
    "VALUE": (VALUE_BODY, VALUE_PROBE),
}
BASE = {"a1": 0x1000000, "a2": 0x1100000, "a6": 0x1600000, "a7": 0x1700000,
        "a9": 0x1900000, "a5": 0x1500000}


def control_code(name):
    with open(os.path.join(CTRL, name + ".hex")) as fh:
        c = fh.read().strip()
    return c[2:] if c.startswith("0x") else c


def _tests_for(cls, chunk, idx, template):
    stem = f"test_{cls}_c{chunk}_{idx}"
    return [stem + "_z", stem + "_s"] if template == "SINGLE" else [stem]


def emit_probes(cls, chunk, items, base):
    """items: list of (i, code_hex, label). Returns (body, tests)."""
    _, template = CLASSES[cls][1], CLASSES[cls][1]
    body_t, probe_t = TEMPLATES[template]
    probes, tests = [], []
    for i, code, label in items:
        probes.append(probe_t.substitute(cls=cls, chunk=chunk, i=i, code=code, label=label))
        tests.extend(_tests_for(cls, chunk, i, template))
    body = body_t.substitute(base=f"{base:x}", probes="".join(probes))
    return body, tests


def chunk_targets(items):
    """Partition by opcode count so a chunk job stays within the CI budget.
    Large bytecodes get their own chunk; small ones batch (a SINGLE item emits
    2 tests, so a small batch of 2 => 4 proofs)."""
    out, small, mid = [], [], []
    for it in items:
        ops = it["n_ops"]
        if ops > 1500:
            if small:
                out.append(small); small = []
            if mid:
                out.append(mid); mid = []
            out.append([it])
        elif ops > 600:
            mid.append(it)
            if len(mid) == 2:
                out.append(mid); mid = []
        else:
            small.append(it)
            if len(small) == 2:
                out.append(small); small = []
    if mid:
        out.append(mid)
    if small:
        out.append(small)
    return out


def load_targets(args, scanner):
    """Return list of {hash, n_ops, code_size_eff, deploys}. Preferred source is
    the full-match parquet the scanner writes (`data/stages/<scanner>.parquet`);
    the JSON is the top-40 sample (useful for a quick local check)."""
    if args.targets_parquet:
        import duckdb
        con = duckdb.connect(":memory:")
        rows = con.execute(
            "SELECT bytecode_hash, n_ops, code_size_eff, deploys "
            "FROM read_parquet(?) ORDER BY deploys DESC", [args.targets_parquet]
        ).fetchall()
        con.close()
        items = [{"hash": h, "n_ops": int(o), "code_size_eff": int(s), "deploys": int(d)}
                 for h, o, s, d in rows]
    else:
        path = args.targets or os.path.join(ROOT, "data", "stages", scanner + "_targets.json")
        man = json.load(open(path))
        items = [{"hash": t["hash"], "n_ops": t.get("n_ops", 0),
                  "code_size_eff": t.get("code_size_eff", 0), "deploys": t.get("deploys", 0)}
                 for t in man.get("targets", [])]
    if args.limit and args.limit > 0:
        items = items[: args.limit]
    return items


def bytecode_source(args):
    """Return a callable hash -> hex string. Uses the DuckDB `bytecodes` table if
    --db is given, else a bytecodes parquet/csv. Raises if neither is available."""
    if not args.controls_only and not (args.db or args.bytecodes_parquet):
        raise SystemExit("target generation needs --db or --bytecodes-parquet "
                         "(run in CI where the DuckDB is built)")
    import duckdb
    con = duckdb.connect(":memory:")
    con.execute("SET threads=4")
    if args.db:
        con.execute(f"ATTACH '{args.db}' AS eth (READ_ONLY)")
        view = "eth.bytecodes"
    else:
        view = f"read_parquet('{args.bytecodes_parquet}')"
    con.execute(f"CREATE VIEW bytecodes_v AS SELECT bytecode_hash, bytecode FROM {view}")

    def fetch(h):
        row = con.execute("SELECT bytecode FROM bytecodes_v WHERE bytecode_hash = ?", [h]).fetchone()
        if row is None:
            return None
        code = row[0]
        if isinstance(code, (bytes, bytearray)):
            code = bytes(code).hex()
        else:
            code = str(code).strip()
            if code.startswith("\\x"):
                code = code[2:]
            if code.startswith("0x"):
                code = code[2:]
        return code

    return fetch


def write_stage(stage, chunks):
    """chunks: list of (chunk_index, body, tests, class_label, targets).

    Output dir follows the CI convention: `harness/stages/stage<stage>/` with
    files `Stage<stage>Chunk_<n>.sol` (so `stage: tracka_a1` -> `stagetracka_a1/`).
    """
    outdir = os.path.join(OUTROOT, "stage" + stage)
    os.makedirs(outdir, exist_ok=True)
    for f in os.listdir(outdir):
        if f.startswith("Stage") or f.startswith("chunk_") or f == "manifest.json":
            os.remove(os.path.join(outdir, f))
    manifest = {"stage": stage, "chunks": []}
    for ci, body, tests, cls, targets in chunks:
        src = HDR.substitute(stage=stage, chunk=ci, cls=cls, body=body)
        with open(os.path.join(outdir, f"Stage{stage}Chunk_{ci}.sol"), "w") as fh:
            fh.write(src)
        with open(os.path.join(outdir, f"chunk_{ci}.tests"), "w") as fh:
            fh.write("\n".join(tests) + "\n")
        manifest["chunks"].append({"chunk": ci, "class": cls, "tests": tests, "targets": targets})
        print(f"  wrote Stage{stage}Chunk_{ci}.sol ({len(targets)} targets, {len(tests)} tests)",
              flush=True)
    with open(os.path.join(outdir, "manifest.json"), "w") as fh:
        json.dump(manifest, fh, indent=1)
    print(f"[{stage}] {len(chunks)} chunks", flush=True)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--class", dest="cls", required=True, choices=ORDER,
                    help="Track A class slug (a1,a2,a5,a6,a7,a9)")
    ap.add_argument("--controls-only", action="store_true",
                    help="emit chunk 0 (controls) only; no bytecode DB needed")
    ap.add_argument("--targets", default=None, help="targets JSON (top-N sample)")
    ap.add_argument("--targets-parquet", default=None, help="full-match parquet from the scanner")
    ap.add_argument("--db", default=None, help="DuckDB with a `bytecodes` table (CI)")
    ap.add_argument("--bytecodes-parquet", default=None)
    ap.add_argument("--limit", type=int, default=0, help="cap targets (0 = all)")
    ap.add_argument("--stage", default=None, help="override stage id (default tracka_<cls>)")
    args = ap.parse_args()

    cls = args.cls
    scanner, template, (vuln, safe) = CLASSES[cls]
    stage = args.stage or f"tracka_{cls}"
    base = BASE[cls]

    chunks = []

    # ---- chunk 0: controls (always) ----
    items = []
    for i, (kind, cname) in enumerate((("MUST_FAIL", vuln), ("MUST_PASS", safe))):
        items.append((i, control_code(cname), f"{kind} {cname}"))
    body, tests = emit_probes(cls, 0, items, base)
    chunks.append((0, body, tests, "CONTROLS", []))

    if not args.controls_only:
        targets = load_targets(args, scanner)
        if not targets:
            raise SystemExit(f"no targets for {scanner}")
        fetch = bytecode_source(args)
        groups = chunk_targets(targets)
        missing = 0
        for gi, group in enumerate(groups, start=1):
            probe_items, meta = [], []
            for i, t in enumerate(group):
                code = fetch(t["hash"])
                if not code:
                    missing += 1
                    continue
                label = (f"{scanner} [{t['n_ops']} ops, {t['deploys']:,} deploys] {t['hash']}")
                probe_items.append((i, code, label))
                meta.append({"hash": t["hash"], "n_ops": t["n_ops"],
                             "deploys": t["deploys"], "idx": i})
            if not probe_items:
                continue
            body, tests = emit_probes(cls, gi, probe_items, base)
            chunks.append((gi, body, tests, scanner, meta))
        print(f"[{stage}] targets={len(targets)} chunks={len(chunks)-1} missing_bytecode={missing}",
              flush=True)

    write_stage(stage, chunks)


if __name__ == "__main__":
    main()
