#!/usr/bin/env python3
"""Generate Kontrol symbolic probe tests from the opcode radar.

Emits /tmp/harness/probe/test/ProbeBatch1.sol containing:
  - 2 ground-truth controls (VulnerableControl -> must FAIL proofs,
    SafeControl -> must PASS) — validates the probe itself
  - N candidate bytecodes pulled from the radar signals in DuckDB

Properties per probe (single symbolic call from an arbitrary attacker):
  P2-SELFDESTRUCT: target ETH balance must remain untouched
  P1-HIJACK:       storage slots 0..7 must never come to hold the attacker's address
"""
import sys
import duckdb

DB = "/tmp/eth-contracts/eth_contracts.duckdb"
OUT = "/tmp/harness/probe/test/ProbeBatch1.sol"
CONTROLS = {
    "vulnerable_control": "/tmp/harness/VulnerableControl.hex",
    "safe_control": "/tmp/harness/SafeControl.hex",
}

CANDIDATE_QUERIES = {
    # (label, sql returning (hash, note))
    "sstore_no_caller_delegate": """
        SELECT o.bytecode_hash, o.n_ops
        FROM opcode_features o WHERE o.sig_sstore_no_caller AND o.sig_delegate
        ORDER BY o.n_ops ASC LIMIT 3""",
    "selfdestruct_delegate": """
        SELECT o.bytecode_hash, o.n_ops
        FROM opcode_features o WHERE o.sig_selfdestruct AND o.sig_delegate
        ORDER BY o.n_ops ASC LIMIT 2""",
    "transient_caller_small": """
        SELECT o.bytecode_hash, o.n_ops
        FROM opcode_features o WHERE o.sig_transient_caller AND o.n_ops <= 200
        ORDER BY o.n_ops ASC LIMIT 2""",
    "transient_top_template": """
        SELECT bytecode_hash, n_ops FROM opcode_features
        WHERE bytecode_hash = '0x07be01e7e7206fe31ecee91ad75dada65ad6ba433ae647a1b9330469f7c6677c'""",
}

TEMPLATE = """
    // {label}: {hash} ({ops} ops)
    function test_probe_{fname}(
        bytes4 selector, uint256 a0, uint256 a1, address attacker
    ) public {{
        vm.assume(attacker != address(0));
        address target = address(uint160(0x1000000 + {idx}));
        vm.etch(target, {code});
        vm.deal(target, 1 ether);
        for (uint256 i = 0; i < 8; i++) {{
            vm.store(target, bytes32(i), bytes32(0));
        }}
        vm.prank(attacker);
        (bool ok, ) = target.call(abi.encodeWithSelector(selector, a0, a1));
        // P2: reachable selfdestruct drains the balance
        assertEq(target.balance, 1 ether, "P2-SELFDESTRUCT-REACHABLE");
        // P1: unprotected write of caller-controlled value (admin/owner slot pattern)
        for (uint256 i = 0; i < 8; i++) {{
            assertTrue(
                vm.load(target, bytes32(i)) != bytes32(uint256(uint160(attacker))),
                "P1-UNPROTECTED-WRITE"
            );
        }}
    }}
"""

def fetch_code(con, h):
    (code,) = con.execute(
        "SELECT substring(bytecode, 3) FROM bytecodes WHERE bytecode_hash = ?", [h]
    ).fetchone()
    return "hex\"" + code + "\""

def main():
    con = duckdb.connect(DB, read_only=True)
    parts = []
    idx = 0

    # ground-truth controls
    for name, path in CONTROLS.items():
        code = open(path).read().strip()
        if code.startswith("0x"):
            code = code[2:]  # hex"" literals reject the 0x prefix
        parts.append(TEMPLATE.format(
            label=f"CONTROL {'must FAIL' if name.startswith('vuln') else 'must PASS'}",
            hash=name, ops="control", fname=name, idx=idx, code=f"hex\"{code}\""))
        idx += 1

    # radar candidates
    for label, sql in CANDIDATE_QUERIES.items():
        for h, ops in con.execute(sql).fetchall():
            code = fetch_code(con, h)
            parts.append(TEMPLATE.format(
                label=label, hash=h, ops=ops,
                fname=f"{label}_{idx}", idx=idx, code=code))
            idx += 1

    src = """// SPDX-License-Identifier: UNLICENSED
// AUTO-GENERATED by gen_probe.py -- bytecode probe batch 1
pragma solidity ^0.8.13;

import {Test} from "forge-std/Test.sol";

contract ProbeBatch1 is Test {
""" + "\n".join(parts) + "}\n"

    with open(OUT, "w") as f:
        f.write(src)
    print(f"wrote {OUT} with {idx} probes ({len(src):,} bytes)", flush=True)

if __name__ == "__main__":
    main()
