#!/usr/bin/env python3
"""Track A generator (v4) — concrete selectors + selectable state models.

Emits, per class:

    harness/stages/stage<stage>/Stage<stage>Chunk_<n>.sol
    harness/stages/stage<stage>/chunk_<n>.tests
    harness/stages/stage<stage>/manifest.json

v4 over v3 (FN/FP hardening):
  * **Concrete selectors.** Each dispatcher entry becomes its own test with a
    literal `bytes4(hex"…")` — no symbolic selector, so no 2^32 branching (the
    reason every safe proof cost ~1 h) and no reliance on a disjunction.
  * **Family-first ordering.** The class's own selector family (initialize /
    upgrade / sync…) is probed first, then the remaining dispatcher entries,
    capped at `--sel-cap` per target.
  * **Three state models** (see ProbeBaseA): `zeroed`, `seeded` (fresh symbolic
    per watched slot — sound, catches writes of zero), `arbitrary` (heaviest).
    Default `seeded`; controls run `zeroed,seeded`.
  * **No-surface accounting.** Targets with no detected dispatcher are counted in
    the manifest (`skipped_no_surface`) instead of being silently dropped.

Usage in CI/HF (bytecodes from the hosted compact parquet):
    python3 scripts/gen_track_a.py --class a7 \
      --targets-parquet /data/a7_unchecked.parquet \
      --bytecodes-parquet /data/tracka_bytecodes.parquet \
      --models seeded --stage tracka_a7 --out /out/stages
"""
import argparse
import json
import os
import string

from Crypto.Hash import keccak

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
CTRL = os.path.join(ROOT, "harness", "controls")
OUTROOT = os.path.join(ROOT, "harness", "stages")

CLASSES = {
    "a1": ("a1_init", "SINGLE", ("VulnerableInit", "SafeInit")),
    "a2": ("a2_upgrade", "SINGLE", ("VulnerableUpgrade", "SafeUpgrade")),
    "a6": ("a6_fee", "SINGLE", ("VulnerableFee", "SafeFee")),
    "a7": ("a7_unchecked", "SINGLE", ("VulnerableUnchecked", "SafeUnchecked")),
    "a9": ("a9_unauth_pull", "PULL", ("VulnerablePull", "SafePull")),
    "a5": ("a5_multicall", "VALUE", ("VulnerableValue", "SafeValue")),
}
ORDER = ["a1", "a2", "a5", "a6", "a7", "a9"]
BASE = {"a1": 0x1000000, "a2": 0x1100000, "a6": 0x1600000, "a7": 0x1700000,
        "a9": 0x1900000, "a5": 0x1500000}
MODEL_CONST = {"zeroed": ("M_ZEROED", "z"), "seeded": ("M_SEEDED", "e"),
               "arbitrary": ("M_ARBITRARY", "a")}

T = string.Template


def k4(sig: str) -> str:
    h = keccak.new(digest_bits=256)
    h.update(sig.encode())
    return h.hexdigest()[:8]


# class families: probed first, in this order
FAMILIES = {
    "a1": ["initialize()", "initialize(address)", "initialize(address,address)",
           "initialize(uint256)", "initialize(uint8,address)",
           "initialize(address,address,address)", "reinitialize()",
           "reinitialize(address)", "init()", "init(address)"],
    "a2": ["upgradeTo(address)", "upgradeToAndCall(address,bytes)",
           "upgrade(address)", "setImplementation(address)", "changeAdmin(address)",
           "updateImplementation(address)", "setImplementationAddress(address)"],
    "a6": ["sync()", "sync(address)", "skim()", "skim(address)"],
    "a7": [],
    "a9": ["transferFrom(address,address,uint256)",
           "safeTransferFrom(address,address,uint256)",
           "safeTransferFrom(address,address,uint256,bytes)",
           "safeBatchTransferFrom(address,address,uint256[],uint256[],bytes)"],
    "a5": ["multicall(bytes[])", "multicall(uint256,bytes[])", "batch(bytes[])",
           "executeBatch(bytes[])", "aggregate((address,bytes)[])"],
}
FAMILY_SELS = {c: [k4(s) for s in sigs] for c, sigs in FAMILIES.items()}

# control selector sets (concrete, from their real signatures)
CONTROL_SIGS = {
    "VulnerableInit": ["initialize(address)"],
    "SafeInit": ["initialize(address)"],
    "VulnerableUpgrade": ["upgradeTo(address)"],
    "SafeUpgrade": ["upgradeTo(address)"],
    "VulnerableFee": ["sync()", "donate(uint256)"],
    "SafeFee": ["sync()", "donate(uint256)"],
    "VulnerableUnchecked": ["pay(address,uint256)"],
    "SafeUnchecked": ["pay(address,uint256)"],
    "VulnerablePull": ["pull(address,uint256)"],
    "SafePull": ["pull(address,uint256)"],
    "VulnerableValue": ["depositAndClaim()"],
    "SafeValue": ["depositAndClaim()"],
}

HDR = T("""// SPDX-License-Identifier: UNLICENSED
// AUTO-GENERATED by gen_track_a.py -- stage $stage, chunk $chunk ($cls)
pragma solidity ^0.8.13;

import {ProbeBaseA} from "../src/ProbeBaseA.sol";

contract Stage${stage}Chunk_$chunk is ProbeBaseA {
$body
""")

SINGLE_BODY = T("""
    function _probeSingle(
        bytes memory code, uint256 idx, bytes4 selector,
        uint256 a0, uint256 a1, address attacker, uint8 model
    ) internal {
        address target = address(uint160(0x${base} + idx));
        _assumeAttacker(attacker, target);
        vm.etch(target, code);
        vm.deal(target, 1 ether);
        _seed(target, model);
        _snapshotTarget(target);
        _snapshotTokens();
        _markBalances(target, attacker);
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selector, a0, a1));
        _checkTarget(target, attacker, model);
    }
$probes}
""")

PULL_BODY = T("""
    address internal constant VICTIM = 0x0000000000000000000000000000000000002222;

    function _probePull(
        bytes memory code, uint256 idx, bytes4 selector, uint256 amt,
        address attacker, uint8 model
    ) internal {
        address target = address(uint160(0x${base} + idx));
        _assumeAttackerVictim(attacker, target, VICTIM);
        vm.etch(target, code);
        vm.deal(target, 1 ether);
        _seed(target, model);
        _seedVictim(VICTIM, target, 1_000 ether, 1_000 ether);
        _snapshotTokens();
        vm.assume(amt <= 1_000 ether);
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selector, VICTIM, amt));
        _checkVictim(VICTIM);
    }
$probes}
""")

VALUE_BODY = T("""
    function _probeValue(
        bytes memory code, uint256 idx, bytes4 selector,
        uint256 a0, uint256 a1, address attacker, uint8 model
    ) internal {
        address target = address(uint160(0x${base} + idx));
        _assumeAttacker(attacker, target);
        vm.etch(target, code);
        vm.deal(target, 2 ether);
        _seed(target, model);
        vm.assume(a0 > 0);
        vm.assume(a0 <= 1 ether);
        vm.deal(attacker, a0);
        _markBalances(target, attacker);
        vm.prank(attacker);
        target.call{value: a0}(abi.encodeWithSelector(selector, a0, a1));
        _checkValue(target, attacker);
    }
$probes}
""")

CODE = T("""    function _code_$i() internal pure returns (bytes memory) { return hex"$code"; }""")

SINGLE_TEST = T("""    function test_${cls}_c${chunk}_${i}_${sel}_${suffix}(
        uint256 a0, uint256 a1, address attacker
    ) public {
        _probeSingle(_code_$i(), $i, bytes4(hex"${sel}"), a0, a1, attacker, ${model});
    }""")

PULL_TEST = T("""    function test_${cls}_c${chunk}_${i}_${sel}_${suffix}(
        uint256 amt, address attacker
    ) public {
        _probePull(_code_$i(), $i, bytes4(hex"${sel}"), amt, attacker, ${model});
    }""")

VALUE_TEST = T("""    function test_${cls}_c${chunk}_${i}_${sel}_${suffix}(
        uint256 a0, uint256 a1, address attacker
    ) public {
        _probeValue(_code_$i(), $i, bytes4(hex"${sel}"), a0, a1, attacker, ${model});
    }""")

BODIES = {"SINGLE": SINGLE_BODY, "PULL": PULL_BODY, "VALUE": VALUE_BODY}
TESTS = {"SINGLE": SINGLE_TEST, "PULL": PULL_TEST, "VALUE": VALUE_TEST}


def control_code(name):
    with open(os.path.join(CTRL, name + ".hex")) as fh:
        c = fh.read().strip()
    return c[2:] if c.startswith("0x") else c


def order_sels(disp_sel, cls, cap):
    """Family selectors first, then the remaining dispatcher entries."""
    toks = [t for t in str(disp_sel or "").replace(",", " ").split() if len(t) == 8]
    seen, out = set(), []
    for s in FAMILY_SELS[cls]:
        if s in toks and s not in seen:
            out.append(s); seen.add(s)
    for s in toks:
        if s not in seen:
            out.append(s); seen.add(s)
    return out[:cap]


def emit_probes(cls, chunk, items, base, models, sel_cap):
    """items: [{i, code, label, sels}]; returns (body, tests, n_skipped)."""
    template = CLASSES[cls][1]
    probes, tests, skipped = [], [], 0
    for it in items:
        sels = it["sels"][:sel_cap] if it["sels"] else []
        if not sels:
            skipped += 1
            continue
        i = it["i"]
        block = "    // " + it["label"] + "\n"
        block += CODE.substitute(i=i, code=it["code"]) + "\n\n"
        for s in sels:
            for m in models:
                mconst, suffix = MODEL_CONST[m]
                block += TESTS[template].substitute(
                    cls=cls, chunk=chunk, i=i, sel=s, suffix=suffix, model=mconst) + "\n\n"
                tests.append(f"test_{cls}_c{chunk}_{i}_{s}{suffix}")
        probes.append(block)
    body = BODIES[template].substitute(base=f"{base:x}", probes="".join(probes))
    return body, tests, skipped


def chunk_targets(items):
    out, small, mid = [], [], []
    for it in items:
        ops = it["n_ops"]
        if ops > 1500:
            if small:
                out.append(small); small = []
            if mid:
                out.append(mid); mid = []
            out.append([it])
        elif ops > 600:
            mid.append(it)
            if len(mid) == 2:
                out.append(mid); mid = []
        else:
            small.append(it)
            if len(small) == 2:
                out.append(small); small = []
    if mid:
        out.append(mid)
    if small:
        out.append(small)
    return out


def load_targets(args, scanner):
    if args.targets_parquet:
        import duckdb
        con = duckdb.connect(":memory:")
        rows = con.execute(
            "SELECT bytecode_hash, n_ops, code_size_eff, deploys, disp_sel "
            "FROM read_parquet(?) ORDER BY deploys DESC", [args.targets_parquet]
        ).fetchall()
        con.close()
        items = [{"hash": h, "n_ops": int(o), "code_size_eff": int(s),
                  "deploys": int(d), "disp_sel": ds} for h, o, s, d, ds in rows]
    else:
        path = args.targets or os.path.join(ROOT, "data", "stages", scanner + "_targets.json")
        man = json.load(open(path))
        items = [{"hash": t["hash"], "n_ops": t.get("n_ops", 0),
                  "code_size_eff": t.get("code_size_eff", 0),
                  "deploys": t.get("deploys", 0),
                  "disp_sel": t.get("disp_sel", "")} for t in man.get("targets", [])]
    if args.limit and args.limit > 0:
        items = items[: args.limit]
    return items


def bytecode_source(args):
    if not args.controls_only and not (args.db or args.bytecodes_parquet):
        raise SystemExit("target generation needs --db or --bytecodes-parquet")
    import duckdb
    con = duckdb.connect(":memory:")
    con.execute("SET threads=4")
    if args.db:
        con.execute(f"ATTACH '{args.db}' AS eth (READ_ONLY)")
        view = "eth.bytecodes"
    else:
        view = f"read_parquet('{args.bytecodes_parquet}')"
    con.execute(f"CREATE VIEW bytecodes_v AS SELECT bytecode_hash, bytecode FROM {view}")

    def fetch(h):
        row = con.execute("SELECT bytecode FROM bytecodes_v WHERE bytecode_hash = ?",
                          [h]).fetchone()
        if row is None:
            return None
        code = row[0]
        if isinstance(code, (bytes, bytearray)):
            code = bytes(code).hex()
        else:
            code = str(code).strip()
            if code.startswith("\\x"):
                code = code[2:]
            if code.startswith("0x"):
                code = code[2:]
        return code

    return fetch


def write_stage(stage, chunks, outroot=None):
    outdir = os.path.join(outroot or OUTROOT, "stage" + stage)
    os.makedirs(outdir, exist_ok=True)
    for f in os.listdir(outdir):
        if f.startswith("Stage") or f.startswith("chunk_") or f == "manifest.json":
            os.remove(os.path.join(outdir, f))
    manifest = {"stage": stage, "chunks": []}
    for ci, body, tests, cls, targets in chunks:
        src = HDR.substitute(stage=stage, chunk=ci, cls=cls, body=body)
        with open(os.path.join(outdir, f"Stage{stage}Chunk_{ci}.sol"), "w") as fh:
            fh.write(src)
        with open(os.path.join(outdir, f"chunk_{ci}.tests"), "w") as fh:
            fh.write("\n".join(tests) + "\n")
        manifest["chunks"].append({"chunk": ci, "class": cls, "tests": tests, "targets": targets})
        print(f"  wrote Stage{stage}Chunk_{ci}.sol ({len(targets)} targets, {len(tests)} tests)",
              flush=True)
    with open(os.path.join(outdir, "manifest.json"), "w") as fh:
        json.dump(manifest, fh, indent=1)
    print(f"[{stage}] {len(chunks)} chunks", flush=True)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--class", dest="cls", required=True, choices=ORDER)
    ap.add_argument("--controls-only", action="store_true")
    ap.add_argument("--targets", default=None)
    ap.add_argument("--targets-parquet", default=None)
    ap.add_argument("--db", default=None)
    ap.add_argument("--bytecodes-parquet", default=None)
    ap.add_argument("--limit", type=int, default=0)
    ap.add_argument("--stage", default=None)
    ap.add_argument("--out", default=None)
    ap.add_argument("--models", default="seeded", help="comma list: zeroed,seeded,arbitrary")
    ap.add_argument("--control-models", default="zeroed,seeded")
    ap.add_argument("--sel-cap", type=int, default=8)
    args = ap.parse_args()

    models = [m.strip() for m in args.models.split(",") if m.strip()]
    cmodels = [m.strip() for m in args.control_models.split(",") if m.strip()]
    cls = args.cls
    scanner, template, (vuln, safe) = CLASSES[cls]
    stage = args.stage or f"tracka_{cls}"
    base = BASE[cls]

    chunks = []
    # ---- chunk 0: controls, concrete selectors, both models ----
    items = []
    for i, (kind, cname) in enumerate((("MUST_FAIL", vuln), ("MUST_PASS", safe))):
        items.append({"i": i, "code": control_code(cname), "label": f"{kind} {cname}",
                      "sels": [k4(s) for s in CONTROL_SIGS[cname]]})
    body, tests, _ = emit_probes(cls, 0, items, base, cmodels, 16)
    chunks.append((0, body, tests, "CONTROLS", []))

    skipped = 0
    if not args.controls_only:
        targets = load_targets(args, scanner)
        if not targets:
            raise SystemExit(f"no targets for {scanner}")
        fetch = bytecode_source(args)
        missing = 0
        for gi, group in enumerate(chunk_targets(targets), start=1):
            probe_items, meta = [], []
            for i, t in enumerate(group):
                code = fetch(t["hash"])
                if not code:
                    missing += 1
                    continue
                probe_items.append({"i": i, "code": code,
                                    "sels": order_sels(t.get("disp_sel"), cls, args.sel_cap),
                                    "label": f"{scanner} [{t['n_ops']} ops, {t['deploys']:,} deploys] {t['hash']}"})
                meta.append({"hash": t["hash"], "n_ops": t["n_ops"],
                             "deploys": t["deploys"], "idx": i})
            if not probe_items:
                continue
            body, tests, sk = emit_probes(cls, gi, probe_items, base, models, args.sel_cap)
            skipped += sk
            if not tests:
                continue
            chunks.append((gi, body, tests, scanner, meta))
        print(f"[{stage}] targets={len(targets)} chunks={len(chunks)-1} "
              f"missing_bytecode={missing} skipped_no_surface={skipped} "
              f"models={models} sel_cap={args.sel_cap}", flush=True)

    write_stage(stage, chunks, args.out)


if __name__ == "__main__":
    main()
