#!/usr/bin/env python3
"""Unified per-stage target generator for the bytecode proof campaign.

Reads the metadata-stripped opcode radar (`opcode_features`) joined with
`contracts` and emits, per stage:

  harness/stages/stage<N>/
      Stage<N>Chunk_<c>.sol     one chunk = 1..N probes (size-class partitioned)
      chunk_<c>.tests           newline list of test names (for the CI loop)
      manifest.json             per-probe: hash, ops, deployments, class,
                                state model, embedded deployment addresses

Property suite (shared ProbeBase, ABI-agnostic, real bytecode via KEVM):
  P_BALANCE_LOST       target ETH balance must not drop
  P_ATTACKER_PROFIT    attacker ETH balance must not rise
  P_STORAGE_CHANGED    no slot in 0..15 may change            (arbitrary injection/Wave-2)
  P_AUTH_WRITE         no slot in 0..15 may equal the attacker
  P_TOKEN_OUTFLOW      no ERC-20 transfer/transferFrom leaves the target
  P_TOKEN_APPROVAL     no ERC-20 allowance is granted
  P_TOKEN_TO_ATTACKER  no ERC-20 transfer is directed at the attacker

Controls are ALWAYS chunk 0; each stage has MUST-FAIL and MUST-PASS controls.
"""
import argparse
import json
import os
import duckdb

DB = "/tmp/eth-contracts/eth_contracts.duckdb"
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONTROLS = os.path.join(ROOT, "harness", "controls")

QUERIES = {
    1: {
        "P1_AUTH_WRITE": """
            SELECT o.bytecode_hash, o.n_ops, count(*) n
            FROM opcode_features o JOIN contracts c USING (bytecode_hash)
            WHERE o.sig_sstore_no_caller AND o.sig_delegate
              AND o.code_size_eff BETWEEN 40 AND 16000
            GROUP BY 1,2 ORDER BY n DESC, 1 ASC LIMIT {limit}""",
        "P2_BALANCE": """
            SELECT o.bytecode_hash, o.n_ops, count(*) n
            FROM opcode_features o JOIN contracts c USING (bytecode_hash)
            WHERE o.sig_selfdestruct AND o.sig_delegate
              AND o.code_size_eff BETWEEN 40 AND 16000
            GROUP BY 1,2 ORDER BY n DESC, 1 ASC LIMIT {limit}""",
    },
    2: {
        "P4_TWO_PHASE": """
            SELECT o.bytecode_hash, o.n_ops, count(*) n
            FROM opcode_features o JOIN contracts c USING (bytecode_hash)
            WHERE o.sig_transient_caller AND o.n_ops BETWEEN 80 AND 1500
            GROUP BY 1,2 ORDER BY n DESC, 1 ASC LIMIT {limit}""",
        "P3_PROXY": """
            SELECT o.bytecode_hash, o.n_ops, count(*) n
            FROM opcode_features o JOIN contracts c USING (bytecode_hash)
            WHERE o.sig_proxy_like AND o.code_size_eff BETWEEN 20 AND 2000
            GROUP BY 1,2 ORDER BY n DESC, 1 ASC LIMIT {limit}""",
    },
    3: {
        # P7 value-extraction oracle over a bounded call sequence, on div-dense code
        "P7_PROFIT": """
            SELECT o.bytecode_hash, o.n_ops, count(*) n
            FROM opcode_features o JOIN contracts c USING (bytecode_hash)
            WHERE o.sig_div_heavy AND o.n_ops BETWEEN 100 AND 3000
              AND o.code_size_eff BETWEEN 200 AND 16000
            GROUP BY 1,2 ORDER BY n DESC, 1 ASC LIMIT {limit}""",
    },
}

HDR = """// SPDX-License-Identifier: UNLICENSED
// AUTO-GENERATED by gen_stage.py -- stage {stage}, chunk {chunk} ({cls})
pragma solidity ^0.8.13;

import {{ProbeBase}} from "../src/ProbeBase.sol";

contract Stage{stage}Chunk_{chunk} is ProbeBase {{
"""

SETUP = """        vm.assume(attacker != address(0));
        vm.assume(uint256(uint160(attacker)) > 0xff);
        vm.assume(attacker != address(0x7109709ECfa91a80626fF3989D68f67F5b1DD12D));
        vm.assume(attacker != address(0x000000000000000000636F6e736F6c652e6c6f67));
        address target = address(uint160(0x{base:x} + {idx}));
        vm.assume(attacker != target);
        vm.etch(target, hex"{code}");
        vm.deal(target, 1 ether);
        _etchTokens();
        for (uint256 i = 0; i < 16; i++) vm.store(target, bytes32(i), bytes32(0));
        bytes32[16] memory before;
        for (uint256 i = 0; i < 16; i++) before[i] = vm.load(target, bytes32(i));
        uint256 bal0 = target.balance;
        uint256 atk0 = attacker.balance;
"""

CHECKS = """        assertEq(target.balance, bal0, "P_BALANCE_LOST");
        assertLe(attacker.balance, atk0, "P_ATTACKER_PROFIT");
        for (uint256 i = 0; i < 16; i++) {{
            bytes32 now = vm.load(target, bytes32(i));
            assertEq(uint256(now), uint256(before[i]), "P_STORAGE_CHANGED");
            assertTrue(now != bytes32(uint256(uint160(attacker))), "P_AUTH_WRITE");
        }}
        _checkTokens(attacker);
"""

SINGLE = "\n    // {label}\n    function {name}(\n        bytes4 selector, uint256 a0, uint256 a1, address attacker\n    ) public {{\n" \
    + SETUP + "        vm.prank(attacker);\n        target.call(abi.encodeWithSelector(selector, a0, a1));\n" + CHECKS + "    }}\n"

TWO_PHASE = "\n    // {label}\n    function {name}(\n        bytes4 selA, uint256 prime, bytes4 selB, uint256 a, uint256 b, address attacker\n    ) public {{\n" \
    + SETUP + "        vm.prank(attacker);\n        target.call(abi.encodeWithSelector(selA, prime));\n" \
    + "        vm.prank(attacker);\n        target.call(abi.encodeWithSelector(selB, a, b));\n" + CHECKS + "    }}\n"

MULTI = "\n    // {label}\n    function {name}(\n        bytes4 s1, uint256 x1, bytes4 s2, uint256 x2, bytes4 s3, uint256 x3, address attacker\n    ) public {{\n" \
    + SETUP + "        vm.prank(attacker);\n        target.call(abi.encodeWithSelector(s1, x1));\n" \
    + "        vm.prank(attacker);\n        target.call(abi.encodeWithSelector(s2, x2));\n" \
    + "        vm.prank(attacker);\n        target.call(abi.encodeWithSelector(s3, x3));\n" + CHECKS + "    }}\n"

PROXY = """    // {label}
    function {name}(bytes4 selector, uint256 a, address attacker) public {{
        vm.assume(attacker != address(0));
        vm.assume(uint256(uint160(attacker)) > 0xff);
        vm.assume(attacker != address(0x7109709ECfa91a80626fF3989D68f67F5b1DD12D));
        vm.assume(attacker != address(0x000000000000000000636F6e736F6c652e6c6f67));
        address canary = address(uint160(0xC0DEC0DE));
        vm.etch(canary, hex"{killer}");
        address target = address(uint160(0x{base:x} + {idx}));
        vm.assume(attacker != target);
        // slot 0 is seeded with `canary`; without this assume the solver picks
        // attacker == canary and P_AUTH_WRITE fires synthetically on every proxy.
        vm.assume(attacker != canary);
        vm.etch(target, hex"{code}");
        vm.deal(target, 1 ether);
        _etchTokens();
        for (uint256 i = 0; i < 16; i++) vm.store(target, bytes32(i), bytes32(0));
        vm.store(target, bytes32(0), bytes32(uint256(uint160(canary))));
        bytes32[16] memory before;
        for (uint256 i = 0; i < 16; i++) before[i] = vm.load(target, bytes32(i));
        uint256 bal0 = target.balance;
        uint256 atk0 = attacker.balance;
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selector, a));
""" + CHECKS + """    }}
"""


def fetch_code(con, h):
    row = con.execute("SELECT bytecode FROM bytecodes WHERE bytecode_hash = ?", [h]).fetchone()
    code = row[0]
    if isinstance(code, (bytes, bytearray)):
        code = bytes(code).hex()
    else:
        code = code.strip()
        if code.startswith("\\x"):
            code = code[2:]
        if code.startswith("0x"):
            code = code[2:]
    return code


def control_code(name):
    with open(os.path.join(CONTROLS, name + ".hex")) as f:
        c = f.read().strip()
    return c[2:] if c.startswith("0x") else c


def chunk_targets(items, class_name):
    out, small, mid = [], [], []
    for it in items:
        ops = it["ops"]
        if ops > 1500:
            if small:
                out.append(small); small = []
            if mid:
                out.append(mid); mid = []
            out.append([it])
        elif ops > 600:
            mid.append(it)
            if len(mid) == 2:
                out.append(mid); mid = []
        else:
            small.append(it)
            size = 5 if class_name in ("P1_AUTH_WRITE", "P2_BALANCE", "P3_PROXY") else 2
            if len(small) == size:
                out.append(small); small = []
    if mid:
        out.append(mid)
    if small:
        out.append(small)
    return out


def controls_for(stage):
    if stage == 1:
        return [("CONTROL_MUST_FAIL", "VulnerableControl", "test_control_vulnerable"),
                ("CONTROL_MUST_PASS", "SafeControl", "test_control_safe")]
    if stage == 3:
        return [("CONTROL_MUST_FAIL", "VulnerableProfit", "test_control_vulnerable_profit"),
                ("CONTROL_MUST_PASS", "SafeProfit", "test_control_safe_profit"),
                ("CONTROL_MUST_FAIL", "VulnerableAmplify", "test_control_vulnerable_amplify"),
                ("CONTROL_MUST_PASS", "SafeAmplify", "test_control_safe_amplify")]
    return [("CONTROL_MUST_FAIL", "VulnerableTransient", "test_control_vulnerable_transient"),
            ("CONTROL_MUST_PASS", "SafeTransient", "test_control_safe_transient"),
            ("CONTROL_MUST_FAIL", "NaiveProxy", "test_control_naive_proxy"),
            ("CONTROL_MUST_PASS", "SafeProxy", "test_control_safe_proxy")]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--stage", type=int, required=True)
    ap.add_argument("--out", default=None)
    ap.add_argument("--limit", type=int, default=8, help="max targets per query")
    ap.add_argument("--emit-chunks", default="", help="comma list; empty = all")
    ap.add_argument("--addr-cap", type=int, default=500,
                    help="max deployment addresses embedded per target")
    ap.add_argument("--controls-only", action="store_true", help="emit chunk 0 only; no DB")
    args = ap.parse_args()

    outdir = args.out or os.path.join(ROOT, "harness", "stages", f"stage{args.stage}")
    os.makedirs(outdir, exist_ok=True)
    for f in os.listdir(outdir):
        if f.startswith(f"Stage{args.stage}Chunk_") or f.startswith("chunk_") or f == "manifest.json":
            os.remove(os.path.join(outdir, f))

    targets = []
    if not args.controls_only:
        con = duckdb.connect(DB, read_only=True)
        con.execute("SET memory_limit='4GB'")
        con.execute("SET threads=4")
        for class_name, sql in QUERIES[args.stage].items():
            for h, ops, n in con.execute(sql.format(limit=args.limit)).fetchall():
                addrs = [a for (a,) in con.execute(
                    "SELECT address FROM contracts WHERE bytecode_hash = ? "
                    "ORDER BY blocknum DESC LIMIT ?", [h, args.addr_cap]).fetchall()]
                targets.append({"hash": h, "ops": ops, "deployments": n,
                                "class": class_name, "state_model": "ZEROED_SLOTS_0_15",
                                "addresses": addrs})

    seen_h = set()
    dedup = []
    for t in targets:
        if t["hash"] in seen_h:
            continue
        seen_h.add(t["hash"])
        dedup.append(t)
    targets = dedup

    per_class = {}
    for t in targets:
        per_class.setdefault(t["class"], []).append(t)
    chunks = [[]]
    for cls, items in per_class.items():
        chunks.extend(chunk_targets(items, cls))

    manifest = {"stage": args.stage, "chunks": []}
    want = set(int(x) for x in args.emit_chunks.split(",")) if args.emit_chunks else None

    for ci, sel in enumerate(chunks):
        if want is not None and ci not in want:
            continue
        if ci == 0:
            parts, tests = [], []
            for kind, cname, tname in controls_for(args.stage):
                code = control_code(cname)
                if args.stage == 1:
                    parts.append(SINGLE.format(label=f"{kind} {cname}", name=tname,
                                               base=0x1000000, idx=0, code=code))
                elif args.stage == 3:
                    parts.append(MULTI.format(label=f"{kind} {cname}", name=tname,
                                              base=0x3000000, idx=0, code=code))
                elif cname in ("NaiveProxy", "SafeProxy"):
                    parts.append(PROXY.format(label=f"{kind} {cname}", name=tname,
                                              base=0xC000000, idx=0, code=code,
                                              killer=control_code("KillerImpl")))
                else:
                    parts.append(TWO_PHASE.format(label=f"{kind} {cname}", name=tname,
                                                  base=0xC000000, idx=0, code=code))
                tests.append(tname)
            cls = "CONTROLS"
        else:
            parts, tests = [], []
            for i, t in enumerate(sel):
                code = fetch_code(con, t["hash"])
                tname = f"test_{t['class'].split('_')[0].lower()}_c{ci}_{i}"
                label = f"{t['class']} [{t['ops']} ops, {t['deployments']:,} deployments] {t['hash']}"
                if t["class"] == "P4_TWO_PHASE":
                    body = TWO_PHASE.format(label=label, name=tname, base=0x2000000, idx=i, code=code)
                elif t["class"] == "P3_PROXY":
                    body = PROXY.format(label=label, name=tname, base=0x2000000, idx=i,
                                        code=code, killer=control_code("KillerImpl"))
                elif t["class"] == "P7_PROFIT":
                    body = MULTI.format(label=label, name=tname, base=0x3000000, idx=i, code=code)
                else:
                    body = SINGLE.format(label=label, name=tname, base=0x1000000, idx=i, code=code)
                parts.append(body)
                tests.append(tname)
            cls = "+".join(sorted({t["class"] for t in sel}))
        src = HDR.format(stage=args.stage, chunk=ci, cls=cls) + "".join(parts) + "}\n"
        with open(os.path.join(outdir, f"Stage{args.stage}Chunk_{ci}.sol"), "w") as f:
            f.write(src)
        with open(os.path.join(outdir, f"chunk_{ci}.tests"), "w") as f:
            f.write("\n".join(tests) + "\n")
        manifest["chunks"].append({"chunk": ci, "class": cls, "tests": tests, "targets": sel})
        print(f"wrote Stage{args.stage}Chunk_{ci}.sol ({len(sel)} targets)", flush=True)

    with open(os.path.join(outdir, "manifest.json"), "w") as f:
        json.dump(manifest, f, indent=1)
    print(f"total chunks: {len(chunks)}; manifest written", flush=True)


if __name__ == "__main__":
    main()
