#!/usr/bin/env python3
"""Unified per-stage target generator for the bytecode proof campaign.

Replaces the ad-hoc gen_probe.py / gen_stage2.py. Reads the *metadata-stripped*
opcode radar (`opcode_features`) joined with `contracts` and emits, per stage:

  harness/stages/stage<N>/
      Stage<N>Chunk_<c>.sol     one chunk = 1..N probes (size-class partitioned)
      manifest.json             per-probe metadata: hash, ops, deployments,
                                property class, state model, selectors
      chunk_<c>.tests           newline list of test names (for CI loops)

Design rules (learned from the F4-F9 chaff):
  * targets come from real signals (metadata stripped in opcode_scan.py)
  * every probe is labelled with its property class and state model
  * controls (must-FAIL / must-PASS) are ALWAYS chunk 0 and gate the matrix
  * one prove invocation per test in CI so a timeout never erases verdicts
"""
import argparse
import json
import os
import duckdb

DB = "/tmp/eth-contracts/eth_contracts.duckdb"
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONTROLS = os.path.join(ROOT, "harness", "controls")

# ----------------------------------------------------------------------------
# Target selection queries (deployment-weighted; metadata already stripped)
# ----------------------------------------------------------------------------
QUERIES = {
    1: {
        # P1-AUTH-WRITE: writes storage on a path with no CALLER compare
        "P1_AUTH_WRITE": """
            SELECT o.bytecode_hash, o.n_ops, count(*) n
            FROM opcode_features o JOIN contracts c USING (bytecode_hash)
            WHERE o.sig_sstore_no_caller AND o.sig_delegate
              AND o.code_size_eff BETWEEN 40 AND 16000
            GROUP BY 1,2 ORDER BY n DESC LIMIT {limit}""",
        # P2-BALANCE / P7-PROFIT: selfdestruct reachable next to a delegatecall
        "P2_BALANCE": """
            SELECT o.bytecode_hash, o.n_ops, count(*) n
            FROM opcode_features o JOIN contracts c USING (bytecode_hash)
            WHERE o.sig_selfdestruct AND o.sig_delegate
              AND o.code_size_eff BETWEEN 40 AND 16000
            GROUP BY 1,2 ORDER BY n DESC LIMIT {limit}""",
    },
    2: {
        # P4: two-phase (prime then privileged call) — REAL TSTORE/TLOAD now
        "P4_TWO_PHASE": """
            SELECT o.bytecode_hash, o.n_ops, count(*) n
            FROM opcode_features o JOIN contracts c USING (bytecode_hash)
            WHERE o.sig_transient_caller AND o.n_ops BETWEEN 80 AND 1500
            GROUP BY 1,2 ORDER BY n DESC LIMIT {limit}""",
        # P3: naive proxy (tiny delegatecall target derived from storage)
        "P3_PROXY": """
            SELECT o.bytecode_hash, o.n_ops, count(*) n
            FROM opcode_features o JOIN contracts c USING (bytecode_hash)
            WHERE o.sig_proxy_like AND o.code_size_eff BETWEEN 20 AND 2000
            GROUP BY 1,2 ORDER BY n DESC LIMIT {limit}""",
    },
}

# ----------------------------------------------------------------------------
# Solidity templates
# ----------------------------------------------------------------------------
HDR = """// SPDX-License-Identifier: UNLICENSED
// AUTO-GENERATED by gen_stage.py -- stage {stage}, chunk {chunk} ({cls})
pragma solidity ^0.8.13;

import {{Test}} from "forge-std/Test.sol";

contract Stage{stage}Chunk_{chunk} is Test {{
"""

# single-call: P1 write / P2 balance / P7 attacker-profit
SINGLE = """
    // {label}
    function test_{name}(
        bytes4 selector, uint256 a0, uint256 a1, address attacker
    ) public {{
        vm.assume(attacker != address(0));
        address target = address(uint160(0x{base:x} + {idx}));
        vm.etch(target, hex"{code}");
        vm.deal(target, 1 ether);
        for (uint256 i = 0; i < 8; i++) vm.store(target, bytes32(i), bytes32(0));
        uint256 bal0 = target.balance;
        uint256 atk0 = attacker.balance;
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selector, a0, a1));
        assertEq(target.balance, bal0, "P_BALANCE_LOST");
        assertEq(attacker.balance, atk0, "P_ATTACKER_PROFIT");
        for (uint256 i = 0; i < 8; i++) {{
            assertTrue(vm.load(target, bytes32(i)) != bytes32(uint256(uint160(attacker))), "P_AUTH_WRITE");
        }}
    }}
"""

# two-phase: prime then privileged call (transient/ordering auth)
TWO_PHASE = """
    // {label}
    function test_{name}(
        bytes4 selA, uint256 prime, bytes4 selB, uint256 a, uint256 b, address attacker
    ) public {{
        vm.assume(attacker != address(0));
        address target = address(uint160(0x{base:x} + {idx}));
        vm.etch(target, hex"{code}");
        vm.deal(target, 1 ether);
        for (uint256 i = 0; i < 8; i++) vm.store(target, bytes32(i), bytes32(0));
        uint256 bal0 = target.balance;
        uint256 atk0 = attacker.balance;
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selA, prime));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selB, a, b));
        assertEq(target.balance, bal0, "P_BALANCE_LOST");
        assertEq(attacker.balance, atk0, "P_ATTACKER_PROFIT");
        for (uint256 i = 0; i < 8; i++) {{
            assertTrue(vm.load(target, bytes32(i)) != bytes32(uint256(uint160(attacker))), "P_AUTH_WRITE");
        }}
    }}
"""

# naive proxy: slot0 points at a canary whose fallback selfdestructs
PROXY = """
    // {label}
    function test_{name}(bytes4 selector, uint256 a, address attacker) public {{
        vm.assume(attacker != address(0));
        address canary = address(uint160(0xC0DEC0DE));
        vm.etch(canary, hex"{killer}");
        address target = address(uint160(0x{base:x} + {idx}));
        vm.etch(target, hex"{code}");
        vm.deal(target, 1 ether);
        vm.store(target, bytes32(0), bytes32(uint256(uint160(canary))));
        uint256 bal0 = target.balance;
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selector, a));
        assertEq(target.balance, bal0, "P_PROXY_HIJACK");
    }}
"""


def fetch_code(con, h):
    row = con.execute("SELECT bytecode FROM bytecodes WHERE bytecode_hash = ?", [h]).fetchone()
    code = row[0]
    if isinstance(code, (bytes, bytearray)):
        code = bytes(code).hex()
    else:
        code = code.strip()
        if code.startswith("\\x"):
            code = code[2:]
        if code.startswith("0x"):
            code = code[2:]
    return code


def control_code(name):
    with open(os.path.join(CONTROLS, name + ".hex")) as f:
        c = f.read().strip()
    return c[2:] if c.startswith("0x") else c


def chunk_targets(items, class_name):
    """Size-class partitioning: a giant never shares a chunk."""
    out, small, mid = [], [], []
    for it in items:
        ops = it["ops"]
        if ops > 1500:
            if small:
                out.append(small); small = []
            if mid:
                out.append(mid); mid = []
            out.append([it])
        elif ops > 600:
            mid.append(it)
            if len(mid) == 2:
                out.append(mid); mid = []
        else:
            small.append(it)
            size = 2 if class_name == "P4_TWO_PHASE" else 5
            if len(small) == size:
                out.append(small); small = []
    if mid:
        out.append(mid)
    if small:
        out.append(small)
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--stage", type=int, required=True)
    ap.add_argument("--out", default=None)
    ap.add_argument("--limit", type=int, default=8, help="max targets per query")
    ap.add_argument("--wave", type=int, default=1)
    ap.add_argument("--emit-chunks", default="", help="comma list; empty = all")
    ap.add_argument("--controls-only", action="store_true",
                    help="emit only chunk 0 (controls); no DB access")
    args = ap.parse_args()

    outdir = args.out or os.path.join(ROOT, "harness", "stages", f"stage{args.stage}")
    os.makedirs(outdir, exist_ok=True)

    targets = []
    if not args.controls_only:
        con = duckdb.connect(DB, read_only=True)
        con.execute("SET memory_limit='4GB'")
        con.execute("SET threads=4")
        for class_name, sql in QUERIES[args.stage].items():
            rows = con.execute(sql.format(limit=args.limit)).fetchall()
            for h, ops, n in rows:
                targets.append({"hash": h, "ops": ops, "deployments": n,
                                "class": class_name, "state_model": "ZEROED_SLOTS_0_7"})

    # controls are ALWAYS chunk 0
    if args.stage == 1:
        controls = [
            ("CONTROL_MUST_FAIL", "VulnerableControl", "test_control_vulnerable"),
            ("CONTROL_MUST_PASS", "SafeControl", "test_control_safe"),
        ]
    else:
        controls = [
            ("CONTROL_MUST_FAIL", "VulnerableTransient", "test_control_vulnerable_transient"),
            ("CONTROL_MUST_PASS", "SafeTransient", "test_control_safe_transient"),
            ("CONTROL_MUST_FAIL", "NaiveProxy", "test_control_naive_proxy"),
            ("CONTROL_MUST_PASS", "SafeProxy", "test_control_safe_proxy"),
        ]

    # build chunk list: [controls] + partitioned wild targets
    per_class = {}
    for t in targets:
        per_class.setdefault(t["class"], []).append(t)
    chunks = [[]]
    for cls, items in per_class.items():
        for group in chunk_targets(items, cls):
            chunks.append(group)

    manifest = {"stage": args.stage, "wave": args.wave, "chunks": []}
    want = set(int(x) for x in args.emit_chunks.split(",")) if args.emit_chunks else None

    for ci, sel in enumerate(chunks):
        if want is not None and ci not in want:
            continue
        if ci == 0:
            parts = []
            tests = []
            for kind, cname, tname in controls:
                code = control_code(cname)
                if args.stage == 1:
                    parts.append(SINGLE.format(label=f"{kind} {cname}", name=tname,
                                               base=0x1000000, idx=0, code=code))
                else:
                    # controls for stage 2 use whichever template fits
                    if cname in ("NaiveProxy", "SafeProxy"):
                        parts.append(PROXY.format(label=f"{kind} {cname}", name=tname,
                                                  base=0xC000000, idx=0,
                                                  code=code, killer=control_code("KillerImpl")))
                    else:
                        parts.append(TWO_PHASE.format(label=f"{kind} {cname}", name=tname,
                                                      base=0xC000000, idx=0, code=code))
                tests.append(tname)
            cls = "CONTROLS"
        else:
            parts, tests = [], []
            for i, t in enumerate(sel):
                code = fetch_code(con, t["hash"])
                tname = f"test_p{t['class'].split('_')[0].lower()}_c{ci}_{i}"
                label = f"{t['class']} [{t['ops']} ops, {t['deployments']:,} deployments] {t['hash']}"
                if t["class"] == "P4_TWO_PHASE":
                    body = TWO_PHASE.format(label=label, name=tname, base=0x2000000, idx=i, code=code)
                elif t["class"] == "P3_PROXY":
                    body = PROXY.format(label=label, name=tname, base=0x2000000, idx=i,
                                        code=code, killer=control_code("KillerImpl"))
                else:
                    body = SINGLE.format(label=label, name=tname, base=0x1000000, idx=i, code=code)
                parts.append(body)
                tests.append(tname)
            cls = "+".join(sorted({t["class"] for t in sel}))
        src = HDR.format(stage=args.stage, chunk=ci, cls=cls) + "".join(parts) + "}\n"
        fname = os.path.join(outdir, f"Stage{args.stage}Chunk_{ci}.sol")
        with open(fname, "w") as f:
            f.write(src)
        with open(os.path.join(outdir, f"chunk_{ci}.tests"), "w") as f:
            f.write("\n".join(tests) + "\n")
        manifest["chunks"].append({"chunk": ci, "class": cls, "tests": tests,
                                   "targets": sel})
        print(f"wrote {fname}  ({len(sel)} targets, {len(src):,} bytes)", flush=True)

    with open(os.path.join(outdir, "manifest.json"), "w") as f:
        json.dump(manifest, f, indent=1)
    print(f"total chunks: {len(chunks)}; wrote manifest to {outdir}/manifest.json", flush=True)


if __name__ == "__main__":
    main()
