// AUTO-GENERATED by gen_stage2.py -- stage 2 deep-auth sweep
pragma solidity ^0.8.13;

import {Test} from "forge-std/Test.sol";

contract Stage2Chunk_33 is Test {

    // P4 two-phase (SIR-class): wild transient_caller [P4-HEAVY] (490 deployments): 0xce34d918a05c90910d7e6bd1166b7e2c38b0385199d09ec70278f2708a5b45d9 (490 deployments)
    function test_p4_w34(
        bytes4 selA, uint256 prime, bytes4 selB, uint256 a, uint256 b, address attacker
    ) public {
        vm.assume(attacker != address(0));
        address target = address(uint160(0x3000000 + 0));
        vm.etch(target, hex"608060405260043610610041576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff168063beabacc814610043575b005b34801561004f57600080fd5b506100bc6004803603606081101561006657600080fd5b81019080803573ffffffffffffffffffffffffffffffffffffffff169060200190929190803573ffffffffffffffffffffffffffffffffffffffff169060200190929190803590602001909291905050506100d6565b604051808215151515815260200191505060405180910390f35b60008060009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff1614151561013357600080fd5b6000821415151561014357600080fd5b600073ffffffffffffffffffffffffffffffffffffffff168473ffffffffffffffffffffffffffffffffffffffff1614156101c4578273ffffffffffffffffffffffffffffffffffffffff166108fc839081150290604051600060405180830381858888f193505050501580156101be573d6000803e3d6000fd5b506102ae565b8373ffffffffffffffffffffffffffffffffffffffff1663a9059cbb84846040518363ffffffff167c0100000000000000000000000000000000000000000000000000000000028152600401808373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200182815260200192505050602060405180830381600087803b15801561026757600080fd5b505af115801561027b573d6000803e3d6000fd5b505050506040513d602081101561029157600080fd5b810190808051906020019092919050505015156102ad57600080fd5b5b7fdef7a29b7527efe948e80c798bc4baa6dbfd0ca5d4d8fecda5c30531ac0cbca48383604051808373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020018281526020019250505060405180910390a160019050939250505056fea165627a7a72305820c808920f41f32e532b2425cce3e54efd9937b05d4af4e45a3f7c0c7828b61ea30029");
        vm.deal(target, 1 ether);
        for (uint256 i = 0; i < 8; i++) vm.store(target, bytes32(i), bytes32(0));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selA, prime));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selB, a, b));
        assertEq(target.balance, 1 ether, "P4-SD-AFTER-PRIME");
        for (uint256 i = 0; i < 8; i++) {
            assertTrue(
                vm.load(target, bytes32(i)) != bytes32(uint256(uint160(attacker))),
                "P4-HIJACK-AFTER-PRIME"
            );
        }
    }
}
