// AUTO-GENERATED by gen_stage2.py -- stage 2 deep-auth sweep
pragma solidity ^0.8.13;

import {Test} from "forge-std/Test.sol";

contract Stage2Chunk_39 is Test {

    // P3-lite (naive proxy): wild proxy_like [P3] (4,700,956 deployments): 0x562d59a51820d47f520c975e0b2bcffac644a509749a3161f481f57b6e826d21 (4,700,956 deployments)
    function test_p3_w0(bytes4 selector, uint256 a, address attacker) public {
        vm.assume(attacker != address(0));
        address canary = address(uint160(0xC0DEC0DE));
        vm.etch(canary, hex"608060405260043610601e575f3560e01c80639890220b14603857601f565b5b3373ffffffffffffffffffffffffffffffffffffffff16ff5b603e6040565b005b3373ffffffffffffffffffffffffffffffffffffffff16fffea2646970667358221220180a9a0f37988e0dcbda0da25610bc8aff749e310cc8471973586d2e55ec996d64736f6c63430008210033");
        address target = address(uint160(0x3000000 + 0));
        vm.etch(target, hex"363d3d373d3d3d363d730de8bf93da2f7eecb3d9169422413a9bef4ef6285af43d82803e903d91602b57fd5bf3");
        vm.deal(target, 1 ether);
        vm.store(target, bytes32(0), bytes32(uint256(uint160(canary))));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selector, a));
        assertEq(target.balance, 1 ether, "P3-HIJACKED-DELEGATECALL");
    }


    // P3-lite (naive proxy): wild proxy_like [P3] (4,106,154 deployments): 0x1b460c826a854d61dca82f718e088b8b4c4082ffeb93752d7691bc62c51dc028 (4,106,154 deployments)
    function test_p3_w1(bytes4 selector, uint256 a, address attacker) public {
        vm.assume(attacker != address(0));
        address canary = address(uint160(0xC0DEC0DE));
        vm.etch(canary, hex"608060405260043610601e575f3560e01c80639890220b14603857601f565b5b3373ffffffffffffffffffffffffffffffffffffffff16ff5b603e6040565b005b3373ffffffffffffffffffffffffffffffffffffffff16fffea2646970667358221220180a9a0f37988e0dcbda0da25610bc8aff749e310cc8471973586d2e55ec996d64736f6c63430008210033");
        address target = address(uint160(0x3000000 + 1));
        vm.etch(target, hex"363d3d373d3d3d363d730a252663dbcc0b073063d6420a40319e438cfa595af43d82803e903d91602b57fd5bf3");
        vm.deal(target, 1 ether);
        vm.store(target, bytes32(0), bytes32(uint256(uint160(canary))));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selector, a));
        assertEq(target.balance, 1 ether, "P3-HIJACKED-DELEGATECALL");
    }


    // P3-lite (naive proxy): wild proxy_like [P3] (1,189,974 deployments): 0xf1b574431f3838d9cdff6e701afd5a058652dab5ae5523288a83d5fad7696139 (1,189,974 deployments)
    function test_p3_w2(bytes4 selector, uint256 a, address attacker) public {
        vm.assume(attacker != address(0));
        address canary = address(uint160(0xC0DEC0DE));
        vm.etch(canary, hex"608060405260043610601e575f3560e01c80639890220b14603857601f565b5b3373ffffffffffffffffffffffffffffffffffffffff16ff5b603e6040565b005b3373ffffffffffffffffffffffffffffffffffffffff16fffea2646970667358221220180a9a0f37988e0dcbda0da25610bc8aff749e310cc8471973586d2e55ec996d64736f6c63430008210033");
        address target = address(uint160(0x3000000 + 2));
        vm.etch(target, hex"363d3d373d3d3d363d73059ffafdc6ef594230de44f824e2bd0a51ca5ded5af43d82803e903d91602b57fd5bf3");
        vm.deal(target, 1 ether);
        vm.store(target, bytes32(0), bytes32(uint256(uint160(canary))));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selector, a));
        assertEq(target.balance, 1 ether, "P3-HIJACKED-DELEGATECALL");
    }


    // P3-lite (naive proxy): wild proxy_like [P3] (952,859 deployments): 0x7a3670f78c75958f13f8579474b348612a80af61fa9b61b2c81c415523f17059 (952,859 deployments)
    function test_p3_w3(bytes4 selector, uint256 a, address attacker) public {
        vm.assume(attacker != address(0));
        address canary = address(uint160(0xC0DEC0DE));
        vm.etch(canary, hex"608060405260043610601e575f3560e01c80639890220b14603857601f565b5b3373ffffffffffffffffffffffffffffffffffffffff16ff5b603e6040565b005b3373ffffffffffffffffffffffffffffffffffffffff16fffea2646970667358221220180a9a0f37988e0dcbda0da25610bc8aff749e310cc8471973586d2e55ec996d64736f6c63430008210033");
        address target = address(uint160(0x3000000 + 3));
        vm.etch(target, hex"5836818037808036817364b29dc43e817817cf77468c8dda63d98ce08fb25af43d91908282803e602b57fd5bf3");
        vm.deal(target, 1 ether);
        vm.store(target, bytes32(0), bytes32(uint256(uint160(canary))));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selector, a));
        assertEq(target.balance, 1 ether, "P3-HIJACKED-DELEGATECALL");
    }
}
