// AUTO-GENERATED by gen_stage2.py -- stage 2 deep-auth sweep
pragma solidity ^0.8.13;

import {Test} from "forge-std/Test.sol";

contract Stage2Chunk_42 is Test {

    // P3-lite (naive proxy): wild proxy_like [P3] (234,910 deployments): 0x6f85b7bf10fd7eeba3c5decaca23ec9d0a81bf92a1f8a742dfd778993ef9299f (234,910 deployments)
    function test_p3_w12(bytes4 selector, uint256 a, address attacker) public {
        vm.assume(attacker != address(0));
        address canary = address(uint160(0xC0DEC0DE));
        vm.etch(canary, hex"608060405260043610601e575f3560e01c80639890220b14603857601f565b5b3373ffffffffffffffffffffffffffffffffffffffff16ff5b603e6040565b005b3373ffffffffffffffffffffffffffffffffffffffff16fffea2646970667358221220180a9a0f37988e0dcbda0da25610bc8aff749e310cc8471973586d2e55ec996d64736f6c63430008210033");
        address target = address(uint160(0x3000000 + 0));
        vm.etch(target, hex"363d3d373d3d3d363d730a9077aa8a6e3b6016e9936ae3541a6bf5740eba5af43d82803e903d91602b57fd5bf3");
        vm.deal(target, 1 ether);
        vm.store(target, bytes32(0), bytes32(uint256(uint160(canary))));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selector, a));
        assertEq(target.balance, 1 ether, "P3-HIJACKED-DELEGATECALL");
    }


    // P3-lite (naive proxy): wild proxy_like [P3] (181,117 deployments): 0x69ee2cbcf3b2584bddf960d9b48eb040d6407cb7e8e801470673e8e3ced1222a (181,117 deployments)
    function test_p3_w13(bytes4 selector, uint256 a, address attacker) public {
        vm.assume(attacker != address(0));
        address canary = address(uint160(0xC0DEC0DE));
        vm.etch(canary, hex"608060405260043610601e575f3560e01c80639890220b14603857601f565b5b3373ffffffffffffffffffffffffffffffffffffffff16ff5b603e6040565b005b3373ffffffffffffffffffffffffffffffffffffffff16fffea2646970667358221220180a9a0f37988e0dcbda0da25610bc8aff749e310cc8471973586d2e55ec996d64736f6c63430008210033");
        address target = address(uint160(0x3000000 + 1));
        vm.etch(target, hex"363d3d373d3d3d363d7342bca2a5593c3b6dc2ebaf62db7e7f6e1d2737945af43d82803e903d91602b57fd5bf3");
        vm.deal(target, 1 ether);
        vm.store(target, bytes32(0), bytes32(uint256(uint160(canary))));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selector, a));
        assertEq(target.balance, 1 ether, "P3-HIJACKED-DELEGATECALL");
    }


    // P3-lite (naive proxy): wild proxy_like [P3] (122,920 deployments): 0x799a4f974f93d287ae49f0e18584cb1947812d264b05381befdeea6c4435ff52 (122,920 deployments)
    function test_p3_w14(bytes4 selector, uint256 a, address attacker) public {
        vm.assume(attacker != address(0));
        address canary = address(uint160(0xC0DEC0DE));
        vm.etch(canary, hex"608060405260043610601e575f3560e01c80639890220b14603857601f565b5b3373ffffffffffffffffffffffffffffffffffffffff16ff5b603e6040565b005b3373ffffffffffffffffffffffffffffffffffffffff16fffea2646970667358221220180a9a0f37988e0dcbda0da25610bc8aff749e310cc8471973586d2e55ec996d64736f6c63430008210033");
        address target = address(uint160(0x3000000 + 2));
        vm.etch(target, hex"363d3d373d3d3d363d73cbd2801377b3cd6ae11ee2e3881144f30b1119745af43d82803e903d91602b57fd5bf3");
        vm.deal(target, 1 ether);
        vm.store(target, bytes32(0), bytes32(uint256(uint160(canary))));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selector, a));
        assertEq(target.balance, 1 ether, "P3-HIJACKED-DELEGATECALL");
    }


    // P3-lite (naive proxy): wild proxy_like [P3] (117,900 deployments): 0x13a3439d21726fac58991727a50099eb5e0909aec3908b47136b29ea2cbf64e7 (117,900 deployments)
    function test_p3_w15(bytes4 selector, uint256 a, address attacker) public {
        vm.assume(attacker != address(0));
        address canary = address(uint160(0xC0DEC0DE));
        vm.etch(canary, hex"608060405260043610601e575f3560e01c80639890220b14603857601f565b5b3373ffffffffffffffffffffffffffffffffffffffff16ff5b603e6040565b005b3373ffffffffffffffffffffffffffffffffffffffff16fffea2646970667358221220180a9a0f37988e0dcbda0da25610bc8aff749e310cc8471973586d2e55ec996d64736f6c63430008210033");
        address target = address(uint160(0x3000000 + 3));
        vm.etch(target, hex"363d3d373d3d3d363d730df19407f9bb6db7a7d877973180de70a77765d75af43d82803e903d91602b57fd5bf3");
        vm.deal(target, 1 ether);
        vm.store(target, bytes32(0), bytes32(uint256(uint160(canary))));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selector, a));
        assertEq(target.balance, 1 ether, "P3-HIJACKED-DELEGATECALL");
    }
}
