// AUTO-GENERATED by gen_stage2.py -- stage 2 deep-auth sweep
pragma solidity ^0.8.13;

import {Test} from "forge-std/Test.sol";

contract Stage2Chunk_48 is Test {

    // P3-lite (naive proxy): wild proxy_like [P3] (30,500 deployments): 0xc109ab8d65189cfe0c1305bb91cb136c385883e34ec590e9b769c90da53b5dc4 (30,500 deployments)
    function test_p3_w36(bytes4 selector, uint256 a, address attacker) public {
        vm.assume(attacker != address(0));
        address canary = address(uint160(0xC0DEC0DE));
        vm.etch(canary, hex"608060405260043610601e575f3560e01c80639890220b14603857601f565b5b3373ffffffffffffffffffffffffffffffffffffffff16ff5b603e6040565b005b3373ffffffffffffffffffffffffffffffffffffffff16fffea2646970667358221220180a9a0f37988e0dcbda0da25610bc8aff749e310cc8471973586d2e55ec996d64736f6c63430008210033");
        address target = address(uint160(0x3000000 + 0));
        vm.etch(target, hex"363d3d373d3d3d363d733a5fb753285ac3a67c6b0d03e121921b2a1428be5af43d82803e903d91602b57fd5bf3");
        vm.deal(target, 1 ether);
        vm.store(target, bytes32(0), bytes32(uint256(uint160(canary))));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selector, a));
        assertEq(target.balance, 1 ether, "P3-HIJACKED-DELEGATECALL");
    }


    // P3-lite (naive proxy): wild proxy_like [P3] (30,500 deployments): 0x06c526f7c962e3371b3794f7ccf4d24757962606cf354a49b551f14f30b993c3 (30,500 deployments)
    function test_p3_w37(bytes4 selector, uint256 a, address attacker) public {
        vm.assume(attacker != address(0));
        address canary = address(uint160(0xC0DEC0DE));
        vm.etch(canary, hex"608060405260043610601e575f3560e01c80639890220b14603857601f565b5b3373ffffffffffffffffffffffffffffffffffffffff16ff5b603e6040565b005b3373ffffffffffffffffffffffffffffffffffffffff16fffea2646970667358221220180a9a0f37988e0dcbda0da25610bc8aff749e310cc8471973586d2e55ec996d64736f6c63430008210033");
        address target = address(uint160(0x3000000 + 1));
        vm.etch(target, hex"363d3d373d3d3d363d73b2ce9dfa531ad026eebbc1964685845743c614335af43d82803e903d91602b57fd5bf3");
        vm.deal(target, 1 ether);
        vm.store(target, bytes32(0), bytes32(uint256(uint160(canary))));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selector, a));
        assertEq(target.balance, 1 ether, "P3-HIJACKED-DELEGATECALL");
    }


    // P3-lite (naive proxy): wild proxy_like [P3] (30,371 deployments): 0xa1bd70cc0fd5c69c14af44101b6ea38301e15fcf09a18e8e623605bb6c56a87d (30,371 deployments)
    function test_p3_w38(bytes4 selector, uint256 a, address attacker) public {
        vm.assume(attacker != address(0));
        address canary = address(uint160(0xC0DEC0DE));
        vm.etch(canary, hex"608060405260043610601e575f3560e01c80639890220b14603857601f565b5b3373ffffffffffffffffffffffffffffffffffffffff16ff5b603e6040565b005b3373ffffffffffffffffffffffffffffffffffffffff16fffea2646970667358221220180a9a0f37988e0dcbda0da25610bc8aff749e310cc8471973586d2e55ec996d64736f6c63430008210033");
        address target = address(uint160(0x3000000 + 2));
        vm.etch(target, hex"363d3d373d3d3d363d735fdcaaf9fd567a7a8384be7c466170c7070d269d5af43d82803e903d91602b57fd5bf3");
        vm.deal(target, 1 ether);
        vm.store(target, bytes32(0), bytes32(uint256(uint160(canary))));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selector, a));
        assertEq(target.balance, 1 ether, "P3-HIJACKED-DELEGATECALL");
    }


    // P3-lite (naive proxy): wild proxy_like [P3] (29,761 deployments): 0x0fc52c3bd2c8a757e570c2e4506ed6b312dfd639313d44e828feb8fb6652661d (29,761 deployments)
    function test_p3_w39(bytes4 selector, uint256 a, address attacker) public {
        vm.assume(attacker != address(0));
        address canary = address(uint160(0xC0DEC0DE));
        vm.etch(canary, hex"608060405260043610601e575f3560e01c80639890220b14603857601f565b5b3373ffffffffffffffffffffffffffffffffffffffff16ff5b603e6040565b005b3373ffffffffffffffffffffffffffffffffffffffff16fffea2646970667358221220180a9a0f37988e0dcbda0da25610bc8aff749e310cc8471973586d2e55ec996d64736f6c63430008210033");
        address target = address(uint160(0x3000000 + 3));
        vm.etch(target, hex"363d3d373d3d3d363d7387ae9be718aa310323042ab9806bd6692c1129b75af43d82803e903d91602b57fd5bf3");
        vm.deal(target, 1 ether);
        vm.store(target, bytes32(0), bytes32(uint256(uint160(canary))));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selector, a));
        assertEq(target.balance, 1 ether, "P3-HIJACKED-DELEGATECALL");
    }
}
