// AUTO-GENERATED by gen_stage2.py -- stage 2 deep-auth sweep
pragma solidity ^0.8.13;

import {Test} from "forge-std/Test.sol";

contract Stage2Chunk_29 is Test {

    // P4 two-phase (SIR-class): wild transient_caller [P4-HEAVY] (671 deployments): 0x5fe4097b321a529a5b3b00959bfbd3d29c86f8bb8d06664bf8ba6ea2a76f2007 (671 deployments)
    function test_p4_w30(
        bytes4 selA, uint256 prime, bytes4 selB, uint256 a, uint256 b, address attacker
    ) public {
        vm.assume(attacker != address(0));
        address target = address(uint160(0x3000000 + 0));
        vm.etch(target, hex"606060405236156100495763ffffffff7c01000000000000000000000000000000000000000000000000000000006000350416638da5cb5b8114610052578063b61d27f61461008e575b6100505b5b565b005b341561005d57600080fd5b610065610112565b60405173ffffffffffffffffffffffffffffffffffffffff909116815260200160405180910390f35b341561009957600080fd5b6101006004803573ffffffffffffffffffffffffffffffffffffffff169060248035919060649060443590810190830135806020601f8201819004810201604051908101604052818152929190602084018383808284375094965061012e95505050505050565b60405190815260200160405180910390f35b60005473ffffffffffffffffffffffffffffffffffffffff1681565b600080543373ffffffffffffffffffffffffffffffffffffffff90811691161461015757600080fd5b8373ffffffffffffffffffffffffffffffffffffffff16838360405180828051906020019080838360005b8381101561019b5780820151818401525b602001610182565b50505050905090810190601f1680156101c85780820380516001836020036101000a031916815260200191505b5091505060006040518083038185876187965a03f19250505015156101ec57600080fd5b6000364360405180848480828437909101928352505060200191506040905051809103902090505b5b93925050505600a165627a7a72305820f48ab55d28e53c1a31b37f2f59fa9a2e22982b7c45820551bf0ad04e8b1d3b3f0029");
        vm.deal(target, 1 ether);
        for (uint256 i = 0; i < 8; i++) vm.store(target, bytes32(i), bytes32(0));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selA, prime));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selB, a, b));
        assertEq(target.balance, 1 ether, "P4-SD-AFTER-PRIME");
        for (uint256 i = 0; i < 8; i++) {
            assertTrue(
                vm.load(target, bytes32(i)) != bytes32(uint256(uint160(attacker))),
                "P4-HIJACK-AFTER-PRIME"
            );
        }
    }
}
