// AUTO-GENERATED by gen_stage2.py -- stage 2 deep-auth sweep
pragma solidity ^0.8.13;

import {Test} from "forge-std/Test.sol";

contract Stage2Chunk_2 is Test {

    // P4 two-phase (SIR-class): wild transient_caller [P4-HEAVY] (224,600 deployments): 0xaffe208456e818f69a73122832d6db3a7b93175f3bf83dd7f080d11743c81ea9 (224,600 deployments)
    function test_p4_w1(
        bytes4 selA, uint256 prime, bytes4 selB, uint256 a, uint256 b, address attacker
    ) public {
        vm.assume(attacker != address(0));
        address target = address(uint160(0x3000000 + 0));
        vm.etch(target, hex"60606040526004361061003d5763ffffffff60e060020a60003504166319449cb28114610042578063a6f9dae114610063578063cbf9b84b14610082575b600080fd5b341561004d57600080fd5b610061600160a060020a03600435166100b8565b005b341561006e57600080fd5b610061600160a060020a0360043516610102565b341561008d57600080fd5b6100a4600435600160a060020a036024351661014c565b604051901515815260200160405180910390f35b60005433600160a060020a039081169116146100d357600080fd5b6001805473ffffffffffffffffffffffffffffffffffffffff1916600160a060020a0392909216919091179055565b60005433600160a060020a0390811691161461011d57600080fd5b6000805473ffffffffffffffffffffffffffffffffffffffff1916600160a060020a0392909216919091179055565b60015460009033600160a060020a0390811691161461016a57600080fd5b81600160a060020a03166040517f7472616e7366657228616464726573732c75696e743235362900000000000000815260190160405190819003902060015460e060020a90910490600160a060020a03168560405160e060020a63ffffffff8516028152600160a060020a039092166004830152602482015260440160006040518083038160008761646e5a03f196955050505050505600a165627a7a723058206946e0912b59359002e3918528faab54d5a4353bd0520aeff28f1a4b2e5fb25d0029");
        vm.deal(target, 1 ether);
        for (uint256 i = 0; i < 8; i++) vm.store(target, bytes32(i), bytes32(0));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selA, prime));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selB, a, b));
        assertEq(target.balance, 1 ether, "P4-SD-AFTER-PRIME");
        for (uint256 i = 0; i < 8; i++) {
            assertTrue(
                vm.load(target, bytes32(i)) != bytes32(uint256(uint160(attacker))),
                "P4-HIJACK-AFTER-PRIME"
            );
        }
    }
}
