// AUTO-GENERATED by gen_stage2.py -- stage 2 deep-auth sweep
pragma solidity ^0.8.13;

import {Test} from "forge-std/Test.sol";

contract Stage2Chunk_3 is Test {

    // P4 two-phase (SIR-class): wild transient_caller [P4-SMALL] (39,505 deployments): 0x2bee4af349ccc652c737b5d4106e4e3e8f555a79b0295d6dc48be38b239f2180 (39,505 deployments)
    function test_p4_w2(
        bytes4 selA, uint256 prime, bytes4 selB, uint256 a, uint256 b, address attacker
    ) public {
        vm.assume(attacker != address(0));
        address target = address(uint160(0x3000000 + 0));
        vm.etch(target, hex"608060405236600a57005b348015601557600080fd5b506001546040516001600160a01b03909116903680600083376000808284865af43d9150816000843e8080156048578284f35b8284fdfea2646970667358221220f938a78c3c818182f8206c6a6e05229fedff84f024226e0eea275d8c9e266a0664736f6c634300060c0033");
        vm.deal(target, 1 ether);
        for (uint256 i = 0; i < 8; i++) vm.store(target, bytes32(i), bytes32(0));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selA, prime));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selB, a, b));
        assertEq(target.balance, 1 ether, "P4-SD-AFTER-PRIME");
        for (uint256 i = 0; i < 8; i++) {
            assertTrue(
                vm.load(target, bytes32(i)) != bytes32(uint256(uint160(attacker))),
                "P4-HIJACK-AFTER-PRIME"
            );
        }
    }


    // P4 two-phase (SIR-class): wild transient_caller [P4-SMALL] (17,349 deployments): 0x83baa4b265772664a88dcfc8be0e24e1fe969a3c66f03851c6aa2f5da73cd7fd (17,349 deployments)
    function test_p4_w3(
        bytes4 selA, uint256 prime, bytes4 selB, uint256 a, uint256 b, address attacker
    ) public {
        vm.assume(attacker != address(0));
        address target = address(uint160(0x3000000 + 1));
        vm.etch(target, hex"60806040523615801560115750600034115b156082573373ffffffffffffffffffffffffffffffffffffffff16347f606834f57405380c4fb88d1f4850326ad3885f014bab3b568dfbf7a041eef7386000366040518080602001828103825284848281815260200192508082843760405192018290039550909350505050a360a8565b6000543660008037600080366000845af43d6000803e80801560a3573d6000f35b3d6000fd5b0000a165627a7a7230582009ad600070879c5d9739059132e69cc1b5b90d2b945f553b3f45ceea43d65c8f0029");
        vm.deal(target, 1 ether);
        for (uint256 i = 0; i < 8; i++) vm.store(target, bytes32(i), bytes32(0));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selA, prime));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selB, a, b));
        assertEq(target.balance, 1 ether, "P4-SD-AFTER-PRIME");
        for (uint256 i = 0; i < 8; i++) {
            assertTrue(
                vm.load(target, bytes32(i)) != bytes32(uint256(uint160(attacker))),
                "P4-HIJACK-AFTER-PRIME"
            );
        }
    }
}
