// AUTO-GENERATED by gen_stage2.py -- stage 2 deep-auth sweep
pragma solidity ^0.8.13;

import {Test} from "forge-std/Test.sol";

contract Stage2Chunk_44 is Test {

    // P3-lite (naive proxy): wild proxy_like [P3] (72,139 deployments): 0xf0f301d94d5b08b52928572574b92b11e68d0f858603daf4daafb599c7472d10 (72,139 deployments)
    function test_p3_w20(bytes4 selector, uint256 a, address attacker) public {
        vm.assume(attacker != address(0));
        address canary = address(uint160(0xC0DEC0DE));
        vm.etch(canary, hex"608060405260043610601e575f3560e01c80639890220b14603857601f565b5b3373ffffffffffffffffffffffffffffffffffffffff16ff5b603e6040565b005b3373ffffffffffffffffffffffffffffffffffffffff16fffea2646970667358221220180a9a0f37988e0dcbda0da25610bc8aff749e310cc8471973586d2e55ec996d64736f6c63430008210033");
        address target = address(uint160(0x3000000 + 0));
        vm.etch(target, hex"363d3d373d3d3d363d735397d0869aba0d55e96d5716d383f6e1d8695ed75af43d82803e903d91602b57fd5bf3");
        vm.deal(target, 1 ether);
        vm.store(target, bytes32(0), bytes32(uint256(uint160(canary))));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selector, a));
        assertEq(target.balance, 1 ether, "P3-HIJACKED-DELEGATECALL");
    }


    // P3-lite (naive proxy): wild proxy_like [P3] (68,400 deployments): 0x4bef21f9e794f490c6b32ebdca539e7c6304b241f4632adc77f1ce60063458ec (68,400 deployments)
    function test_p3_w21(bytes4 selector, uint256 a, address attacker) public {
        vm.assume(attacker != address(0));
        address canary = address(uint160(0xC0DEC0DE));
        vm.etch(canary, hex"608060405260043610601e575f3560e01c80639890220b14603857601f565b5b3373ffffffffffffffffffffffffffffffffffffffff16ff5b603e6040565b005b3373ffffffffffffffffffffffffffffffffffffffff16fffea2646970667358221220180a9a0f37988e0dcbda0da25610bc8aff749e310cc8471973586d2e55ec996d64736f6c63430008210033");
        address target = address(uint160(0x3000000 + 1));
        vm.etch(target, hex"363d3d373d3d3d363d7389bf387095cd603035a08036d89bd2089ce091c75af43d82803e903d91602b57fd5bf3");
        vm.deal(target, 1 ether);
        vm.store(target, bytes32(0), bytes32(uint256(uint160(canary))));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selector, a));
        assertEq(target.balance, 1 ether, "P3-HIJACKED-DELEGATECALL");
    }


    // P3-lite (naive proxy): wild proxy_like [P3] (67,089 deployments): 0x352ffb477a9da4a2fa5748e40b9a436e3116f1edf95a3ebbab2a76eabd0971c0 (67,089 deployments)
    function test_p3_w22(bytes4 selector, uint256 a, address attacker) public {
        vm.assume(attacker != address(0));
        address canary = address(uint160(0xC0DEC0DE));
        vm.etch(canary, hex"608060405260043610601e575f3560e01c80639890220b14603857601f565b5b3373ffffffffffffffffffffffffffffffffffffffff16ff5b603e6040565b005b3373ffffffffffffffffffffffffffffffffffffffff16fffea2646970667358221220180a9a0f37988e0dcbda0da25610bc8aff749e310cc8471973586d2e55ec996d64736f6c63430008210033");
        address target = address(uint160(0x3000000 + 2));
        vm.etch(target, hex"363d3d373d3d3d363d737a887b7076810947d957d045559a26f180595f895af43d82803e903d91602b57fd5bf3");
        vm.deal(target, 1 ether);
        vm.store(target, bytes32(0), bytes32(uint256(uint160(canary))));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selector, a));
        assertEq(target.balance, 1 ether, "P3-HIJACKED-DELEGATECALL");
    }


    // P3-lite (naive proxy): wild proxy_like [P3] (66,962 deployments): 0x35551a33c6946132f328624ad488435dd091e52f85871c16c1600158fccf5239 (66,962 deployments)
    function test_p3_w23(bytes4 selector, uint256 a, address attacker) public {
        vm.assume(attacker != address(0));
        address canary = address(uint160(0xC0DEC0DE));
        vm.etch(canary, hex"608060405260043610601e575f3560e01c80639890220b14603857601f565b5b3373ffffffffffffffffffffffffffffffffffffffff16ff5b603e6040565b005b3373ffffffffffffffffffffffffffffffffffffffff16fffea2646970667358221220180a9a0f37988e0dcbda0da25610bc8aff749e310cc8471973586d2e55ec996d64736f6c63430008210033");
        address target = address(uint160(0x3000000 + 3));
        vm.etch(target, hex"363d3d373d3d3d363d7363730a73f5eb2b5e10486d20c10a451aa3c1c6dd5af43d82803e903d91602b57fd5bf3");
        vm.deal(target, 1 ether);
        vm.store(target, bytes32(0), bytes32(uint256(uint160(canary))));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selector, a));
        assertEq(target.balance, 1 ether, "P3-HIJACKED-DELEGATECALL");
    }
}
