// AUTO-GENERATED by gen_stage2.py -- stage 2 deep-auth sweep
pragma solidity ^0.8.13;

import {Test} from "forge-std/Test.sol";

contract Stage2Chunk_25 is Test {

    // P4 two-phase (SIR-class): wild transient_caller [P4-SMALL] (908 deployments): 0xe5b8de762d7c4d3ca64b52e1e25a6150a02792aa1eea54a091f0d2d12a83a0c0 (908 deployments)
    function test_p4_w26(
        bytes4 selA, uint256 prime, bytes4 selB, uint256 a, uint256 b, address attacker
    ) public {
        vm.assume(attacker != address(0));
        address target = address(uint160(0x3000000 + 0));
        vm.etch(target, hex"608060405234801561000f575f80fd5b5060043610610029575f3560e01c80637458e5d91461002d575b5f80fd5b61004061003b366004610114565b610042565b005b5f546001600160a01b031633146100975760405162461bcd60e51b815260206004820152601560248201527443616c6c6572206973206e6f7420666163746f727960581b604482015260640160405180910390fd5b60405163f5878b9b60e01b8152600481018290526001600160a01b03838116602483015284169063f5878b9b906044015f604051808303815f87803b1580156100de575f80fd5b505af11580156100f0573d5f803e3d5ffd5b50505050505050565b80356001600160a01b038116811461010f575f80fd5b919050565b5f805f60608486031215610126575f80fd5b61012f846100f9565b925061013d602085016100f9565b915060408401359050925092509256fea2646970667358221220c5379efba01ad34d5c08b5bca90d212e4f0a417b0c66901004d0f4aa1c4a4c9e64736f6c63430008150033");
        vm.deal(target, 1 ether);
        for (uint256 i = 0; i < 8; i++) vm.store(target, bytes32(i), bytes32(0));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selA, prime));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selB, a, b));
        assertEq(target.balance, 1 ether, "P4-SD-AFTER-PRIME");
        for (uint256 i = 0; i < 8; i++) {
            assertTrue(
                vm.load(target, bytes32(i)) != bytes32(uint256(uint160(attacker))),
                "P4-HIJACK-AFTER-PRIME"
            );
        }
    }
}
