// AUTO-GENERATED by gen_stage2.py -- stage 2 deep-auth sweep
pragma solidity ^0.8.13;

import {Test} from "forge-std/Test.sol";

contract Stage2Chunk_45 is Test {

    // P3-lite (naive proxy): wild proxy_like [P3] (59,343 deployments): 0x6539d93c354d77a449dbdadb4357619da56b1b843e00b48c4af740150fef4cdd (59,343 deployments)
    function test_p3_w24(bytes4 selector, uint256 a, address attacker) public {
        vm.assume(attacker != address(0));
        address canary = address(uint160(0xC0DEC0DE));
        vm.etch(canary, hex"608060405260043610601e575f3560e01c80639890220b14603857601f565b5b3373ffffffffffffffffffffffffffffffffffffffff16ff5b603e6040565b005b3373ffffffffffffffffffffffffffffffffffffffff16fffea2646970667358221220180a9a0f37988e0dcbda0da25610bc8aff749e310cc8471973586d2e55ec996d64736f6c63430008210033");
        address target = address(uint160(0x3000000 + 0));
        vm.etch(target, hex"363d3d373d3d3d363d7362b92d5ad29bc7adffa2904faac28dd0ce3fc65a5af43d82803e903d91602b57fd5bf3");
        vm.deal(target, 1 ether);
        vm.store(target, bytes32(0), bytes32(uint256(uint160(canary))));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selector, a));
        assertEq(target.balance, 1 ether, "P3-HIJACKED-DELEGATECALL");
    }


    // P3-lite (naive proxy): wild proxy_like [P3] (54,138 deployments): 0x19a8d34d710ea01385a9ae240a49b4c561b50df63c4efc576e4f5f17f26a39eb (54,138 deployments)
    function test_p3_w25(bytes4 selector, uint256 a, address attacker) public {
        vm.assume(attacker != address(0));
        address canary = address(uint160(0xC0DEC0DE));
        vm.etch(canary, hex"608060405260043610601e575f3560e01c80639890220b14603857601f565b5b3373ffffffffffffffffffffffffffffffffffffffff16ff5b603e6040565b005b3373ffffffffffffffffffffffffffffffffffffffff16fffea2646970667358221220180a9a0f37988e0dcbda0da25610bc8aff749e310cc8471973586d2e55ec996d64736f6c63430008210033");
        address target = address(uint160(0x3000000 + 1));
        vm.etch(target, hex"363d3d373d3d3d363d73fb547b99356a114d54671915a0f7bf5cec1973f35af43d82803e903d91602b57fd5bf3");
        vm.deal(target, 1 ether);
        vm.store(target, bytes32(0), bytes32(uint256(uint160(canary))));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selector, a));
        assertEq(target.balance, 1 ether, "P3-HIJACKED-DELEGATECALL");
    }


    // P3-lite (naive proxy): wild proxy_like [P3] (51,305 deployments): 0x6c817ba86bcd28512dfcfa8c2f13b737f3b83e57ef527b81f5c715ac729fde0a (51,305 deployments)
    function test_p3_w26(bytes4 selector, uint256 a, address attacker) public {
        vm.assume(attacker != address(0));
        address canary = address(uint160(0xC0DEC0DE));
        vm.etch(canary, hex"608060405260043610601e575f3560e01c80639890220b14603857601f565b5b3373ffffffffffffffffffffffffffffffffffffffff16ff5b603e6040565b005b3373ffffffffffffffffffffffffffffffffffffffff16fffea2646970667358221220180a9a0f37988e0dcbda0da25610bc8aff749e310cc8471973586d2e55ec996d64736f6c63430008210033");
        address target = address(uint160(0x3000000 + 2));
        vm.etch(target, hex"363d3d373d3d3d363d735c0e7822aaaaeb4d4d798a48035b9e92b17fc5775af43d82803e903d91602b57fd5bf3");
        vm.deal(target, 1 ether);
        vm.store(target, bytes32(0), bytes32(uint256(uint160(canary))));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selector, a));
        assertEq(target.balance, 1 ether, "P3-HIJACKED-DELEGATECALL");
    }


    // P3-lite (naive proxy): wild proxy_like [P3] (45,224 deployments): 0xd38220488983895f813b934c9bf4a37b69b425dc2f3835bf26271a8810581968 (45,224 deployments)
    function test_p3_w27(bytes4 selector, uint256 a, address attacker) public {
        vm.assume(attacker != address(0));
        address canary = address(uint160(0xC0DEC0DE));
        vm.etch(canary, hex"608060405260043610601e575f3560e01c80639890220b14603857601f565b5b3373ffffffffffffffffffffffffffffffffffffffff16ff5b603e6040565b005b3373ffffffffffffffffffffffffffffffffffffffff16fffea2646970667358221220180a9a0f37988e0dcbda0da25610bc8aff749e310cc8471973586d2e55ec996d64736f6c63430008210033");
        address target = address(uint160(0x3000000 + 3));
        vm.etch(target, hex"363d3d373d3d3d363d73e38f942db7a1b4213d6213f70c499b59287b01f15af43d82803e903d91602b57fd5bf3");
        vm.deal(target, 1 ether);
        vm.store(target, bytes32(0), bytes32(uint256(uint160(canary))));
        vm.prank(attacker);
        target.call(abi.encodeWithSelector(selector, a));
        assertEq(target.balance, 1 ether, "P3-HIJACKED-DELEGATECALL");
    }
}
